### ISSUE TITLE
Translating Texstudio to other language and other questions

### ISSUE THREAD

**Issue by TSaarela** [texstudio-org/texstudio#1011]
Hi. First of all, this isn't an issue with Texstudio, and I know this is a place to report about bugs, so sorry about that - I just could not find a place to ask a few questions.  I just love Texstudio, and so does few of my friends, who I have introduced this software to.

Anyway, I was looking around the Texstudio website, and other sources, and couldn't find any forums in which Texstudio is discussed. I had some questions, but there seems to be no place to ask them? So that is why I ask here, although I know bug forum place is not really appropriate for that - but where then?

I am, for example, interested in translating Texstudio to Finnish - which is not a small task. But I had no place to ask how I can start doing that? So perhaps people here can tell me?

I can program using C++, and other languages, and have done that before, so I could also do some programming if necessary. 

But my questions are at least at first, for translating the software, so do I need to download the whole source code, and recompile the whole thing? I use Win10 at the moment, and also I was not sure what compiler is used in this project. I can use Visual Studio if necessary, but that is a massive software. I can always install other compilers too. But I wonder what Win10 based compilers are used to compile this? I could use some lighter software if possible, since VS takes enormous amount of disk space. I hope someone can point me into the right direction.

**Comment by muzimuzhi** [comment]
[wiki - Translating](https://github.com/texstudio-org/texstudio/wiki/Translating)

**Comment by MeanSquaredError** [comment]
If you want to build TeXstudio under Windows you will need to install Qt for Windows. When installing it use the Qt package manager to also install the `mingw32` package for Qt.  Do not use a standalone MSYS/MinGW installation since it is difficult to make it work with Qt and TeXstudio build system.

Since Qt and mingw32 does not like spaces in the installation pathname, the Qt installer by default offers you installation in `c:\qt` (I myself use this default location).

After Qt and mingw32 have been installed, it is relatively easy to build TeXstudio. I use the following commands:

```
c:\qt\5.12.6\mingw73_32\bin\qtenv2.bat
c:\Qt\5.12.6\mingw73_32\bin\qmake.exe "CONFIG+=debug" "NO_POPPLER_PREVIEW=true" "NO_TESTS=true"
cd path_to_txs_source
c:\qt\Tools\mingw730_32\bin\mingw32-make.exe
```
In the above example replace `path_to_txs_source` with the actual location of your TeXstudio source code. It will build a debug version of TeXstudio without internal PDF viewer and without automatic tests. If you need the internal PDF viewer, you will also need to install the `poppler` library.

It is also possible to build TeXstudio using Visual Studio 2019 community edition, but it is more involved and (at least for me) requires much more tinkering with the source code and build system to make it work.

**Comment by MeanSquaredError** [comment]
Actually I just saw that there is a Wiki page explaining how to build TeXstudio under Windows:
https://github.com/texstudio-org/texstudio/wiki/Compiling

I haven't used the approach from the Wiki but  the information there might be useful to you my approach does not work for you for whatever reason.

**Comment by tmelorc** [comment]
Today I got an automatic message informing new file to translate from Transifex.
I already did it, but I observed a lot of non translatable strings. It would be good to mark them as non translatable, instead of copying it to translated version. Some strings are codes, so translate them even with the same code, does not make sense I think.
Regards.
