### ISSUE TITLE
Open terminal does not work

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#1046]
### Environment
```
TeXstudio 3.00.00 (git 3.0.0alpha3-15-g5147db65)
Using Qt Version 5.14.2, compiled with Qt 5.14.2 R
OS: Gentoo Linux
```

Compiled latest commit from git on Gentoo Linux to support https://github.com/texstudio-org/texstudio/issues/888 and tested, if https://github.com/texstudio-org/texstudio/pull/898 fixes the problem here too. 

**Clicking on `Open Terminal` does not do anything.** 
Not even a message on STDERR. Do we need specific settings?

https://github.com/texstudio-org/texstudio/issues/888#issuecomment-576333120

**Comment by MeanSquaredError** [comment]
Does this problem happen only in TeXstudio 3 or does it also exist in TexStudio 2.12.x ?

**Comment by KarlMagnusLarsson** [comment]
I can not repeat this on Linux Debian 10.3 (or OSX 10.13.6).

Texstudio 3.00.00 (git 3.0.0alpha3-15-g5147db65)
Using Qt Version 5.11.3, compiled with Qt 5.11.3 R.
OS: Debian Linux 10.3
Tools->Open terminal work for me and opens a terminal at working directory.

Building on OSX, 10.13.6 also work for me.
TeXstudio 3.00.00 (git 3.0.0alpha3-15-g5147db65)
Using Qt Version 5.14.1, compiled with Qt 5.14.1 R

**Comment by jonasstein** [comment]
Yes, same for 2.12.22
```
TeXstudio 2.12.22 (git n/a)
Using Qt Version 5.14.2, compiled with Qt 5.14.2 R
```

Any idea, what I should test?
How do you call the terminal exactly?
I fear it is a bug in our package. Just opened a ticket on Gentoo (https://bugs.gentoo.org/719132)

**Comment by MeanSquaredError** [comment]
FYI, it works correctly on Fedora 31, too.

The terminal command is invoked in `startTerminalEmulator()` defined in `src/utilssystem_unix.cpp`
This function in turn relies on `getTerminalCommand()` (again defined in `src/utilssystem_unix.cpp`) to get the executable pathname of the terminal program.

`getTerminalCommand()` tries a few things in order to get the pathname of the terminal executable:

1. First it tries to run `gsettings get org.gnome.desktop.default-applications.terminal exec`
If that succeeds, it strips the surrounding quotes and uses the result as the executable pathname.
2. If step 1, failed then it tries `which konsole`
3. If step 2, failed then it tries `which xterm`

If all the three methods fail then it returns an empty `QString` which means that the detection failed.

If the detection fails, the caller ( `startTerminalEmulator()` ) should display an error popup.
If the detection is successful then TXS uses `QProcess::startDetached` to run the terminal executable. However I think that we don't really display any error message if the detection of the executable succeeds but the actual execution fails.

So my guess is that the executable is detected but its execution fails for whatever reason. Could it be related to any executable permissions, running TXS without sufficient permissions or another similar problem?

**Comment by jonasstein** [comment]
Tested the following:
```
$ gsettings set org.gnome.desktop.default-applications.terminal exec /usr/bin/xfce4-terminal #set variable to my terminal
$ gsettings get org.gnome.desktop.default-applications.terminal exec
'/usr/bin/xfce4-terminal'
$ /usr/bin/xfce4-terminal # opens terminal
$ texstudio # now Open Terminal ... nothing happens
```

Is this related to https://gitlab.gnome.org/GNOME/glib/issues/338?
Do we need a user config for the terminal command?

**Comment by MeanSquaredError** [comment]
I am not sure why after running
`gsettings get org.gnome.desktop.default-applications.terminal exec`
TeXstudio is unable to find the proper terminal application. However I agree that having a separate configuration setting to specify an external terminal application is probably the best solution.

@sunderme , @timhoffm  what do you think about having a setting for an external terminal application? I guess I could prepare a PR for that if you think that it is an OK solution.

**Comment by timhoffm** [comment]
👍 for an external terminal setting. The default value should be created from our current logic. But if that fails or the user wants to have another terminal, he can explicitly define that.

**Comment by MeanSquaredError** [comment]
OK, I will try to prepare the patch this weekend.

**Comment by jonasstein** [comment]
Thank you. Works fine on Gentoo with
```
TeXstudio 3.00.00 (git 3.0.0alpha6-1-g80b1f228)
Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
```
