### ISSUE TITLE
Bug/Highlight of the cursor position

### ISSUE THREAD

**Issue by alsahahari** [texstudio-org/texstudio#106]
### Environment
- TeXstudio:  TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
- Qt:  Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS:  Windows 7
- TeX distribution:  MikTex 2.9

### Expected behavior
Highlighting the paragraph of the current cursor position in the pdf viewer if there is a figure or an algorithm part of the section. Also by holding the Ctrl key and clicking on the caption of a figure with [t] will highlight a large part of the page including the header.

### Actual behavior
The entire page of the current cursor position is highlighted instead of the actual pargaph.

**Comment by sunderme** [comment]
no feedback

**Comment by qzfx** [comment]
This does not seem to be the usual imprecision of synctex.
I have the same problem, using 2.12.8 on Win7 and with TexLive 2017.
The problem appears on any .tex I have worked on since installing 2.12.8. (Example attached)
More precisely, if I click on the source code, in the PDF a much too large yellow box is highlighted, and the lower boundary is actually somewhat correct, the upper is usually outside of the page, and the left and right are at the begin and end of the text block.

It works fine with 2.12.6. (I have downgraded again)

[document.tex.txt](https://github.com/texstudio-org/texstudio/files/1920781/document.tex.txt)

**Comment by alsahahari** [comment]
Thank you @qzfx 
I did the same as you (downgraded to 2.12.6) as it was more accurate in this regard. I rely on this feature a lot especially while revising papers. It is a great feature and I wish the developer will fix it soon

**Comment by qzfx** [comment]
The bug is still present in 2.12.10

**Comment by qzfx** [comment]
Seems to be fixed in 2.12.14
* **Windows 10**
* TeXstudio 2.12.14 (git 2.12.14)
* Nutze Qt-Version 5.8.0, kompiliert mit Qt 5.8.0
* MiKTeX-pdfTeX 2.9.6362 (1.40.18) (MiKTeX 2.9.6400 64-bit)

**Comment by timhoffm** [comment]
Thanks for the feedback.
