### ISSUE TITLE
Question:  the XDG external viewer for PDF no longer launches

### ISSUE THREAD

**Issue by mkstreet** [texstudio-org/texstudio#1074]
### Environment
TeXstudio: 2.12.6 (hg 6631:16db084dae24)
Qt: Version 5.9.5, compiled with Qt 5.9.3 R
OS: Ubuntu 18.04
TeX distribution: texlive 2019

### Expected behavior
The system PDF viewer will launch.

### Actual behavior
When I press the button for the XDG external PDF viewer, it no longer launches.
It hasn't worked for some time.

When I press the button, TexStudio reports:
***
   Process started: xdg-open "myfilename".pdf
   Process exited normally
***
but nothing happens after that and no PDF viewer is launched.

**Comment by MeanSquaredError** [comment]
If you open a shell prompt, cd into the directory where `myfilename.tex` is located and then run
`xdg-open "myfilename".pdf` 
Does it open the PDF file?

**Comment by mkstreet** [comment]
> If you open a shell prompt, cd into the directory where `myfilename.tex` is located and then run
> `xdg-open "myfilename".pdf`
> Does it open the PDF file?

Yes, it does.  Foxit Reader startups up and opens myfilename.pdf.
That seems to work fine.

In TexStudio, when I do a "Check Installtion" from the menu, I get this as the system report. Perhaps there is something in here that is wrong, but I don't know what:

************
Process started: printenv

CLUTTER_IM_MODULE=xim
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
DESKTOP_SESSION=ubuntu
DISPLAY=:0
GDMSESSION=ubuntu
GDM_LANG=en_US
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/texstudio.desktop
GIO_LAUNCHED_DESKTOP_FILE_PID=3745
GJS_DEBUG_OUTPUT=stderr
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_SHELL_SESSION_MODE=ubuntu
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK2_MODULES=overlay-scrollbar
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
HOME=/home/dell
IM_CONFIG_PHASE=2
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LOGNAME=dell
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
PAPERSIZE=letter
PATH=/home/dell/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/texlive/2019/bin/x86_64-linux
PWD=/home/dell
QT4_IM_MODULE=xim
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
SESSION_MANAGER=local/dell-Inspiron-1545:@/tmp/.ICE-unix/2888,unix/dell-Inspiron-1545:/tmp/.ICE-unix/2888
SHELL=/bin/bash
SHLVL=0
SSH_AGENT_PID=3023
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TEXTDOMAIN=im-config
TEXTDOMAINDIR=/usr/share/locale/
USER=dell
XAUTHORITY=/home/dell/.Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/dell
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_ID=c2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=7
XMODIFIERS=@im=ibus

Process exited normally


************

**Comment by MeanSquaredError** [comment]
Most likely Foxit Reader is specified as a program that handles the PDF mimetype but the Foxit reader is not accessible to TeXstudio (i.e. it is not in the PATH variable as seen by TeXstudio).
Can you please try the following:
1. Run `xdg-mime query filetype /path/to/myfilename.pdf` , where `/path/to/myfilename.pdf` is the actual path to your .pdf file.
2. Run `xdg-mime query default pdf_mimetype`, where `pdf_mimetype` is the mimetype returned by step 1 (most likely `application/pdf`).
3. Locate where on your filesystem is the filename returned by step 2. On Fedora 31 it is in `/usr/share/applications/`, but on your linux distro it may differ.
4. Run `grep '^Exec=' /path/to/mimetype.desktop | cut -f2- -d'='` , where `/path/to/mimetype.desktop` is the location of the `.desktop` file from step 3.

Then the check if the executable file returned by step 4 is anywhere in the PATH of TeXstudio (in your case it is 
`PATH=/home/dell/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/texlive/2019/bin/x86_64-linux`

If the Foxit reader is not in that path, then you can either change the path of the TXS executable so that it will point to Foxit reader or you can edit the settings of TeXstudio and specify the path to the Foxit reader directly in the setting for the `External PDF viewer`. You can configure it from
`Options / Configure TeXstudio... / Commands / External PDF Viewer`.

By default on Linux it is something like:
`xdg-open %.pdf > /dev/null`
You can try changing it to something like:
`/path/to/foxit/reader/executable %.pdf`

**Comment by mkstreet** [comment]
> Most likely Foxit Reader is specified as a program that handles the PDF mimetype but the Foxit reader is not accessible to TeXstudio (i.e. it is not in the PATH variable as seen by TeXstudio).
> Can you please try the following:
> 
> 1. Run `xdg-mime query filetype /path/to/myfilename.pdf` , where `/path/to/myfilename.pdf` is the actual path to your .pdf file.

    application/pdf

> 2. Run `xdg-mime query default pdf_mimetype`, where `pdf_mimetype` is the mimetype returned by step 1 (most likely `application/pdf`).

   FoxitReader.desktop


> 3. Locate where on your filesystem is the filename returned by step 2. On Fedora 31 it is in `/usr/share/applications/`, but on your linux distro it may differ.

  whereis FoxitReader
  FoxitReader: /home/dell/bin/FoxitReader

> 4. Run `grep '^Exec=' /path/to/mimetype.desktop | cut -f2- -d'='` , where `/path/to/mimetype.desktop` is the location of the `.desktop` file from step 3.
> 
  If I grep for /home/dell/bin/FoxitReader.desktop, it says no such file.
  And if I grep for /home/dell/bin/FoxitReader , then no results are returned.

   grep '^Exec=' /home/dell/bin/FoxitReader | cut -f2- -d'='
   {no results returned}

**Comment by MeanSquaredError** [comment]
In your case `whereis FoxitReader` found the executable file itself and not the `FoxitReader.desktop` (as specified in step 3). So no wonder that the grep from step 4 did not find the executable.

I don't if Ubuntu maintains a locate database so maybe `locate FoxitReader.desktop` will not work, but you can try 
`find / -name 'okularApplication_pdf.desktop'`
It should work although depending on your filesystem size it might be slower.

However assuming that Foxit Reader is in `/home/dell/bin/FoxitReader`, then you can try setting
`Options / Configure TeXstudio... / Commands / External PDF Viewer` 
to `/home/dell/bin/FoxitReader %.pdf` and see if that will work.

**Comment by mkstreet** [comment]
> In your case `whereis FoxitReader` found the executable file itself and not the `FoxitReader.desktop` (as specified in step 3). So no wonder that the grep from step 4 did not find the executable.
> 
> I don't if Ubuntu maintains a locate database so maybe `locate FoxitReader.desktop` will not work, but you can try
> `find / -name 'okularApplication_pdf.desktop'`
> It should work although depending on your filesystem size it might be slower.
> 
> However assuming that Foxit Reader is in `/home/dell/bin/FoxitReader`, then you can try setting
> `Options / Configure TeXstudio... / Commands / External PDF Viewer`
> to `/home/dell/bin/FoxitReader %.pdf` and see if that will work.

locate FoxitReader.desktop
/home/dell/.local/share/applications/FoxitReader.desktop
/home/dell/opt/foxitsoftware/foxitreader/FoxitReader.desktop

**Comment by MeanSquaredError** [comment]
I would assume that `/home/dell/.local/share/applications/FoxitReader.desktop` is the correct location so you can try running grep on it (step 4) and see where is the actual binary that handles the .pdf files.

**Comment by mkstreet** [comment]
I tried grep on both and they both returned the same:

grep '^Exec=' /home/dell/.local/share/applications/FoxitReader.desktop | cut -f2- -d'=' 
/home/dell/opt/foxitsoftware/foxitreader/FoxitReader.sh %F


grep '^Exec=' /home/dell/opt/foxitsoftware/foxitreader/FoxitReader.desktop | cut -f2- -d'=' 
/home/dell/opt/foxitsoftware/foxitreader/FoxitReader.sh %F

**Comment by MeanSquaredError** [comment]
OK, then I guess you can just set
`Options / Configure TeXstudio... / Commands / External PDF Viewer`
to 
`/home/dell/opt/foxitsoftware/foxitreader/FoxitReader.sh %.pdf`
and see if that fixes the problem with the external PDF viewer.

**Comment by mkstreet** [comment]
Yes, that works. FoxitReader launches now and opens the pdf file.

Is the situation caused by the FoxitReader being in the wrong place so XDG doesn't find it?

**Comment by MeanSquaredError** [comment]
Originally I thought that your .desktop file specifies a relative pathname for FoxitReader binary and the FoxitReader binary is not in the PATH of TeXstudio. However given that the .desktop file uses an absolute pathname, I guess the problem is somewhere else.

`xdg-open` is a shell script which essentially runs the a certain application (based on the desktop environment of the user) and that application in turn looks up the .desktop file and extracts the binary that opens the .pdf file.

On my machine I use KDE so `xdg-open` effectively runs  `kde-open5 /path/to/myfile.pdf` which actually does the .dekstop lookup and starts the PDF viewer.

From your debug logs it seems that you are using GNOME so I am not sure which application it actually runs.

You can try running:
`bash -x xdg-open /path/to/myfile.pdf`
to see which program actually opens .pdf on GNOME.

Why that program actually fails under TeXstudio is another question. My guess is that it does not know that `/home/dell/.local/share/applications/` is a location where .desktop files should be searched for, but I might be wrong.

If you want to use `xdg-open` instead of directly calling FoxitReader, then you can try adding explicitly `/home/dell/.local/share/applications/` to `XDG_DATA_DIRS` before running TeXstudio and see if that will make a difference.

**Comment by mkstreet** [comment]
When I do this,
   bash -x xdg-open /path/to/myfile.pdf

It starts FoxitReader.

I am not sure where to properly modify the environment variable XDG_DATA_DIRS

$ echo $XDG_DATA_DIRS
/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop

**Comment by MeanSquaredError** [comment]
What I meant is that running 
`bash -x xdg-open /path/to/myfile.pdf`
will display all the executed script commands on the standard output, each command prefixed by `+`, e.g. in my case it looks like:
```
...
+ case "${KDE_SESSION_VERSION}" in
+ kde-open5 /root/archive/myfile.pdf
+ '[' 0 -eq 0 ']'
+ exit_success
+ '[' 0 -gt 0 ']'
+ exit 0
```
In my case it is using `kde-open5` to open `myfile.pdf`
In your case on GNOME it will use some other program.

Whichever program you are using it has problems opening the .pdf file, most likely it is missing some environment variable or some environment variable lacks a path when run under TeXstudio.

From what you showed in your previous message:
```
$ echo $XDG_DATA_DIRS
/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
```
The value of `XDG_DATA_DIRS` in TeXstudio and from the command line are identical, so  it does not seem to be a problem with `XDG_DATA_DIRS`.

Whichever desktop-dependent program is being run by `xdg-open` it behaves differently when run from TeXstudio and when run from the command prompt.

I would recommend just running `FoxitReader %.pdf` directly since it seems to work most reliably in your case.

**Comment by mkstreet** [comment]
Ok, I can run it directly.

For completeness, the bash output shows:
....
+ which gnome-default-applications-properties
+ DE=gnome3
+ '[' -f /run/user/1000/flatpak-info ']'
+ '[' xgnome3 = x ']'
+ DEBUG 2 'Selected DE gnome3'
+ '[' -z '' ']'
+ return 0
+ case "${BROWSER}" in
+ case "$DE" in
+ open_gnome3 cb.pdf
+ gio help open
+ gio open cb.pdf
+ '[' 0 -eq 0 ']'
+ exit_success
+ '[' 0 -gt 0 ']'
+ exit 0

**Comment by MeanSquaredError** [comment]
It uses `gio open cb.pdf` to open the PDF file `cb.pdf`. So you can configure the external PDF viewer as `gio open %.pdf` and then try to view the PDF in the external viewer. If it fails to start FoxitReader then most likely there is something misconfigured in the shared mime database or maybe TXS is not started with the proper environment variables.

**Comment by mkstreet** [comment]
gio open %.pdf   does not work.

I changed the external viewer to just:   FoxitReader %.pdf

And that works.  It's good enough.  Thanks much!
