### ISSUE TITLE
Wrong word breaking for long words

### ISSUE THREAD

**Issue by JimVardakis0** [texstudio-org/texstudio#1106]
### Environment
- TeXstudio: git 2.12.22
- Qt: Qt version 5.12.1
- OS: Windows 10 Home
- TeX distribution: MiKTeX-pdfTeX 2.9.6870 (1.40.19) (MiKTeX 2.9.6930 64-bit)

### Expected behaviour
When typed text exceeds the length of a line, TeXstudio adds a dash to the middle of the word and continues on the next line. Everything is expecting to fit inside a specified length, in particular nothing should be longer than `\textwidth` or otherwise a warning of an overfull `\hbox` will be created. TeXstudio will try to adjust the spacing while doing so.

### Actual behaviour
However, when there are many consecutive lengthy words, TeXstudio fails to break them appropriately, which then creates a line considerably longer than what it should be.
![New Bitmap Image](https://user-images.githubusercontent.com/65783429/82697096-4c455280-9c36-11ea-96c5-f6ef282544a9.jpeg)
The line should break where the arrows pinpoint, but it doesn't.

### How to reproduce
For example, this will create an overfull `\hbox`:
`\documentclass{article}`
`\begin{document}`
`abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvuwxyz`
`\end{document}`

**Comment by muzimuzhi** [comment]
Hyphenation is the work of TeX engines, not the work of editors like TeXstudio. Hence this issue is kind of off-topic.

In short, there is a hyphenation dictionary distributed with TeX and extended by some packages. For arbitrary artificial and long word, it is most likely that TeX don't know it hence cannot do auto hyphenation.
 - In-place workaround: insert `\-` in the work to mark possible hyphen positions. E.g., `abc\-def\-ghi`
 - In-preamble workaround: add `\hyphenation{abc\-def\-ghi another\-long-\-long\-word}` to your preamble.

You can search for keywords like `\-`, `\hyphenation` to get more explanations.

**Comment by JimVardakis0** [comment]
This is indeed interesting! Thank you!
However, I don't understand; If this not an issue of TeXstudio, then where should this be reported? And is this supposed to be reported at all?

**Comment by muzimuzhi** [comment]
> @muzimuzhi This is indeed interesting! Thank you!
> However, I don't understand; If this not an issue of TeXstudio, then where should this be reported? And is this supposed to be reported at all?

With the knowledge from https://github.com/texstudio-org/texstudio/issues/1106#issuecomment-632985908, this is not supposed to be reported (for automatic solution) because TeX acts as expected and one cannot expect that TeX can do auto-hyphen for arbitrary (artificial and long) word.

I think there are enough discussions about this on tex.stackexchange.com that you can take a look at. See also related subsections under [9 Line breaking](https://latexref.xyz/Line-breaking.html#Line-breaking).

**Comment by MeanSquaredError** [comment]
@JimVardakis0 

If you insist on reporting the issue to the developers, then I guess you can try reporting it to the maintainers of the MiKTeX distribution since they are the only ones who can change this behavior.

However I suspect that they will not be willing to make any changes and will instead recommend something like what muzimuzhi.

Either add hints to tell pdftex how to split those words (they are not true English words so pdftex does not know how to split them), or adjust the pdftex macros in the preamble and tell it to prefer underfull hboxes to overfull ones (I am not a TeX expert so I am not exactly sure how to do that in your case but reading the links provided by muzimuzhi will probably help). In that case it will split the text along whitespace and you will probably get underfull hboxes now and then if you have too many long unsplittable words, but it is arguably better than overfull hboxes.

**Comment by muzimuzhi** [comment]
@JimVardakis0 
The command `\seqsplit` from package `seqsplit` may help you. It is designed to
> typeset long sentences of letters, which should not have spaces between them (like letters in words), but could be split between lines at any point, and without a hyphenation character.

And the hyphenation "character" is configurable. See a usage here: https://tex.stackexchange.com/a/228063.

**Comment by JimVardakis0** [comment]
@muzimuzhi 
Thanks this is good to know.
