### ISSUE TITLE
Percent sign within href is interpreted as comment

### ISSUE THREAD

**Issue by sba1** [texstudio-org/texstudio#1108]
When I write code like that
```
\href{https://de.wikipedia.org/wiki/Multiplizit%C3%A4t_(UML)}
```
the TeXstudio syntax highlighter interprets everything beyond the percent sign as comment, although this code is interpreted correctly by LaTeX and produced the expected output, namely the proper URL and following text within the same line.

### Environment
- TeXstudio: 2.12.22 (Build: 2.12.22+debian-1)
- Qt: 5.12.5
- OS: Debian Bullseye
- TeX distribution: TexLive 2020.20200417

### Expected behavior

I would expect that the syntax highlighther doesn't interpret the ```%``` as the begin of a comment in this special case.

### Actual behavior

TeXstudio interprets everything beyond the first  ```%``` as comment.

**Comment by muzimuzhi** [comment]
Similar to #1095. 

It seems that texstudio should highlight `Token::url` as `Token::verbatimStart` or `Token::verbatim`.

**Comment by KCaglarCoskun** [comment]
This also causes some TOC entries to vanish.

### Environment

- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10

### Expected behavior
![image](https://user-images.githubusercontent.com/19360095/122082674-7c8efe80-ce00-11eb-9fcf-cf280341a895.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/19360095/122082460-52d5d780-ce00-11eb-9677-baeb952a2763.png)

### Code
```tex
\documentclass[a4paper, 12pt]{article}
\usepackage{hyperref}

\begin{document}

\section{Popularity}
The ngram of hybrid systems with respect to other related fields is: (Figure from \href{https://books.google.com/ngrams/graph?content=Albert&direct_url=t1\%3B\%2CAlbert%3B%2Cc0}{link})

\section{Hybrid Systems}

\end{document}
```
