### ISSUE TITLE
logo i=√(-1) is wrong (i=±√(-1) would be correct)

### ISSUE THREAD

**Issue by JoKalliauer** [texstudio-org/texstudio#1117]
### Environment
![https://www.texstudio.org/images/texstudio128x128.png](https://www.texstudio.org/images/texstudio128x128.png)
https://www.texstudio.org/images/texstudio128x128.png on https://www.texstudio.org/ has a mathematical mistake

### Expected behavior
i=±√(-1)
or more correct:
i²=-1 (see https://en.wikipedia.org/wiki/Imaginary_number )

### Actual behavior
i=√(-1)

### How to reproduce
![https://www.mathe-online.at/tests/komplex/widerspruch.jpg](https://www.mathe-online.at/tests/komplex/widerspruch.jpg)
source: https://www.mathe-online.at/tests/komplex/widerspruch.html
license: assuming all right reserved (maybe fair-use or maybe below the treshold of originality)

**Comment by sunderme** [comment]
if you want to edit the logo ... go ahead

**Comment by tmelorc** [comment]
You can make use of _Principal square root of complex numbers_.

**Comment by JoKalliauer** [comment]
@sunderme Is there somewhere a vector-version of the logo (svg,ai,eps,...) ?

**Comment by tmelorc** [comment]
Usually the symbol `\sqrt{z}` is for the principal square root. So, in this case, the logo is right. I wouldn't change it.

![Seleção_256](https://user-images.githubusercontent.com/15181573/83420795-81536100-a3fd-11ea-822c-71c5329f6eb2.png)

**Comment by JoKalliauer** [comment]
I'm not talking about calulating the square root. (That would be differenet)
a=\sqrt(4) leads to a=+2
but a²=4 leads to a=+2 or a=-2
(Maybe I missunderstood you.)

i is defined as i²=-1 see e.g. https://en.wikipedia.org/wiki/Imaginary_number
There exist two solutions to this one is i=+\sqrt{-1} and the other one is i=-\sqrt{-1}
see e.g. https://math.stackexchange.com/a/13808/572127 or https://en.wikipedia.org/wiki/Branch_point

**Comment by tmelorc** [comment]
Hello @JoKalliauer. I understanding your arguments.
I only observed that is common in complex analysis to use the symbol `\sqrt` for one of the two square roots, namely, the so called principal one. Since the principal square root of the complex number `-1` is `i` (not `-i`) it is not good to write `\pm` with that symbol.

What do you think?
Regards.

**Comment by JoKalliauer** [comment]
a=\sqrt(4) leads to a=+2
a²=4 leads to a=+2 or a=-2

You are talking about the first line, I'm talking about the second.
`i` is defined as `i²=-1` and imho not `i=\sqrt{-1}`, at least according to [Wikipedia](https://en.wikipedia.org/wiki/Imaginary_number) refering to [Uno Ingard, K. (1988). "Chapter 2". Fundamentals of Waves and Oscillations. Cambridge University Press. p. 38. ISBN 0-521-33957-X.](https://books.google.at/books?id=SGVfGIewvxkC&pg=PA38&redir_esc=y)

**Comment by septatrix** [comment]
Does there exist an unrasterized version somewhere or would one need to edit the original png file?

**Comment by sunderme** [comment]
utilities/texstudio.svg but it is incomplete ...

**Comment by clecap** [comment]
Defining a mathematical object merely by a property is known to lead to severe problems unless you make statements on existence and uniqueness. That's why higher mathematics defines $i$ differently, either by field extension mechanisms, via polynomials, as pairs or by vector space constructions. Starting with $i^2=-1$ is known to lead to severe problems.

$\pm$ is a shorthand notation and defines two values, not one. It defies the necessity of distinguishing $+i$ from $-i$. Changing the logo in the suggested way could lead, at best,  to embarrassment.

**Comment by JoKalliauer** [comment]
Even if i is difficult to define i²=-1 is correct. I think it might be best to keep it as it is.
