### ISSUE TITLE
[Feature Request] Project related parameters

### ISSUE THREAD

**Issue by Noranius** [texstudio-org/texstudio#1362]
Documents in a professional manner need meta information for building, for example, you want to use pdfLatex as compiler for project A but project B needs LuaLatex. Furthermore, the name of the outputfile could be specified in such a meta information. By loading a project, the meta information is loaded, as well and sets up all necessary parameters in texStudio. This is very similar to project information in visual studio or eclipse.

**Comment by muzimuzhi** [comment]
> for example, you want to use pdfLatex as compiler for project A but project B needs LuaLatex

This is achievable by using [magic comment](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#TEXCOM) `!TeX program = pdflatex` or `!TeX program = lualatex` at the very beginning of the main tex file.

**Comment by Noranius** [comment]
The example with the build environment was only one. Furthermore you could define

- an output path
- additional parameters for building
- pre and post built commands
- meta information for the final pdf
- ...

**Comment by sunderme** [comment]
meta info for pdf -> hypertex
all the rest -> magic comment , perhaps some inline scripts.
I don't see a need for a more complicated setup
Since txs is cross platform, going through the hassle of getting things to run on different machines is not desirable.
This is especially true for pre/post build commands, additional parameters for building and output path.
