### ISSUE TITLE
The window Configure Texstudio lacks sliders!

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#1391]
### Environment
- TeXstudio:  3.0.2 (git 3.0.2beta1)
- Qt:  5.12.3
- OS: win1064
- TeX distribution: texlive

When I try to change commands, I do not see the ok-button. Therefore, I have not been able to save the changes. Very irritatin
### Expected behavior
I would expect sliders on the right side when not everything is visible - I have a doublelined taskbar at the bottom. Or/and there should be the field in the upper right corner for the switch to fullpage/not fullpage. That would be proper windows behaviour.

### Actual behavior
the OK button is hidden behind the taskbar. Not respecting the taskbar is improper behaviour in windows.

**Comment by muzimuzhi** [comment]
If I didn't misunderstand your question, perhaps you can resize the configuration window?

**Comment by bernhard-kleine** [comment]
Finally, I imagined resizing would help.  I managed to resize and to see the OK button. But it took me quite a while to do so. The need for resizing is not evident and that is my complained: If the ms windows sizing would be respected and the config window would be cropped to the display and slider would be added this whole discussion would be superfluous. When the main texstudio window does very well fit into the display, why the config window could not do this, too?

**Comment by octaeder** [comment]
This issue concerns an old (early 3) beta version, current 4.2.2 shows sliders on win10. Nevertheless sliders wouldn't move the ok buttton. The window musst be moved. If the window is as large that neither border nor ok button is visible, there is still a way moving the window: When the window is active press Alt+Space (opens the window menu, even if you can't see it) then V key (chooses entry  "verschieben"). Now the window can be moved with the cursor keys (sometimes called arrow keys) in any of the four directions. Press Return when the window is well positioned for resizing or pressing ok button.

Since nothing happend in more than 12 months I suggest to close the issue.

**Comment by octaeder** [comment]
#2868 resizes height of config if it is larger than the part above the task bar. So I would say that this is solved since 4.5.1.
