### ISSUE TITLE
Feature request: Ignore-list for word repetition

### ISSUE THREAD

**Issue by DBX12** [texstudio-org/texstudio#1428]
**What**
An ignore-list for the word repetition function.

**Why**
Mainly because there are several words and "classes" of words which just repeat in a common text but are not a bad writing style per se. For example, pronouns or articles. You cannot write the sentence "I knock on the door of the hut" without repeating "the" (and without rearranging the sentence).

I think that would really increase the value of function and Texstudio as whole.

**Comment by benibela** [comment]
Warning of duplicate "the" was the usual example where it should warn

E.g.: I knock on the the door of the hut

Perhaps the default setting  of the "words between repetition" number is too high

**Comment by DBX12** [comment]
So maybe the example in English was bad. Unfortunately, I cannot translate my example meaningfully and hope there is a German-speaking contributor who can do it better:

> Diese Mängel sollen später bei der Besichtigung der Wohneinheiten genauer begutachtet werden.

The alert is shown on the second "der", unfortunately my grammar lessons are too far in the past to describe what kind of word "der" is in this context :see_no_evil:

**Comment by benibela** [comment]
But it is the same in German. It would not be good if there were three der

>    Diese Mängel sollen später bei der der Besichtigung der Wohneinheiten genauer begutachtet werden.

**Comment by DBX12** [comment]
Hmm, right. If the word "der" is ignore-listed such repetitions would not get caught. Maybe fiddling with the repetition distance settings is the better solution.
Thank you for pointing that out :+1:  I'll close that ticket then.

**Comment by jadaml** [comment]
I actually have a better, examples for why would you need this, though may be easy to be dismissed as not relevant for the target use-case:
I am currently writing my CV in TeXstudio. (The reason I chose LaTeX, so I can program it.) In it, I list both Visual Studio 2022 and Visual Studio Code, next to each other. I also, sadly, cannot simplify this, by for example saying "Visual Studio 2022, ~ Code", or anything else to this effect, as it is needed to be searchable, and a search key of "Visual Studio Code" would never find "~ Code" as a result. Another example could be "Test-driven Development (TDD), Behavior-driven Development (DDD)", where I couldn't simply it to be "Test and behavior-driven Development" (which would be a very reasonable change) for the same reason. (And it is possible, that the recruiters tools are searching case-sensitive too.)

Furthermore, I'm also surprised that this feature request was dismissed like this, since most mathematical definitions, thesis and operations only have a single name and there is no opportunity in mathematics to introduce alternative naming to them nor to always just introduce additional text between repetitions (as it could potentially devalue the message of a text), and so it is unavoidable to never have word repetitions. Especially, since the entire TeX system was originally developed to typeset beautiful mathematical articles and books. Although, sadly, my profession is adjacent to mathematics, and have not been involved enough in it to say anything for certain, I would like to ask you to reconsider, at least.
