### ISSUE TITLE
Icon not included in Windows

### ISSUE THREAD

**Issue by jrmoserbaltimore** [texstudio-org/texstudio#1432]
`C:\Program Files\TexStudio\logo.ico` doesn't exist after a clean install of 3.0.4.  This is associated with the program and so the file types associated with it.  As a result, a generic icon is used for .tex files, rather than the TeXStudio logo.

**Comment by OgreTransporter** [comment]
Actually, you don't need to install an icon. Windows can use the icon from the EXE. This is then an error in the registration of the file extensions.

**Comment by Stimmenhotel** [comment]
I had the same error and changed it using FileTypesMan v1.95.
If I am not mistaken, it was because of the changed path of txs. Instead of Programs (86x) it uses the folder without braces (the 64x one) but the icon is still searched at (86x).

I thought this was due to my many switches between versions at that time.

**Comment by zxl19** [comment]
Hi @sunderme ! I also encountered this problem using version 3.1.2 on Windows. The icon of `.tex` files cannot be correctly displayed.
