### ISSUE TITLE
100% CPU usage with inline checking using languagetool 

### ISSUE THREAD

**Issue by HubYin** [texstudio-org/texstudio#1453]
### Environment
- TeXstudio: 3.0.4 (git 3.0.4)
- Qt: Version 5.12.3, compiled with Qt 5.12.3 R
- OS: Windows 7 with 2 cores (4 threads)
- TeX distribution: miktex 2.9
- TeXstudio installed from: binary
- Java: version "1.8.0_281"
- LanguageTool: version 5.2

### Description

100% CPU usage always occurs for 3~4 seconds when editing text with inline language checking by LanguageTool.

Configure as follows:

Editor:
![image](https://user-images.githubusercontent.com/16040285/105785570-4f67be00-5fcf-11eb-9daa-1080c47ee7de.png)

Language Checking:
![image](https://user-images.githubusercontent.com/16040285/105785529-39f29400-5fcf-11eb-81b2-6b15aad5653b.png)

**Comment by sunderme** [comment]
do you see which process actually causes the cpu load ? (task manager)

**Comment by HubYin** [comment]
> do you see which process actually causes the cpu load ? (task manager)

It is the process of java.exe.

**Comment by sunderme** [comment]
then language tool is causong the load because it is checking the text. Nothing we can do ...
(be aware that language tool is grammar checker and hence it is given the complete sentence to check, even if you only change one letter ...)

**Comment by HubYin** [comment]
> then language tool is causing the load because it is checking the text. Nothing we can do ...
> (be aware that language tool is grammar checker and hence it is given the complete sentence to check, even if you only change one letter ...)

Could you give me some advice for reducing the load, like limiting the number of threads? How to do that?

**Comment by Rawi01** [comment]
I have the same issue and hope that I can provide some more details to get this one resolved.

Typing a single character triggers a request which works perfectly fine. Completing this request takes ~500ms. If I start writing normally TexStudio sends a request for almost every character. This quickly creates a huge queue for LanguageTool to process which takes even longer because all have to be done at the same time. After finishing a sentence I usually have to wait until the last request was processed.

I checked the code and there already seems to be some check to prevent to many request by delaying them but either this does not work or the time is to low for someone like me and HubYZ.

TeXstudio 4.2.3 / LanguageServer 5.9
