### ISSUE TITLE
Improve Release Management 

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#1478]
### Environment
- TeXstudio: 3.1.0
I would love to get a better release management. For me as a downstream packager it's quite tiresome to have releases in such a short frequency. I understand that if there's a bug in a release, it should be fixed, but for the last couple of release cycles it was a bit too much in my opinion.

**Comment by sunderme** [comment]
as too few people test beta or rc, there is nothing we can do.

**Comment by hannes101** [comment]
But couldn't the beta and the rcs wait a little longer, currently the frequency is really high and I think it would make sense to give people a bit more time to test these rcs and betas.

**Comment by sunderme** [comment]
I guess, you do not have an automated set-up to do a release ?
"fast" and "slow" here is really subjective. When commits have piled up which probably are interesting for users, I will do a release.
Here it was because of the transition to 3.1.0 where functionality is extended. The bug which affects users is annoying and if I get the same bug reported repeatedly, I will act.

**Comment by hannes101** [comment]
No, it's not automated and I still do not get the reason, why there was the need to go to 3.0.5 and then less than 3 days later to 3.1.0 and include new functionality. 
For me it also does not give too good an impression overall, but do as you please.

**Comment by sunderme** [comment]
maybe as a heads up:
3.1.1 will be published not to far in the future (4 weeks ?) if global TOC generates some interest.
Otherwise, probably in May, 4.0.0 will be published with support for Qt6.
Target release cycle is about 3 months, but that strongly depends on development activity.
