### ISSUE TITLE
Installer: Does not remember last install location

### ISSUE THREAD

**Issue by foreachthing** [texstudio-org/texstudio#1501]
### Environment
- TeXstudio: >3
- OS: Win 10 x64

### Expected behavior
The installer installs by default to the last install location.

### Actual behavior
It always wants to install in "c:\program files\texstudio". This is not where I have txs installed.

### How to reproduce
Start installer, install txs _not_ in default path.
Install update.

**Comment by sunderme** [comment]
currently the installer does not read anything on the system. If someone wants to change that ...

**Comment by qqobb** [comment]
@foreachthing: Is your issue the same as #1475? If so, I guess there's not much you can do about it.

@sunderme wrote in https://github.com/texstudio-org/texstudio/issues/1384#issuecomment-743759017:
> all builds will be 64 bit.

So, it seems that texstudio went from 32 bit to 64 bit. Quoting [wikipedia](https://en.wikipedia.org/wiki/Program_Files):
> The *Program Files* folder serves as the default installation target for 64-bit programs, while the *Program Files (x86)* folder is the default installation target for 32-bit programs that need WoW64 emulation layer.

It's not possible to manually choose between *Program Files* and *Program Files (x86)*, see [here](https://answers.microsoft.com/en-us/windows/forum/windows_10-files/windows-10-installing-to-program-files-folder/8fc41fe2-d9e4-4fb9-844b-5f5586fc5fe1).

I think the change from 32 bit to 64 bit should be announced somewhere in the update notifications in order to avoid confusion.

**Comment by foreachthing** [comment]
@qqobb, no, it's not that #1475.
It's that I've installed txs _not_ on the c-drive. So, every time I install an update, it asks me to install txs on the c-drive. This is somewhat annoying 🙄

**Comment by qqobb** [comment]
> It's that I've installed txs not on the c-drive.

Ok, so this is indeed another issue.

> currently the installer does not read anything on the system. If someone wants to change that ...

Maybe one should use ["App Paths" registry keys](https://docs.microsoft.com/en-us/windows/win32/shell/app-registration) for this, e.g.:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\
```

But this is beyond my knowledge, so I won't be able to help. Perhaps it's useful to have a look at RStudio, see [here](https://github.com/rstudio/rstudio/search?q=%22App+Paths%22).

**Comment by sunderme** [comment]
fixed for nsis installer
