### ISSUE TITLE
BUG: Ctrl+Shift+I "\item" replaces selected text instead of surrounding like other commands

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1510]
### Environment
- TeXstudio: 3.1

### Expected behavior
Behave like `Ctrl+b` (bold)

### Actual behavior
If you select some text and hit ctrl+B, the selection is surrounded withthe command into `\textbf{TEXT}`.
but If you select some text and hit ctrl+shift+i, the selection is just replaced with `\item`.
 
### Solution
Edit the definition of the macro in the Options/Configure/Menus/Latex/List Env/\Item
and replace
```
var ins="\\item"
```
with 
```
var ins="\\item[%|]"
```

**Comment by JonathanLevine657** [comment]
On second that. I guess the right thing to do depends on the environment.

**Comment by JonathanLevine657** [comment]
When there is an active selection, it would be useful if the `\item` menu command trasnformed into `\item[SELECTION]`:

```
%SCRIPT

var ln=cursor.lineNumber();
var env=editor.document().getLastEnvName(ln);
var ins="\\item"; 
if(cursor.hasSelection()) { # <- added this
    ins="\\item[%|]";
}
if(env=="description"){
    ins=ins+"[%<label%>] %<description%>"
} else {
    ins=ins+" "
}
editorView.insertSnippet(ins)
```

**Comment by sunderme** [comment]
editors usually overwrite selected text.
If txs tries to guess that a different behavior is more appropriate, it better does no generate a cost by adding extra steps for the users, if txs is wrong. cutBuffer is a good example. It places selected text into the first placeholder. If the user does not want it, it can overwritten like it would be done for any placeholder, no extra cost added.
Here, the inserted code is changed from `\item` to `\item[]`. If the guess is wrong, extra work is added for the user. Since there is no good indication that the second option is really the likely option (unlike item in description), I stick with staying at the default insert,i.e. "\item"

**Comment by JonathanLevine657** [comment]
> editors usually overwrite selected text.

Editors meant for programming often don't. TXS in particular very often doesn't, and that's usually very useful.

> Here, the inserted code is changed from \item to \item[]. If the guess is wrong, extra work is > added for the user. 

Not true. The code is only changed if the user invokes the macro with an active selection. That's how practically all applicable macros in TXS work - when invoked with an active selection, they wrap the selection contents. That's how text styles, environments,  boxes, and   practically everything works in TXS.

So, *Not* doing this is what creates extra work for the user, because it is inconsistent with how TXS generally behaves. The user can easily activate the bare `\item` either by not marking a selection in the first place (less work overall), or deleting the selection content before invoking the command. Just like they can with all the other macros.

I appreciate your attention to details very much, it's this kind of usability nuance that makes an editor really enjoyable to use. But I completely disagree with your analysis here.
