### ISSUE TITLE
Have TexStudio not select .bmp as default image format when pasting in graphics

### ISSUE THREAD

**Issue by bogger33** [texstudio-org/texstudio#1521]
### Environment
- TeXstudio: TeXstudio 2.12.14 (Build: 2.12.14+debian-1)
- Qt: 5.11.3, compiled with Qt 5.11.2 R
- OS: LMDE
- TeX distribution: pdflatex (the default)
- 
### Expected behavior
I paste in image data, it picks .png or .jpg or something as the file extension

### Actual behavior
I like to paste in image data straight from kolourpaint, it's very convenient, however, by default TeXstudio will select .bmp as the file extension (i think maybe because it's the first in the list of valid file extensions) - and saving it as a bmp doesn't actually work, it results in an error of it not finding the file, since the extension won't be specified in the generated code, and latex doesn't appear to actually check for bmp files when it's not. So I have to manually change the extension to png every single time

on a less important note, it would also be convenient if it didn't generate the \caption{} bit, if no caption was entered

### How to reproduce
open up graphics program of your choice (i use kolourpaint), copy a selection, paste into TeXstudio

**Comment by JonathanLevine657** [comment]
This is handled here
https://github.com/texstudio-org/texstudio/blob/ee4e4f6fadeeaac3f75346fa588d8ceb0f32a37c/src/texstudio.cpp#L3469-L3486
which tries to use a png extension by default.

This calls `FileDialog::getSaveFileName`:
https://github.com/texstudio-org/texstudio/blob/d80b93ac0dbec3598edfcf63211b6d20e8a3f72c/src/filedialog.cpp#L18-L22

Which in turn uses the QT static method `QFileDialog::getSaveFileName`. This method doesn't behave as desired here if the `dir` argument points at a non-existent file. 

A solution is given by ChrisW67 [here](https://www.qtcentre.org/threads/49434-QFileDialog-set-default-name?highlight=QFileDialog). Instead of using a static method, you need to create a `QFileDialog` object and use the setters it provides, namely `selectFile`:
```
    #include <QtGui>
    #include <QDebug>
     
    int main(int argc, char *argv[])
    {
        QApplication app(argc, argv);
     
        QFileDialog dialog;
        dialog.setOptions(QFileDialog::DontUseNativeDialog);  // with or without this
        dialog.setFileMode(QFileDialog::AnyFile);
        dialog.setAcceptMode(QFileDialog::AcceptSave);
        dialog.setDirectory(".");

        dialog.selectedNameFilter(filters); // Takes QStringList

        dialog.selectFile("somefile.txt");   // magic happens here

        int ret = dialog.exec();
        if (ret == QDialog::Accepted)
            qDebug() << dialog.selectedFiles();
        else
            qDebug() << "Cancelled :(";
     
        return app.exec();
    }
```

**Comment by sunderme** [comment]
I have reduced the offered image formats to just png.
Furthermore caption is only set if caption or short caption is non-empty **or** a label is given.
The label does not make sense without caption to reference in text...
