### ISSUE TITLE
Option 'Disable horizontal scrolling for "Fit to Text Width" not working'

### ISSUE THREAD

**Issue by duartefontes** [texstudio-org/texstudio#1526]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS:MigSur 11.2.2
- TeX distribution: texlive

### Expected behavior
Option 'Disable horizontal scrolling for "Fit to Text Width" should work

### Actual behavior
Option 'Disable horizontal scrolling for "Fit to Text Width" is not working

### How to reproduce
Select the mode "Fit to Text Width" and ascertain verify that horizontal scrolling is allowed, despite the fact that the option  'Disable horizontal scrolling for "Fit to Text Width" is selected

**Comment by sunderme** [comment]
not sure if that was the intention but the option disables horizontal panning (moving with with the hand cursor) only

**Comment by duartefontes** [comment]
> not sure if that was the intention but the option disables horizontal panning (moving with with the hand cursor) only

In my case, it disables nothing. And it did disable in the previous version.
What went wrong?

**Comment by ulriksf** [comment]
Confirming that horizontal scrolling with the touchpad is not being disabled here, either. I'm running Texstudio 3.1.1, Qt 5.15.2 on MacOS 11.2.2. 

I would love to see this feature fixed, or even extended to disable all horizontal scrolling (except with the scroll bar), so that we could zoom in manually and then scroll only vertically with the touchpad.

**Comment by octaeder** [comment]
@duartefontes @ulriksf This worked well for me ever since for Win (and also on laptop with touchpad). Would you please check, if it works for you with latest version 4.2.3. You can find it here https://texstudio.org/#download.

**Comment by BenjaminMoraga** [comment]
I've the same problem. 
TeXstudio: 4.2.3
Qt: 6.3.1
OS: Arch Linux
TeX distribution: texlive

**Comment by octaeder** [comment]
The subject of the issue says _horizontal scrolling is possible_. Others say that this is true when they _use the touchpad_. But what does this mean? In scroll mode the mouse cursor of the pdf viewer is the open hand cursor. After a double click (without releasing the finger from the touchpad) the mouse pointer changes to a closed hand cursor and you can move the page around with the mouse cursor (maybe after zooming in). A quite different method is moving the page by gestures on the touchpad (slide two fingers sideways over the pad). I wasn't aware of this difference in my last comment.

I observed on my Win10 laptop that no horizontal scrolling appears with the closed hand cursor movement for _fit to text width_ as @sunderme said. But horizontal scrolling happens with the touchpad gesture in the same way as it happens when you move the horizontal scrollbar with the mouse cursor (double click and moving cursor). I tested this with following portable versions:

2.12.22 win qt5
3.1.0 win qt5
4.0.0 win qt5
4.0.0 win qt6
4.2.2 win qt6

So it's likely that this difference in behaviour between mouse pointer and touchpad gesture existed most of the time and is not new (or is it OS specific?). Maybe after this clarification @duartefontes can clarify what behaviour he observed in which versions.

**Comment by duartefontes** [comment]
Using my macOS 12.4 and TeXStudio 4.3.0 with QT 6.3.1, I agree with @octaeder: in the 'Fit to Text Width' mode, horizontal scrolling is disabled with closed hand cursor movement, but enabled with touchpad gesture. What I really want, though, is the horizontal scrolling to be disabled with touchpad gesture as well (when I choose the option 'Disable horizontal scrolling for "Fit to Text Width"'). I am especially interested in this feature for the simple fact that horizontal scrolling with touchpad gesture *was* disabled in a previous TeXstudio version in macOS (I do not remember which one, though; I believe one of the versions 2)

**Comment by pbpb** [comment]
Any chance of getting a win10 64 zip build for this fix?

**Comment by octaeder** [comment]
build from this fix can be downloaded here (dev version): [https://github.com/texstudio-org/texstudio/actions/runs/5159577640](https://github.com/texstudio-org/texstudio/actions/runs/5159577640)
This will part of the next release 4.6.0 (no release date available)
