### ISSUE TITLE
\chapter{} unrecognized using \documentclass{scrbook}

### ISSUE THREAD

**Issue by samulicron** [texstudio-org/texstudio#2033]
### Environment
- TeXstudio: 4.1.2 (git 4.1.2)
- Qt: 6.2.1
- OS: Win 10 x64
- TeX distribution: Tex Live 2021

### Expected behavior
Recognize \chapter{} as valid command when using documentclass _scrbook_.

### Actual behavior
Does not recognize \chapter{} as a valid command, but does recognize \section{} and \subsection{}.

### How to reproduce
```
\documentclass{scrbook} % book works

\begin{document}
	\chapter{}
\end{document}
```

**Comment by muzimuzhi** [comment]
Duplicated of #2003, which has been fixed in https://github.com/texstudio-org/texstudio/commit/a3db37ffaceec8b64d37adef6f177aba4ae5ec16. To have an earlier trial before next release, you can download a dev release from https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml, e.g, from the artifacts of this [workflow run](https://github.com/texstudio-org/texstudio/actions/runs/1599209568).
