### ISSUE TITLE
Random space inserted after autocompleting \item on macOS

### ISSUE THREAD

**Issue by nik312123** [texstudio-org/texstudio#2069]
### Environment
- TeXstudio: 4.2.0
- Qt: 6.2.2, compiled with Qt 6.2.2 R
- OS: macOS 12.1
- TeX distribution: texlive (as installed by MacTeX)

### Expected behavior
When I autocomplete `\item`, no space should be produced after `\item` upon hitting enter to accept the autocompletion suggestion.

### Actual behavior
When I autocomplete `\item`, a space is produced after `\item` upon hitting enter to accept the autocompletion suggestion.

### How to reproduce
Autocomplete `\item` to get the following:

```latex
\item 
```

(Note the space after the `\item`)

Notes:
- This issue did not occur in TeXstudio 4.1.2 for me, so I believe it was caused by code changes in between the releases of 4.1.2 and 4.2.0.

**Comment by dbitouze** [comment]
>When I autocomplete \item, no space should be produced after \item upon hitting enter to accept the autocompletion suggestion.

I don't see why you don't want any space after `\item`: this command is (mainly) inserted either in `itemize` and `enumerate` lists, or in `description` lists.

- In the first case, it has to be followed by a space before the next token.
- In the second case, it has to be followed by `[` but TeXstudio automatically inserts it since it inserts `\item[label]`.

>This issue did not occur in TeXstudio 4.1.2 for me, so I believe it was caused by code changes in between the releases of 4.1.2 and 4.2.0.

Indeed, see https://github.com/texstudio-org/texstudio/issues/2010.

**Comment by nik312123** [comment]
@dbitouze Ah, I see. Thanks for the clarification.
