### ISSUE TITLE
txs does handle minted $ wrong (green)

### ISSUE THREAD

**Issue by damnms** [texstudio-org/texstudio#2113]
When using \mintinline{bash}{echo $HOME}, texstudio makes all following text green, but it should not.

### Environment
- TeXstudio: texstudio-4.2.1-1.fc35.x86_64
- Qt: 5.15.2, kompiliert mit Qt 5.15.2 R
- OS: Fedora 35
- TeX distribution: XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021)

### Expected behavior
to not have all following text in green, but in black. thats kinda hard to read in txs

### Actual behavior
all following text after $ is green

### How to reproduce
use \mintinline{bash}{echo $HOME} hello world -> hello world will be green

**Comment by damnms** [comment]
i also have the problem when i use:
\mintinline[breaklines]{bash}|PUB=`cat $HOME/.ssh/id_ed25519.pub`| hello world

**Comment by sunderme** [comment]
fixed in git, only supported syntax is ```\mintinline{<lang>}|<code>|```

**Comment by Qrrbrbirlbel** [comment]
> fixed in git, only supported syntax is `\mintinline{<lang>}|<code>|`

Does this mean that TeXstudio's highlighter only supports `|<code>|` because `minted` supports any delimiters *and* `{<code>}` which previously (4.2.1) didn't color the whole text either (but also didn't color `<code>` which I didn't even notice).

TeXstudio 4.2.3 properly colors `\mintinline{<lang>}!<code>!`, too, but not for example `\mintinline{<lang>}3<code>3`

**Comment by sunderme** [comment]
txs supports "symbols" as delimiters like `|` or `!` or similar.
