### ISSUE TITLE
Spell check highlighting seems not to pick up invalid two letter words

### ISSUE THREAD

**Issue by WilliamADon** [texstudio-org/texstudio#2168]
TexStudio is not highlighting two letter mis-spelled words (e.g. si or gh).  I am using en_GB dictionary.

**Comment by sunderme** [comment]
That is correct.

**Comment by WilliamADon** [comment]
OK.  Does that mean it's now acknowledged to be an issue that will in due course be fixed?

**Comment by sunderme** [comment]
it means that the current functionality is intentional and has been that way for more than 10 years.
Though I don't know the exact reason why it is implemented that way.

**Comment by benibela** [comment]
Because so short words are often abbreviations or variable names.

Probably every  two letter combination has some meaning for someone. E.g. "si" is the country code for top-level domain of Slovenia, Spanish for yes, the abbreviation for the sine integral, and something about prochirality. "gh" is the country code for Ghana, a slang for good half, and I often use it for Github

**Comment by sunderme** [comment]
so, I would take it as a "no" on changing.

**Comment by WilliamADon** [comment]
OK.  I understand.  I think it would be better, like Microsoft word for instance, if they were highlighted unless in capitals or added to a personal dictionary, but obviously your call.
