### ISSUE TITLE
Macro read-in failed, Error: Illegal Value

### ISSUE THREAD

**Issue by sayol** [texstudio-org/texstudio#2395]
A dialogue box appears saying that

- Macro read-in failed

- Error: Illegal Value
![Untitled](https://user-images.githubusercontent.com/10920202/172896645-73a8cbab-7e62-4cf3-8334-facc177f5270.png)
How to solve it?

**Comment by sunderme** [comment]
a bit more context ?
You should follow the template to give sufficient information for debugging.

**Comment by sunderme** [comment]
no feedback

**Comment by s8074132** [comment]
Problem:
Got the same error today, when I tried to start texstudio. When closing the popup, the same popped up again. I used `pkill texstudio` to kill the process.

What caused the error:
My textstudio macros were saved under `/home/<username>/.config/texstudio/macro`
All macro files where there, but all files had a size of 0 Bytes, they were empty.

Possible solutions:
1. I had an old backup of my texstudio configuration, so I restored 34 of 35 by replacing the macro files.
2. I deleted the last remaining, empty macro file. (the only solution, if you have no backup to restore)

Texstudio started without the dialog afterwards.

**Comment by s8074132** [comment]
@octaeder 

__System Info:__
- Linux Mint 21 Cinnamon
- TeXstudio 4.2.1 (Build: 4.2.1+ds-1) Nutze Qt-Version 5.15.3, kompiliert mit Qt 5.15.2 R

__Are there any changes done that might cause the error?__
This is the procedure, I did: Woke my PC up from standby, tried to start TexStudio and got the error.

__Is there a way to reproduce the error?__
I know why the error was raised: suddenly empty macro files in the config directory. I just remembered, that I recently had a backup copied to my disk (wrong path) and the disk went full to the last tiny bit. I guess, texstudio tried to save the current session to the disk, but because the disk was full, all session/config file contents (including the marco files) could not be written to the disk ⇒ all files got 0 Bytes as content.

__Probably the json in some of the files is not correct. Look at additional quotes that are not escaped by a backslash.__
The files were empty, so I guess the file contents were passed to the json parser, which threw the error.

Maybe something like this happened to @sayol 

Possible solutions for the dev-Team: 

- Maybe check the disk space, before trying to write any config/session files to avoid corrupted/empty file contents which cannot be read on the next start.
- When a corrupted config/session file is read, throw a more specific error (which config file is corrupted)
- I guess, the message would popup 35x for every macro, which could not been read by the parser. Maybe afterwards I would have got into texstudio anyway. But the first thought was: I cannot close the program except through the process manager (or pkill). Maybe a list of errors is better than throwing every error in a new popup window.

**Comment by octaeder** [comment]
@s8074132 Thanks for your patience. Since under normal conditions everything is ok, I suggest opening an enhancement/feature request.

**Comment by s8074132** [comment]
@octaeder Oh, I've no trouble with this issue, since it can be resolved easily. I just wanted to share my findings with the community, because this thread has not provided any solutions so far since last year. So anyone searching for this error message can find a possible reason and a solution in my messages above.
