### ISSUE TITLE
Cannot easily assign custom shortcut (due to conflict with existing one for other action)

### ISSUE THREAD

**Issue by baloe** [texstudio-org/texstudio#2555]
I wanted to assign Mirror Curser Down and Up with Ctrl-Shift-Down and Ctrl-Shift-Up, respectively.

I did so through Options > Configure ... as I have done many times before.

The problem is that the shortcut still would not mirror my cursor. Instead it seems to still be associated with another action assigned with this shortcut by default. I can't find which one that is so I am unable to unassign that one.

If I remember correctly in previous versions of Texstudio the user was warned about a shortcut already being associated with another action and the other action would then be deassociated automatically.

This is 
```
TeXstudio 4.3.0 (git n/a)
Using Qt Version 6.3.1, compiled with Qt 6.3.1 R 
```
Installed through the official Manjaro Repositories.

**Comment by baloe** [comment]
So after finally finding  
Menus > Idefix > GoTo > Next Error  
I was able to deassign the default association and am able to mirror my cursor down and up as I wanted.

**Comment by sunderme** [comment]
basic key mapping seems not to check for other shortcuts. So, this is an enhancement.

**Comment by octaeder** [comment]
Notes:

1. For all other users/readers it might be of interest that actions "Create cursor mirror down" and "Create cursor mirror up" already have shortcuts as can be seen from following screenshot.
2. The first text line in the mouse over (s. screenshot) is not correct in this case because basic key mapping seems to be special in that it is not possible to change Additional Shortcut. One can only change Current Shortcut.

![grafik](https://user-images.githubusercontent.com/102688820/189654582-0ed6fca4-44c2-4702-8859-ad92edcf8266.png)

**Comment by sunderme** [comment]
this was implemented
