### ISSUE TITLE
wrong completion \\[2cm]

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#26]
when typing
`test\\[`
Texstudio completes to `test\\[\]`, which is wrong. Is there a way to disable this?

![selection_465](https://user-images.githubusercontent.com/298682/35781351-58c5cf30-09e9-11e8-9485-8acce0635a20.png)
![selection_466](https://user-images.githubusercontent.com/298682/35781353-5e390bd0-09e9-11e8-9cd6-42ffa17d2cd4.png)

**Comment by timhoffm** [comment]
I don't think there is. Parentheses are defined via the qnfa file. As far as I understand them, it's not possible to distinguish `\[` from `\\[`.

**Comment by jonasstein** [comment]
can I disable `\[`  completion at least? I grep 'ed  some files but did not find anything useful.

**Comment by timhoffm** [comment]
If you want to do this, you would have to modify the [language definiton](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#LANGUAGEDEF).

**Warning: Be sure you understand the implications:**

**1. Defining your own language definition overrides the built-in TeX language definition. You will only see your version. You are decoupled from any changes we might make to the built-in definition in future releases.**

**2. We expose the language specification to you as end-user to give you more flexibility in adapting TeXstudio to your needs. But you should take it as is, because we don't have the capacity to give support here.**

If you still want to do this:

1. Get a copy of `tex.qnfa` from the repo.
2. Create a folder `languages` in your settings directory and place the file therein.
3. Edit your version of `tex.qnfa`.
4. Restart TeXstudio.
