### ISSUE TITLE
Overhauling user manual

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#2608]
The user manual seems to be more and more outdated.
I have started to convert the manual to markdown and reordered it. (https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/usermanual_en.md)
Help is welcome, especially for the parts which are annotated **todo** .
Target audience are users who are getting started and are looking for new features or trying to solve issues.

**Comment by sunderme** [comment]
there are a few points i want to achieve and maybe someone can help.
* TOC should be beside the text in html, similar to https://pandoc.org/MANUAL.html
* tooltips on top of images would be great to allow context sensitive information.

**Comment by octaeder** [comment]
destroyed my bookmark chapter, please fix:
![image](https://user-images.githubusercontent.com/102688820/192116413-cd8ac816-d938-4752-b204-e1b0e0d5bc71.png)

**Comment by sunderme** [comment]
https://github.com/texstudio-org/texstudio/pull/2607#issuecomment-1257010002 , furo looks interesting. 
For now the usermanual_en.md is written as markdown. Let's see what is the best way to get a html out of it.

**Comment by octaeder** [comment]
your images look quite oversized. Ex. quickstartwizard is 1050 pixels wide, more than half of a FullHD display. Image info shows 144dpi. It should be rendered at about 96dpi (67%).

**Comment by dbitouze** [comment]
> [#2607 (comment)](https://github.com/texstudio-org/texstudio/pull/2607#issuecomment-1257010002) , furo looks interesting. For now the usermanual_en.md is written as markdown. Let's see what is the best way to get a html out of it.

Here is a proof of concept with (a minimal configuration of) `Sphinx-doc` as documentation generator and  `usermanual_en.md` as source file (as it is: could be improved):

- for the HTML output (with `Furo` as theme): https://dbitouze.gitlab.io/texstudio-manual/usermanual_en.html
- for the PDF output: [texstudio.pdf](https://github.com/texstudio-org/texstudio/files/9641733/texstudio.pdf)

**Comment by dbitouze** [comment]
> `usermanual_en.md` as source file (as it is: could be improved)

I meant, from the `Sphinx-doc` point of view.

I also forgot to give the link to the source: https://gitlab.com/dbitouze/texstudio-manual

**Comment by sunderme** [comment]
I tried to use sphinx here. Apparently it is a bit tricky on ubuntu (20.04) as the extensions are not present and it failed.
I can get a very similar output with pandoc alone which is less complicated.
So for now, I will generate the helpfile this way, but that does not mean we can't change it later as the source is the same anyway.

**Comment by dbitouze** [comment]
> I tried to use sphinx here. Apparently it is a bit tricky on ubuntu (20.04) as the extensions are not present and it failed.

Here is a procedure that worked for me in a VM with Ubuntu 22.04:

```bash
sudo apt-get install python3-pip python3-dev python3-setuptools apache2 -y
pip3 install --upgrade pip
pip3 install sphinx
pip3 install myst_parser
pip3 install sphinx_comments
pip3 install sphinx_design
pip3 install sphinxext.opengraph
pip3 install furo
mkdir ~/tmp
cd ~/tmp
wget https://gitlab.com/dbitouze/texstudio-manual/-/archive/main/texstudio-manual-main.tar.bz2
tar xvfj texstudio-manual-main.tar.bz2
mkdir texstudio-manual
cd texstudio-manual
~/.local/bin/sphinx-quickstart # Answer `y` at the first question and whatever you want
                               # at the subsequent questions (the answers will be erased by the
                               # configuration file I provide).
mv -f ~/tmp/texstudio-manual-main/source/* source/
sed -E -i 's#sphinx-build#~/.local/bin/sphinx-build#g' Makefile
make html
xdg-open build/html/usermanual_en.html
```

**Comment by octaeder** [comment]
- some images in chapter 1 show a terminal tab which is not present by default
- maybe 1.1 should give hint that installing LaTeX should be done before starting TeXstudio (what happens when you proceed the other way round?)
- wrong image in section 1.2 (read the text), some of the text moved to 6.1, so same problem there (app image missing)
- quick wizard shown in 1.3 is old while the one in 2.1.1 is new (not released change)
- last sentence of introduction to 5.8 not longer suitable since you (re-) moved description for the pdf-viewers

**Comment by sunderme** [comment]
for whatever reason, pip install failed here. 
But from what I see, it is not really necessary to run sphinx more than once. The only important part seem the template for pandoc and the css file (and js possibly).
My current approach is an adaptation of https://github.com/Mushiyo/pandoc-toc-sidebar and this seems to be sufficient.
With pandoc present, you only have to call `convertToHTML.sh` in `texstudio/utilities/manual`.

**Comment by dbitouze** [comment]
> Here is a procedure that worked for me in a VM with Ubuntu 22.04:

I forgot the process for the PDF output format::

```bash
cd ~/tmp/texstudio-manual
make latexpdf
xdg-open build/latex/texstudio.pdf
```

**Comment by dbitouze** [comment]
> My current approach is an adaptation of https://github.com/Mushiyo/pandoc-toc-sidebar and this seems to be sufficient.

But, this way, you cannot get PDF output format.

**Comment by dbitouze** [comment]
>for whatever reason, pip install failed here.

Probably easy to fix.

**Comment by sunderme** [comment]
pandoc can deliver pdf as well (via latex) and it looks okay.
The important part is to have a markdown source file, that we can transform in all outputs, one way or another. 
For html output, I would prefer a pandoc only approach as set-up seems to be easy enough on any system. You can still let run sphinx for a more fancy output.

**Comment by sunderme** [comment]
pip upgrade did the trick

**Comment by sunderme** [comment]
@dbitouze building the html locally, there is a second toc to the right.
That is actually quite useful as it is more detailed than the one on the left. However it does not scroll with the text, i.e. when the entry is outside of the current view, it does not scroll there. This may or may not be desirable ?
Anyway, the search box seems to be pretty useless for single page document. The comment function should not be there as it links to an external site.
Otherwise looks quite nice.

**Comment by dbitouze** [comment]
> @dbitouze building the html locally, there is a second toc to the right.

Interestingly, my local build doesn't provide such a local ToC but, indeed, there are provided for another project (a French LaTeX FAQ), e.g. https://dbitouze.gitlab.io/test-faq-fr/3_composition/tableaux/tableau_sur_plusieurs_pages.html

> That is actually quite useful as it is more detailed than the one on the left. However it does not scroll with the text, i.e. when the entry is outside of the current view, it does not scroll there. This may or may not be desirable ?

In the link above, you can see that the local ToC does scroll with the text. 

> Anyway, the search box seems to be pretty useless for single page document.

There could be two versions of the manual: one with a single page embedded with TXS, and another one, online, with several pages (more friendly IMO).

> The comment function should not be there as it links to an external site.

Again, could be useful for an online manual.

>  Otherwise looks quite nice.

OK.

**Comment by sunderme** [comment]
I have split the help file and put everything together in https://github.com/sunderme/texstudio/tree/manual
Maybe you can have a look ?

**Comment by sunderme** [comment]
direct link to the result: https://htmlpreview.github.io/?https://github.com/sunderme/texstudio/manual/utilities/manual/build/html/getting_started.html

**Comment by sunderme** [comment]
I have put it on github pages to test: https://sunderme.github.io/getting_started.html

**Comment by dbitouze** [comment]
> I have put it on github pages to test: https://sunderme.github.io/getting_started.html

Very nice, thanks!

Some minor remarks after a quick overview:

- some commands are not entered as code (`\hline, %\s?[A-Z][A-Z_-]+`, etc.),
- keyboard keys should be harmonized and displayed with a nice and special style (e.g. “Ctrl+Shift+I” → <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>, if not <kbd>Ctrl</kbd>+<kbd>⇧</kbd>+<kbd>I</kbd>).

**Comment by dbitouze** [comment]
IMO, `sphinx-comments` is still useful since, used with e.g. https://web.hypothes.is/:

 - the visitors are then able to put comments (that might be helpful for improving the manual) without the necessity to open an issue (and then to have a GitHub account),
 - it can be used by the visitors just as comments (and global bookmarks over the Internet) for themselves.

**Comment by sunderme** [comment]
the whole manual is static with local resources, only the comments would break that. Especially as the manual is also installed locally on the user's computers.

**Comment by dbitouze** [comment]
> the whole manual is static with local resources, only the comments would break that.

Is it a big deal?

> Especially as the manual is also installed locally on the user's computers.

This would concern only the online version of the manual.

**Comment by dbitouze** [comment]
> In Germany, there was a successful law-suit that loading google fonts from google in the webpage was a violation of privacy, so I stay away from that as much as possible.

AFAICS, no Google Font [here](https://dbitouze.gitlab.io/texstudio-manual/usermanual_en.html).

**Comment by octaeder** [comment]
typo in "The result is in `./build/html/` , `getiting_started.html` as entry point." of file Readme.md

**Comment by octaeder** [comment]
Text and command examples in _set-up for external viewers_ are broken: Many new brackets [ or ], or parts of command lost (s. okular, Foxit Reader has add. slash).

**Comment by octaeder** [comment]
Remarks on chapter Configuring TeXstudio:
- spellchecker, thesaurus, and grammar are no longer configured under _General_, move it to _Grammar_. The syntax checker is configured under _Completion_.
- As the group is called _Menus_ the section should be _Configuring the Menus_. Seems to be reasonable since configuration of all menus is possible, not only math and latex.
- As the group is called _Toolbars_ the section should be _Configuring the Toolbars". Seems to be reasonable since configuration of all toolbars is possible, not only for custom toolbar.
- As the group is called _SNV/GIT_ the section should be _Configuring SVN and GIT_.
- There is a backslash after _The internal pdf viewer also accepts the following options (txs:///internal-pdf-viewer) to modify its behaviour:_

Chapter Advanced features:
- There is a backslash at the end of _The “run script” button directly executes a script in the editor for testing._ and at the end of _Additionally the following special trigger terms (without parentheses) can be used to execute the script when the corresponding event occurs:_

Chapter Background information:
- There is a backslach after <command>[#classification] (s. cwl file format).
- There is a backslash after Examples: (s. between the two tables in classification format).

**Comment by octaeder** [comment]
- _The toolbars can be hidden by a right click on an empty space in the toolbar area._ It is unnecessary to target on empty space and could be difficult. Even this is possible (right click on the dropdown):
![image](https://user-images.githubusercontent.com/102688820/192893724-42cdd66f-05ea-498d-9d4a-493282c47432.png)
- Adapting the main GUI about toolbars: _They can be moved by dragging the handler on the left-hand side._ So the user might wonder why this is not true for the central bar. Cool, if you could change the behavior for it, otherwise you could give it a small note.
- This is not a current image 
![image](https://user-images.githubusercontent.com/102688820/192895489-e32032ef-8779-4858-80d8-97ec3d827270.png)
as you can see here:
![image](https://user-images.githubusercontent.com/102688820/192897518-3e9a5a09-97a1-4e44-97b3-357913d801d4.png)
- Changing shortcuts is a little bit different for Editor/Basic Key Mapping: Only _Current Shortcut_ can be changed, no _Additional Shortcut_ is possible.

**Comment by octaeder** [comment]
Chapter _Editing a Tex Document_, section _Formatting your text_ right at the beginning:
- toolbar in two words found
- the image of the _Format_ toolbar is outdated. Changing text size is done in the (horizontal) _Format_ toolbar (s. getting started). The others can be found in the (vertical) _Central_ toolbar.
Btw. to be consistent, it should be _Central_ in the image (chapter getting started) as you used _Tools_, _Format_, _Table_.
- _Additional option_ states _This option is available for all the environments indicated by “[selection]” in the “LaTeX” menu._ But nothing like _[selection]_ can be found in the LaTex menu.
- Image of the Quick Tabular wizard is outdated.
Btw. some of the wizards can be closed with ESC, others not.
- Image of the Insert Graphics wizard is outdated. So it shows something interesting with respect to PR #2609:
![image](https://user-images.githubusercontent.com/102688820/192903424-05998765-cf9b-425a-9c99-5022280c941b.png)
The second option was part of the frame (marked here with red lines) surrounding the options for caption, label, and position. The first two options are aligned. So I believe the PR was a fix not a GUI change.
- Section _Cross References and notes_ shows \*\*Additional option:\*\* right after the image. Seems to be a mark down.
- Chapter _Inserting math formula_ shows math symbols in the _Math_ toolbar, but these are located in the _Central_ toolbar these days.
- Another backslash: _The completer has several operation modes which are shown in the tabs below the command list.\\_
- Please add to the _Auto Completion_ section that switching operation mode is done with SHIFT+SPACE.

**Comment by octaeder** [comment]
- [ ] typo in _The changes is perofrmed immediately_ (Configuring TeXstudio/Configuring GUI scaling)

**Comment by octaeder** [comment]
Welcome to TeXstudio Manual’s documentation Has this a special meaning? I mean manual and documentation.

**Comment by octaeder** [comment]
- [ ] typo in _available as shortcurs_ (Editing a TeX document/Formatting your text)
- [ ] Editing a TeX document/Inserting a table/Manipulating tables contains a short paragraph about block cursors. But now there is a new section _Block cursor_ in _Special Commands_. Maybe the first one should have a link to the second or this should be consolidated.
- [ ] Last sentence in _Block cursor_ is _By clicking Ctrl+Shift+Alt+left click a block from the current cursor to the mouse position is selected._ But Ctrl+Shift+left click is sufficient for this and much easier to press with your left hand :-)
- [ ] Please add that you can create a column of cursors with Ctrl+Alt+CursorUp/Down.
- [ ] Please add that all cursors can be moved with CursorLeft/Right/Up/Down at once.

**Comment by octaeder** [comment]
- [ ] In Editing a TeX document/Inserting a table/Manipulating tables contains a short paragraph about block cursors. It says _Press Ctrl+Alt and drag the cursor with the mouse._ But the keys are Ctrl+Shift as pointed out in special commands Block cursor.

**Comment by octaeder** [comment]
- [ ] The image showing the context menu of the inline preview shows _Clear In...e Preview_ instead of
![image](https://user-images.githubusercontent.com/102688820/193275588-0c0893e9-cbb8-4960-912b-a0cfdcf0c832.png)

- [ ] The preview pane and it's context menu could be described/presented.
![image](https://user-images.githubusercontent.com/102688820/193274885-b4dd9cd9-9517-4afd-a796-32d8e79e354a.png)

**Comment by octaeder** [comment]
- [ ] In Configuring TeXstudio/Configuring the spell checker, wrong wording in _on windows a large number is languages is provided_. Suggesing "of" replacing first "is".
- [ ] In the same paragraph we find _A particularly convenient way to get additional dictionaries is downloading a dictionary extension of [http://wiki.services.openoffice.org/wiki/Dictionaries](http://extensions.openoffice.org/) or [LibreOffice](https://extensions.libreoffice.org/extensions?getCategories=Dictionary&getCompatibility=any)_. For the first link I feel it's not nice to use a different link under the hood. Both links should be those of PR #2615 , s. my post above from september 29th at 12:24 am.

**Comment by octaeder** [comment]
add to previous post:
- [ ] wrong wording in _Linux distributions usually over a wide range of hunspell dictionaries as well which can be used_. Suggesting "offer" replacing "over".

**Comment by octaeder** [comment]
- [ ] In Configuring the grammar checker, wrong wording in _which need to be provided in the “Wodlist Directory”_.

**Comment by octaeder** [comment]
- [ ] I wonder if this is a current image (compile_toolbar.png, s. Compiling a document):

![image](https://user-images.githubusercontent.com/102688820/193377027-3d7845c1-9dc6-403d-a930-3b45d56f79b5.png)

The stop symbol is not a square, but it is in the images of chapter Getting started.

**Comment by sunderme** [comment]
in my opinion, the main update work is done.

**Comment by octaeder** [comment]
- [ ] The [texstudio.org](https://www.texstudio.org/#features) page still shows _user manual_ with link to old manual.

**Comment by octaeder** [comment]
@sunderme Which of the following changes/additions to the manual do you (not) want to have? These are from my task lists above. Please leave comments:

1. As the group is called _Menus_ the section should be _Configuring the Menus_. Seems to be reasonable since configuration of all menus is possible, not only math and latex.
2. As the group is called _Toolbars_ the section should be _Configuring the Toolbars_. Seems to be reasonable since configuration of all toolbars is possible, not only for custom toolbar.
3. Add a note that changing shortcuts is a little bit different for Editor/Basic Key Mapping: Only _Current Shortcut_ can be changed, no _Additional Shortcut_ is possible.

And what about this? The [texstudio.org](https://www.texstudio.org/#features) page still shows _user manual_ with link to old manual.

Thx

**Comment by sunderme** [comment]
> @sunderme Which of the following changes/additions to the manual do you (not) want to have? These are from my task lists above. Please leave comments:
> 
>     1. As the group is called _Menus_ the section should be _Configuring the Menus_. Seems to be reasonable since configuration of all menus is possible, not only math and latex.
> 
>     2. As the group is called _Toolbars_ the section should be _Configuring the Toolbars_. Seems to be reasonable since configuration of all toolbars is possible, not only for custom toolbar.
> 
>     3. Add a note that changing shortcuts is a little bit different for Editor/Basic Key Mapping: Only _Current Shortcut_ can be changed, no _Additional Shortcut_ is possible.
> 
> 
> And what about this? The [texstudio.org](https://www.texstudio.org/#features) page still shows _user manual_ with link to old manual.
> 
> Thx

I have implemented the changes.
texstudio.org will be updated with the next release.

**Comment by octaeder** [comment]
s. [here](https://texstudio-org.github.io/configuration.html#advanced-configuration-of-the-build-system)
- [ ] There should be no double quote in: _In advanced mode, you can reference it using txs:///"\<command id\>_
- [ ] Should be "them": _Do not use then at Options -> Commands._

**Comment by octaeder** [comment]
@sunderme Shouldn't there be a md file for each html file, as it is for configuration.html? 8066ab7075c7a6205dcacc113974b092eea0a799

![grafik](https://user-images.githubusercontent.com/102688820/196009188-015e9f92-8b81-4bd3-8e6e-5213e74d8a8b.png)

I think that these files will be overwritten when the manual is generated the next time.

**Comment by octaeder** [comment]
@sunderme In chapter Editing a TeX Document -> Special Commands -> Rename Environment:
- [ ] it may worth noting that one can circumvent waiting for the mirror cursor by double-clicking the environment name. This will immediately activate the mirror cursor. As a side effect, the name is selected and you can enter a new name. As an example: change equation to aligned.

**Comment by dbitouze** [comment]
> there is no "online" version of the manual, it is the same on the computer and on pages. In Germany, there was a successful law-suit that loading google fonts from google in the webpage was a violation of privacy, so I stay away from that as much as possible.

A drawback of not providing an online manual is that the one coming with TXS has a search box which doesn't work.

And TXS would be I guess the single software in the world that doesn't provide an online version of its manual...

**Comment by sunderme** [comment]
there is an online version of the manual (https://texstudio-org.github.io/getting_started.html), it simply is not the only one.

**Comment by dbitouze** [comment]
> there is an online version of the manual (https://texstudio-org.github.io/getting_started.html), it simply is not the only one.

From your sentence I quoted, I supposed you didn't want to provide any online version of the manual. Sorry for the noise.
