### ISSUE TITLE
Weird behavior when using mouse to select text to the end of document

### ISSUE THREAD

**Issue by jzniu** [texstudio-org/texstudio#2614]
When I use the mouse to select text to the end of a document, once it reaches the end, the cursor somehow moves back to somewhere in the middle of the document. I'm not sure if this is related to Qt or texstudio itself. Using Shift+Down to select doesn't have this issue.

### Environment
- TeXstudio: 4.2.1 (having the same issue before this version I believe)
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior

The mouse cursor should stay at the end of the document and selection of text just ends there.

### Actual behavior

The mouse cursor moves to somewhere in the middle of the document once it reaches the end of the document. It seems that internally some modulo operation is used causing the issue.

### How to reproduce

Use the mouse to select text to the end of a document.

**Comment by octaeder** [comment]
Sorry, can't reproduce with current 4.3.1 Qt6 Win10. Check it with latest portable version of txs with Qt6.

**Comment by jzniu** [comment]
I use a Qt5 version because the Qt6 version doesn't display things consistently on multiple of my computers. Qt6 doesn't seem to have this issue. When I tried to test on the latest portable Qt5 version, texstudio crashed whenever I dragged a .tex document into it. Again this is on Windows 10.

**Comment by sunderme** [comment]
not reproducible
txs/win qt5 is deprecated, 4.4.0 will not have a win/qt5 version.

**Comment by jzniu** [comment]
The same issue exists in the version below:

TeXstudio 4.4.0 (git 4.4.0)
Using Qt Version 6.4.1, compiled with Qt 6.4.1 R

**Comment by octaeder** [comment]
Is this reproducable? Can you clarify what mouse cursor movement you exactly do until the cursor jumps away (s. below)? Does this happen in all documents?

can't reproduce with TeXstudio 4.4.1 (git 4.4.1) Using Qt Version 6.4.1, compiled with Qt 6.4.1 R for Win10 (4.5.1 is the only newer version available):

![grafik](https://user-images.githubusercontent.com/102688820/220074927-40612e4d-d4a0-4db4-bc7c-5c150cd40df6.png)

Nothings random happens when dragging the cursor to the last character of the last line.

Now I can see something that could be what you see: Set the text cursor in the last line (not necessary but simplifies action). No further text needed in that line. Move mouse cursor over the last line, press left mouse button, then drag it over the last line number and then one line below (this may be the editor status line). Then the text jumps upwards and probably repeats in a loop. Same in 4.51. This seems not depend on the Adv. Editor setting for Vertical Overscroll.

**Comment by jzniu** [comment]
Tried this document with about 20 lines. Just used mouse to press and select text from somewhere in the middle to the end, then the selected area seemed to repeatedly restart from line 1.

![2023-02-20_5-54-32](https://user-images.githubusercontent.com/6538395/220086200-738c9576-3043-4e9a-b98b-ca0c784fbe9f.gif)

**Comment by octaeder** [comment]
I think this is basically what I described. Your mouse cursor moves down left to the editor and there over the status line.
Maybe @sunderme has some idea.

**Comment by sunderme** [comment]
looks like you need to place the mouse pointer at the "L" of "Line".
So below the line numbers in the status line.

**Comment by octaeder** [comment]
It seems what you have to do is moving the mouse cursor past the left edge of the editor below the last line (not necessarily line number panel activated), s. red area. With overscroll active the line after the last line may not be virtually the status line.

![grafik](https://user-images.githubusercontent.com/102688820/220089988-72b9af75-313e-4289-87dd-901242fc74a9.png)

**Comment by octaeder** [comment]
This happens even if you disable line numbers, folding and Line Change States (will also deactivate line marks), i.e. no editor side panels visible. So moving over the left edge and past last line seems to be the criterion.

**Comment by octaeder** [comment]
@sunderme not fixed, assume from my tests that the following should be used:
```
    if(ln>=lines()){
        ln=lines()-1;
    }
```

**Comment by sunderme** [comment]
I don't see fails, demonstrate.

**Comment by octaeder** [comment]
click into last line and drag into the red rectangle
![grafik](https://user-images.githubusercontent.com/102688820/220181664-35edc04a-a592-457e-92cc-ac10783df7ff.png)

**Comment by octaeder** [comment]
![grafik](https://user-images.githubusercontent.com/102688820/220182218-1685dd21-e195-46e1-aa10-ba1aa5091e83.png)

**Comment by octaeder** [comment]
![grafik](https://user-images.githubusercontent.com/102688820/220203504-864e21ea-5233-4d71-98cd-baea5e3a5aa7.png)
Test ok
