### ISSUE TITLE
chapters missing from the structure pane

### ISSUE THREAD

**Issue by jhdeov** [texstudio-org/texstudio#2666]
### Environment
- TeXstudio: 4..1.2
- Qt: 6.2.2
- OS: Mac
- TeX distribution: mixtex

### Expected behavior
I'm using a [latex template](https://github.com/langsci/latex-skeletons/raw/gh-pages/monographskeleton.zip) from a book publisher. \chapter{} commands should appear in the structure pane.

### Actual behavior
Chapters don't appear in the structure pane. 

![201017009-5c80d5d1-6ca6-4043-bf4b-fb890a7e0773](https://user-images.githubusercontent.com/42621803/201017994-06d90b16-974e-42a2-9de7-f347c1e5bfc7.png)

### How to reproduce

Example latex is attached. This works on overleaf. I asked the publisher's latex team (who were surprised by this glitch), and they didn't know a solution. 

[chapter-missing.zip](https://github.com/texstudio-org/texstudio/files/9977967/chapter-missing.zip)

**Comment by mbertucci47** [comment]
The chapters show up fine for me with the template given. The problem is that your file is not automatically recognizing the `langscibook` class and loading the correct cwl (completion file) that contains `\chapter`. You can make the class file permanently active by Options->Configure TeXstudio->Completion and checking `class-langscibook.cwl`. This will, however, make the langscibook commands part of autocompletion for all documents regardless of whether `langscibook` is loaded.

**Comment by jhdeov** [comment]
I upgraded to the new version and that fixed it...
