### ISSUE TITLE
Shortcuts for Greek Alphabets

### ISSUE THREAD

**Issue by abelokoj-github** [texstudio-org/texstudio#2675]
### Describe the feature and the current behavior/state
I created a script that allows users to add Greek shortcuts to  be typed with very few keystrokes.

Take for example, **typing** `a><` will immediately produce `\alpha`,  `q><` will give `\theta`,  `l><` will give `\lambda` This makes typing math a bit more comforting and relatively faster.

Maybe you can add it as a feature in your next release. 

See the full code set below.

### Who will benefit with this feature?
Virtually all users
### Code  Script Below
```
Trigger: (\w+)><

%SCRIPT

shortcut = {
'a': '\\alpha',
'b': '\\beta',
'g': '\\gamma',
'd': '\\delta',
'e': '\\epsilon',
'z': '\\zeta',
'n': '\\eta',
'q': '\\theta',
'i': '\\iota',
'k': '\\kappa',
'l': '\\lambda',
'm': '\\mu',
'n': '\\nu',
'o': '\\omicron',
'p': '\\pi',
'r': '\\rho',
's': '\\sigma',
't': '\\tau',
'u': '\\upsilon',
'f': '\\phi',
'ch': '\\chi',
'ps': '\\psi',
'w': '\\omega',
'vt': '\\vartheta',
'vep': '\\varepsilon',
'D':  '\\Delta',
'P': '\\Pi', 
'Ps': '\\Psi',
'F':  '\\Phi',
'G':  '\\Gamma',
'Q':  '\\Theta',
'L':  '\\Lambda',
'X':  '\\Xi',
'Y':  '\\Psi',
'S':  '\\Sigma',
'U':  '\\Upsilon',
'W':  '\\Omega',
}

 if (shortcut[triggerMatches[1]] !== undefined) {
    replacement = shortcut[triggerMatches[1]]
	editor.write(replacement)
 }

```

**Comment by muzimuzhi** [comment]
Or you can contribute it to https://github.com/texstudio-org/texstudio-macro

**Comment by abelokoj-github** [comment]
Do I have to make a pull request for that?

I actually prefer something that probably comes along with the default TexStudio build. I think it will be very helpful for users especially those working of Math and Physics related documents. It makes the work extremely fast.

**Comment by octaeder** [comment]
The [macro repository](https://github.com/texstudio-org/texstudio-macro) works the same as this one. You can create issues and pull request. These macros can be imported easily via the macro menu of txs.
Do you think command completion isn't usefull for these commands?

**Comment by dbitouze** [comment]
> Do I have to make a pull request for that?
> 
> I actually prefer something that probably comes along with the default TexStudio build. I think it will be very helpful for users especially those working of Math and Physics related documents. It makes the work extremely fast.

I strongly support the idea of providing efficient shortcuts, not as a macros which most of the users don't know and use, but directly in TXS.

**Comment by abelokoj-github** [comment]
> > Do I have to make a pull request for that?
> > I actually prefer something that probably comes along with the default TexStudio build. I think it will be very helpful for users especially those working of Math and Physics related documents. It makes the work extremely fast.
> 
> I strongly support the idea of providing efficient shortcuts, not as a macros which most of the users don't know and use, but directly in TXS.

This exactly my thought. When I checked the macro repository, I saw a few good codes which I never even new existed. SO many users will not be aware of this if it is not directly included in TexStudio. As for me, I think it is working fine so far, and honestly it has shifted typing math to another level in terms of speed, and comfort.

**Comment by sunderme** [comment]
I prefer it as macro in the macro library.
the shortcut is not self-explanatory and it is nearly impossible, that someone stumbles over it by accident. And if he does, because he actually wanted to insert something different and now he can't.
The user needs to be very aware of in-text keywords. My preference is using the completer and that special cases are handled via macros, activated, conciously, by the user.

**Comment by geolta** [comment]
I'd also prefer adding this or a similar behaviour to TXS by default (although it should be possible to disable of course). Instead of using the `letter><` syntax, something like `@letter` like it is done in the *LaTeX Workshop* extension of VSCode would be possible as well (but this would require typing a `@` what is difficult with some keyboard layouts, so I'm not sure whether this syntax is really a good idea).

I really don't know anything about the completion system but would it be possible to show a completion for greek letters if you type `><`? This might be a good compromise since it is correct that this macro makes it impossible to type `a><` (for whatever reason you want to type that ;) ).

> the shortcut is not self-explanatory and it is nearly impossible, that someone stumbles over it by accident

This is related to a general problem in TXS, that is has a giant amount of features without a easy to access ressource where everything is explained (something like a welcome tour at the first start).

A general note on the script: Currently, typing a letter that doesn't exist in the dictionary like `A><` leads to it's removal.

**Comment by sunderme** [comment]
the manual has been improved.
Apart from that *all* in-text replacements are dangerous (and I will probably not accept them),
e.g. someone edits a verbatim with any programming language and all of a sudden text is changed.
Macros are a good compromise in that respect, as the user can do whatever he likes.

**Comment by sunderme** [comment]
and maybe a final hint, what can be done with the completer.
The setting below allows typing 'a' and then ctrl+space. The Completer will offer "a(User Tag)" which is completed to "\alpha".
This approach should be free of any unwanted side-effects and is even simpler than the approach above.
<img width="886" alt="grafik" src="https://user-images.githubusercontent.com/14033169/201738685-6aa01b81-c3b2-4526-8297-018a520c0b74.png">

**Comment by dbitouze** [comment]
> but this would require typing a `@` what is difficult with some keyboard layouts, so I'm not sure whether this syntax is really a good idea).

Please, not `@`: a nightmare on French keyboard! :smile:

**Comment by dbitouze** [comment]
> and maybe a final hint, what can be done with the completer. The setting below allows typing 'a' and then ctrl+space. The Completer will offer "a(User Tag)" which is completed to "\alpha". This approach should be free of any unwanted side-effects and is even simpler than the approach above. <img alt="grafik" width="886" src="https://user-images.githubusercontent.com/14033169/201738685-6aa01b81-c3b2-4526-8297-018a520c0b74.png">
> 
> For completeness sake: https://texstudio-org.github.io/editing.html#user-tags-completion

Doing this for every Greek letter is rather tedious.

**Comment by abelokoj-github** [comment]
> I'd also prefer adding this or a similar behaviour to TXS by default (although it should be possible to disable of course). Instead of using the `letter><` syntax, something like `@letter` like it is done in the _LaTeX Workshop_ extension of VSCode would be possible as well (but this would require typing a `@` what is difficult with some keyboard layouts, so I'm not sure whether this syntax is really a good idea).
> 
> I really don't know anything about the completion system but would it be possible to show a completion for greek letters if you type `><`? This might be a good compromise since it is correct that this macro makes it impossible to type `a><` (for whatever reason you want to type that ;) ).
> 
> > the shortcut is not self-explanatory and it is nearly impossible, that someone stumbles over it by accident
> 
> This is related to a general problem in TXS, that is has a giant amount of features without a easy to access ressource where everything is explained (something like a welcome tour at the first start).
> 
> A general note on the script: Currently, typing a letter that doesn't exist in the dictionary like `A><` leads to it's removal.

You definitely do not need to use capital letters.   Use the small letters for small lettered greek alphabet. an capital letters for capital lettered greek alphabets. An example is `D><` which gives `\Delta` whereas `d><` gives `\delta`

Regarding someone suggesting to use @ symbol, I think you can easily change the shortcut as you want. I only figured that `><` will not be easily typed for any other purpose in a document, hence I set it that way. Moreover, it is closer to my fingers while typing than that @ symbol

To change this you can simply replace `Trigger: (\w+)><` with `Trigger: (\w+)@`

@sunderme  I understand your point. Maybe it can be disabled by default. However, that is one of the reasons I selected the shortcut trigger to be `><` instead of regularly used words. Maybe a better shortcut might solve the problem.

**Comment by dbitouze** [comment]
> .g. someone edits a verbatim with any programming language and all of a sudden text is changed.

I don't know if it is feasible but, indeed, such a feature should be disabled in verbatim environments.

**Comment by octaeder** [comment]
@sunderme one idea: the completer could add the macro name after usertag (macro menu to the left, completion for "a" to the right):
![image](https://user-images.githubusercontent.com/102688820/201760630-1e0cefcf-70c2-4448-9bda-b9ea6b8692f5.png) . . . . . ![image](https://user-images.githubusercontent.com/102688820/201760659-677987e7-f50d-46cf-98d4-81f8ad888140.png)

so it would show:

A (Usertag Alpha)
a (Usertag alpha)

**Comment by sunderme** [comment]
I agree, that can be improved.

**Comment by octaeder** [comment]
I made the macros from the original list posted above:

![image](https://user-images.githubusercontent.com/102688820/201792991-fb8209df-8f1f-42ed-a2e8-8324f1640ac5.png)

Test file:
```
\documentclass[a4paper]{article}
\usepackage{amsmath}
\begin{document}
\begin{align*}
\mathsf{a  } &\quad \alpha\\
\mathsf{b  } &\quad \beta\\
\mathsf{g  } &\quad \gamma\\
\mathsf{d  } &\quad \delta\\
\mathsf{e  } &\quad \epsilon\\
\mathsf{z  } &\quad \zeta\\
\mathsf{n  } &\quad \eta\\
\mathsf{q  } &\quad \theta\\
\mathsf{i  } &\quad \iota\\
\mathsf{k  } &\quad \kappa\\
\mathsf{l  } &\quad \lambda\\
\mathsf{m  } &\quad \mu\\
\mathsf{n  } &\quad \nu\\  %  s. \eta
%\mathsf{o }  &\quad \omicron\\
\mathsf{p  } &\quad \pi\\
\mathsf{r  } &\quad \rho\\
\mathsf{s  } &\quad \sigma\\
\mathsf{t  } &\quad \tau\\
\mathsf{u  } &\quad \upsilon\\
\mathsf{f  } &\quad \phi\\
\mathsf{ch } &\quad \chi\\
\mathsf{ps } &\quad \psi\\
\mathsf{w  } &\quad \omega\\
\mathsf{vt } &\quad \vartheta\\
\mathsf{vep} &\quad \varepsilon\\
\mathsf{D  } &\quad \Delta\\
\mathsf{P  } &\quad \Pi\\
%\mathsf{Ps } &\quad \\ s. Y
\mathsf{F  } &\quad \Phi\\
\mathsf{G  } &\quad \Gamma\\
\mathsf{Q  } &\quad \Theta\\
\mathsf{L  } &\quad \Lambda\\
\mathsf{X  } &\quad \Xi\\
\mathsf{Y  } &\quad \Psi\\
\mathsf{S  } &\quad \Sigma\\
\mathsf{U  } &\quad \Upsilon\\
\mathsf{W  } &\quad \Omega
\end{align*}
\end{document}
```
pdf ouput:

![image](https://user-images.githubusercontent.com/102688820/201791360-230e6926-c056-4578-87b7-3a36d3422642.png)

Comments:

- I assume a mistake in the original list: should it be "v" not "n" for \nu (n is used for \eta) ?
- o for \omicron did not work, since \omicron is unknown (which package?)
- Do you really want Y and Ps for \Psi?

**Comment by octaeder** [comment]
I suggest following changes (list ordered by 'abbreviation'):

![image](https://user-images.githubusercontent.com/102688820/201815859-3d64ed88-9706-4960-b6ed-035b47e70a98.png)

If anything is ok I can upload the macros with a PR.

**Comment by octaeder** [comment]
I think I've not been clear. The notation in the image, say z --> \zeta, means that you have to enter z in your text. then press ctrl+space which opens the completion list where you in best case (i.e. the abbreviation is unique) simply press enter to start the macro that uses "a" as an abbreviation and thus inserts \zeta.
Since all installed macros appear in the macro menu, I suggested to have them all in a subfolder, that's all. As sunderm said, he will not change txs to automatically replace these abbreviations out of the box.

**Comment by abelokoj-github** [comment]
@octaeder in my initial post, to get `\zeta`, I simply need to type `z><` and it will be automatically converted/replaced with `\zeta`

**Comment by sunderme** [comment]
can we close this ?
