### ISSUE TITLE
line math mode

### ISSUE THREAD

**Issue by guilleb90** [texstudio-org/texstudio#2719]
Hello. I want to suggest that the line math mode $ ... $ be written $$ instead of $ $ (no space between the first $ and the second $).

I also want to suggest that the shortcut Ctrl+Tab be available to activate the line math mode option.

**Comment by octaeder** [comment]
I'm used to typing $$ and then inserting the formula. Then I tried what is inserted by shortcut ctrl+shift+m for a while. But it did not convince me due to the additional spaces. So I went back to the old approach. What speaks against it is that \[  ]\ and \( \) are insert with two spaces.

I'm not sure if it is a good idea to choose that say special shortcut for this purpose. Maybe there will be something new where using ctrl+tab is more adequate. The original shortcut is nice for me because math starts with m. But you can do it for you. Add in the configuration your shortcut as described in the tooltip (click on image to enlarge):

![grafik](https://user-images.githubusercontent.com/102688820/205463472-b66f8fb2-219b-4418-bc8e-04865180eab9.png)

Do you still want the spaces being removed even if the shortcut is not changed?

I prepared a PR removing the spaces without changing the shortcut. Let's see if @sunderme agrees. Maybe the menu then should show $$ instead of $...$. Currently I stay with the ellipsis, for me it expresses that you can insert a formula.

**Comment by sunderme** [comment]
the default shortcut will not be changed, but that can be done by the suer as illustrated by @octaeder

**Comment by dbitouze** [comment]
The trouble with the new implementation is that, before any math is entered between the two `$`, the document seems to have syntax errors:
![Screenshot_20230123_185800](https://user-images.githubusercontent.com/1032633/214114758-7c42681b-110d-4b5e-afa4-aba60de1bc5b.jpg)

**Comment by sunderme** [comment]
indeed.

**Comment by octaeder** [comment]
Insert a line below $$ and the coloring normalizes.
Maybe this is because things like $$ x^2 $$ should also work? Even so I think $$ is TeX, not LaTeX.

**Comment by sunderme** [comment]
`$$ .. $$` is recognized by txs.
I owould rather suggest to insert `$ $` with the space in a placeholder. (or some text in a placeholder)

**Comment by octaeder** [comment]
I always thought that this "wrong coloring" should indicate that I forgot to insert a formula. First complaint I see here. I wouldn't change things.

**Comment by octaeder** [comment]
ok, I give up. A quick change shows this:

![grafik](https://user-images.githubusercontent.com/102688820/214123402-80a78c37-c324-4e79-86cb-4e140c88d8c6.png)

This?

**Comment by sunderme** [comment]
I already placed a space character. That is probably closer to how it is now.

**Comment by dbitouze** [comment]
> I already placed a space character. That is probably closer to how it is now.

“maths” instead of “formula” or of a space would not be bad.

**Comment by sunderme** [comment]
it has been changed to `$ $` with the space highlighted (placeholder)

**Comment by octaeder** [comment]
For a long time there had been two spaces with a cursor in the middle, recently the spaces were removed, and now one space comes back as a placeholder:

![grafik](https://user-images.githubusercontent.com/102688820/214164899-d142f6bd-a48f-42f4-a02a-8ccb8de99507.png)

Current state for users of 4.4.1 is with two spaces. I'm sure the user will immediately notice the small change. He may know more  or less about placeholders, mainly as one with a name like in \sqrt{arg}. So using `$maths$` would be more common. So I vote for `$maths$`.
