### ISSUE TITLE
Alignat Wizard

### ISSUE THREAD

**Issue by helour** [texstudio-org/texstudio#2921]
Hi,
would it be possible to implement the alignat wizard?
It would help me a lot in writing a system of equations.
Thank you for considering it.

![TeXStudioAlignat](https://user-images.githubusercontent.com/79715809/216573238-8a632ad2-ee50-44c0-8a10-e83c5d4dbb51.png)

**Comment by octaeder** [comment]
Alignat is basically like array, so I started enhancing the QuickArray dialog. Still some small bugs but it works. Here is your example that I slightly improved to get correct operator spacings. Below you see what has been entered in the dialog:

![image](https://user-images.githubusercontent.com/102688820/227777686-f8358349-16ee-4622-b84d-a5d9d91be350.png)

As you can see:
- the env statement being used shows in the title line.
- you can choose the package you use. So you can choose form different sets of envs offered by the packages. Main difference is between amsmath and mathtools, While the first always centers all columns, the latter has an optional argument that you can set with the Alignment combobox.
- since the table reflects the column alignment you have good visual feedback.
- now in case of array env you can set column alignment per column (the title shows your settings as said above).
- Besides array env the dialog chooses automatically column alignment. So in case of alignat there's no need to split columns.
- When the checkbox is set the dialog uses `*{n}{alingchar}` to replace runs of the same column alignment symbol alignchar (title bar will show this effect).

**Comment by dbitouze** [comment]
> It would help me a lot in writing a system of equations.

Generally, I'd advise to not use `alignat` for this purpose but the `systeme` package (it works better if the populated equations are on left hand side as in the second example below):

```latex
\documentclass{article}
\usepackage{systeme}
\begin{document}
\begin{enumerate}
\item \systeme{x_1=2-2x_2-x_3,2x_2=-5+x_1+2x_3,x_3=3-x_1-x_2}
\item \systeme{-2x_2-x_3+2=x_1,x_1+2x_3-5=2x_2,-x_1-x_2+3=x_3}
\end{enumerate}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/227784846-babbc60e-3b7b-4bd7-bd0b-7de2e2e97e2c.png)

**Comment by helour** [comment]
Nice. Thanks. How about adding a checkbox which enables automatically add curly brackets {} after all operators (or hardcoded +, -, =) in even columns (2, 4, 6) like this:
```
 x_1 &={} & 2 &-{} &2x_2 &-{} & x_3 \\
2x_2 &={} &-5 &+{} & x_1 &+{} &2x_3 \\
 x_3 &={} & 3 &-{} & x_1 &-{} & x_2

```

**Comment by dbitouze** [comment]
> @dbitouze I know the package 'systeme', but I also need to align elements at the '=' operator.
> 
> ```
>   x_1 &+{} &3x_2 &={} & 2 \\
> -4x_1 &+{} &2x_2 &={} &-5
> ```

It's possible with `systeme`:

```latex
\documentclass{article}
\usepackage{systeme}
\begin{document}
\sysalign{r,r}
\systeme{x_1 + 3x_2 =  2,-4x_1 + 2x_2 = -5}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/231662860-21f6cbc4-4812-4a1a-9762-784b7adf3c87.png)

**Comment by octaeder** [comment]
One drawback of package systeme, but not for everyone 😉, the documentation is in French.

**Comment by dbitouze** [comment]
> One drawback of package `systeme`, but not for everyone wink, the documentation is in French.

@octaeder Indeed, but most of its features are illustrated with telling examples :wink:
