### ISSUE TITLE
Packages Help (Texdoc) → Packages Documentations (texdoc)

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2992]
### Describe the feature and the current behavior/state
I suggest to replace the string “Packages Help (Texdoc)” (in the “Help” menu) by “Packages Documentations (texdoc)” since:
- what is displayed is more commonly called “Documentation“ than “Help”,
- the corresponding command-line tool is `texdoc`, not `Texdoc`.

### Who will benefit with this feature?
Everybody who is using TXS.

**Comment by sunderme** [comment]
extremely minute cosmetics ...

**Comment by octaeder** [comment]
@dbitouze In french sunderme would say "l'art pour l'art", or totally unnecessary. Be aware that we have to expect that already exist translations into many languages. Changing the text would make it necessary to retranslate all of them. Maybe translation into main languages can be done automatically, but all the rest? So it's wise thinking twice about text one wants to add to the code. Chances are (from my point of view) that sunderme would not accept a PR, so I don't dare to change this.

**Comment by sunderme** [comment]
That summarizes it quite nicely.
There are some unmaintained languages in txs. Any change of old texts invalidates another translation.
(Newly added texts do not fall under this restriction)

**Comment by dbitouze** [comment]
> @dbitouze In french sunderme would say "l'art pour l'art", or totally unnecessary.

That's what I assumed, but I wasn't sure. Congratulations on your mastery of French :smile: 

> Be aware that we have to expect that already exist translations into many languages. Changing the text would make it necessary to retranslate all of them.

But it would require, not a lot of work for one people, just a little for several people, isn't it?

Maybe the best would be to separate the core strings of TXS from their translation in English. Hence in the current case, “Packages Help (Texdoc)” could stay the core string and its translation in English could be changed into “Packages Documentations (texdoc)” without affecting the translations in other languages.

**Comment by dbitouze** [comment]
> That summarizes it quite nicely. There are some unmaintained languages in txs. Any change of old texts invalidates another translation. (Newly added texts do not fall under this restriction)

Hence my previous suggestion.

BTW, I've taken the liberty to translate in French as “Packages Documentations (texdoc)”.

**Comment by octaeder** [comment]
> _Maybe the best would be to separate the core strings of TXS from their translation in English._

This would introduce a new translation language database for English to be maintained, even so it should be easy because in most cases the coded text can be it's on translation (that's the point for the following). But I think this will not solve the core problem. Each time when translatable text is changed the translation databases for all languages change and use the coded text as translation, i.e. all language translations switch to English and need retranslation (@sunderme may correct me if I'm wrong). One way could be to only replace the text to be translated and not change the translation text. But this might introduce a new problem because the translation is related to a line number. So beside simple cases it might be not clear which old text in the database should be replaced by the new one (this could be something for a KI).

**Comment by dbitouze** [comment]
What I meant is that the translation text would stay the same and only the translations would change. I guess `Transifex` has a feature that lets the core team suggests to all the translators a change in the core (I mean, the English) translation.

**Comment by sunderme** [comment]
There will not be any "separation" of translation texts. 
The flow is basically defined by the needs of Qt/cpp and there is really no benefit in deviating from that.
