### ISSUE TITLE
Smoothed picture in built-in PDF viewer

### ISSUE THREAD

**Issue by YuryPakhomov** [texstudio-org/texstudio#3045]
### Environment
- TeXstudio: 4.5.1 and any other
- Qt: 5.15.8
- OS: Linux Slackware 15.0 (current)
- TeX distribution: texlive-2023.230322
- Poppler:  poppler-23.03.0
- 4k monitor 
- xorg-server-21.1.8

### Expected behavior
Clear and sharp page (pdf format) in built-in PDF viewer

### Actual behavior
Now the page is smooth, like a small DPI: https://disk.yandex.ru/i/W_dZsDJgR2k45g
A lens of built-in viewer shows fine as using the scaling. 
I use default settings of built-in viewer and system display resolution = 117 dpi
The external viewers (okular and others) works good.

### How to reproduce
Use built-in PDF viewer for any compiled TeX file
It is very likely that this is due to the use of the 4k monitor. Change DPI settings does not change the quality

**Comment by sunderme** [comment]
works fine on ubuntu

**Comment by sunderme** [comment]
not reproducible

**Comment by fedelibre** [comment]
@sunderme Have you tested it on a 4k monitor? (see the Environment list above)

I don't have a 4k monitor, but I found this issue because another application using poppler to render PDF files have some rendering problems on 4k monitors, see [this issue](https://github.com/frescobaldi/frescobaldi/issues/1485).

**Comment by sunderme** [comment]
I am working with 4k monitors.
Also, the pdf renderer was tweaked to deliver good results on scaled displays.
