### ISSUE TITLE
Move Line Up/Down incorrectly moves the line below selected line(s)

### ISSUE THREAD

**Issue by jzniu** [texstudio-org/texstudio#3131]
### Environment
- TeXstudio: 4.5.2
- Qt: Qt6
- OS: Windows10
- TeX distribution: miktex

### Expected behavior

Select one or multiple lines (from start of line N to start of line N+m), then use Move Line Up/Down to move the selected line(s) up and down. Only those selected lines (line N to line N+m-1 exactly, inclusive at both ends) move, not including line N+m.

### Actual behavior

Line N+m moves along as well. 

If the selection ends at the end of line N+m-1, then line N+m doesn't move along. It seems that the EOL character in line N+m-1 leads to the inclusion of line N+m. This may relate to the way of implementation regarding how many lines are considered.

Popular text editors, such as vscode, behave consistently regardless whether the EOL is included or not.

**Comment by octaeder** [comment]
I think this is a result of working with selections, s. LatexEditorView::getSelectedLineBlocks:

When a cursor is found with a selection then the indices of all lines from selection.startLine to selection.endLine are added to a list of lines being moved. But the last line should only be added if the selection doesn't end in column 0.

**Comment by jzniu** [comment]
Just tested in texstudio 4.6.0. This bug doesn't seem to be fixed, at least not fixed for demonstrated scenario shown below:

(select multiple lines and then move line up/down)

![2023-07-30 14 48 28](https://github.com/texstudio-org/texstudio/assets/6538395/cf9046d8-be98-4cce-8672-9ad7adee00f9)

**Comment by octaeder** [comment]
TeXstudio 4.6.3 (git 4.6.2-8-gfe43e18c2) moves line 5 even so there's no real selection because the selection started in line 2 column 0 and ended in line 5 column 0 (selection ends at end of line 4):

```latex
\documentclass[10pt,a5paper]{article}
\begin{document}
1
3
4
5
2
6
\end{document}
```

**Comment by octaeder** [comment]
The question is, what exactly is selected here? When you move the cursor at the beginning of line 5 one to the left then it works. And the blue highlighting is different:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/f69adc5e-76f9-431f-a72f-f2d48f570070)

after moving cursor left:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/4298914a-29d7-4f27-ae86-52089352efbe)

The difference in selection is the newline character.
Is this a natural/expected behavior in practice?

**Comment by octaeder** [comment]
Look at notepad++. Line 5 is not moved, but some changes appear:

select:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/fe491a3e-0e5e-4579-8746-b50b9a7a8b22)

move up (look at cursor, probably anchor and cursor are interchanged):
![image](https://github.com/texstudio-org/texstudio/assets/102688820/709143dc-698e-4e74-9e9a-9fbe61be0a3a)
Since highlighting doesn't look similar  to the next image, I assume that anchor is located before number 2 (newline is selected) not after 4.

select:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/fd6b68e2-15c0-425f-b8af-d196c8ca72b1)

move up:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/b8475477-1c5f-429d-ab9f-35cdd3bbad23)

**Comment by jzniu** [comment]
Several popular text editors, including vscode, notepad++, and sublime text, move the lines selected, including all text and eol characters on the lines that are even partially selected, regardless where the cursor is located, but not including the line where nothing is selected and only has the cursor at the start. For example, giving the following content:

1
2
33
444
5

If you have the following selected (in [])

3[3
44]4

The entire two lines will still move.

However I do notice that notepad++ somehow changed the selected scope when you move the lines to include the entire two lines, but vscode and sublime text don't do that although the entire lines move together. Obviously the latter is more reasonable and expected.
