### ISSUE TITLE
Help → Packages Help... doesn't work in all circumstances

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3143]
### Environment
- **TeXstudio:** TeXstudio 4.6.0 (git 4.6.0alpha1-92-g8fe8f984c)
- **Qt version:** 5.15.2, compiled with Qt 5.15.2 D
- **OS:** GNU/Linux (Mageia 8)
- **TeX distribution:** TeX Live 2023

### Expected behavior
Help → Packages Help... should work in all circumstances.

### Actual behavior

Help → Packages Help... doesn't work in all circumstances. For instance, when TXS is open but without any file open in it, that leads to a popup containing:

>Can't detect the file name.
>You have to save a document before you can compile it.

### How to reproduce
Open TXS but without any file open in it. Go to Help → Packages Help..., type e.g. “amsmath“ + Enter.

**Comment by octaeder** [comment]
No issue with **4.5.2** Win10. List is empty:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/f792bda0-195c-4b3b-b6ba-30b0ca6c97ef)
Maybe there should be no **description text**, s. texdocdialog.ui, line 45.

But you can type the name of a package:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/9eff85cd-1d66-40ac-a72a-d80b45d2f98c)
and you can see a message in the status bar:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/08309858-c172-46fe-9711-85ab355dad61)

**Comment by octaeder** [comment]
For me **it doesn't work with current master** compiled for win10 **even if you have a document**:
```
\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{mathtools}
\begin{document}

\end{document}
```
Packages help starts with

![image](https://github.com/texstudio-org/texstudio/assets/102688820/090f2a6c-a55a-4385-b71e-46a68d5debf7)

and messages panel says:
```
\MiKTeX 2.9\miktex\bin\x64\texdoc.exe"  --list --machine amsbsy
Process exited with error(s)
```
Same when I choose mathtools from the list. The message indicates that the MikTeX system has not been detected. I wonder because running texdoc.exe --version in console yields the expected string `MiKTeX Help Utility 4.2 (MiKTeX 23.1)`.

**Comment by octaeder** [comment]
The problem is that help.ccp wants to to figure out if miktex is present (otherwise texlive, ...):
```
bool Help::isMiktexTexdoc()
{
    if (!texDocSystem) {
        QString answer=runTexdoc("--version");
		texDocSystem = answer.startsWith("MiKTeX") ? 1 : 2;
	}
	return (texDocSystem == 1);
}
```
But runTexdoc uses runCommand for executing "texdoc --version" :
```
QString Help::runTexdoc(QString args)
{
    QString output;
    emit statusMessage(QString(" texdoc "));
    emit runCommand(BuildManager::CMD_TEXDOC+" "+args, &output);
    return output;
}
```
But this is:
```
bool Texstudio::runCommand(const QString &commandline, QString *buffer, QTextCodec *codecForBuffer, bool saveAll)
{
    if(saveAll){
        fileSaveAll(buildManager.saveFilesBeforeCompiling == BuildManager::SFBC_ALWAYS, buildManager.saveFilesBeforeCompiling == BuildManager::SFBC_ONLY_CURRENT_OR_NAMED);
    }
	if (documents.getTemporaryCompileFileName() == "") {
		if (buildManager.saveFilesBeforeCompiling == BuildManager::SFBC_ONLY_NAMED && currentEditorView()) {
			QString tmpName = buildManager.createTemporaryFileName();
			currentEditor()->saveCopy(tmpName);
			currentEditorView()->document->setTemporaryFileName(tmpName);
		} else {
			QMessageBox::warning(this, tr("Error"), tr("Can't detect the file name.\nYou have to save a document before you can compile it."));
			return false;
		}
	}
```
After this texDocSystem equals 2 and nothing will ever happen when you enter a package.

Maybe it's possible to execute `buildManager.runCommand` directly.
