### ISSUE TITLE
Some (new) ideas about the formulas preview 

### ISSUE THREAD

**Issue by helour** [texstudio-org/texstudio#3192]
1. Please separate the formula preview for the tooltip (where the mouse cursor is) and for the highlighted text (where the text cursor is).
2. The formula preview in the tooltip does not need to be updated when the text changed. The formula preview of the highligted math text in a window (panel tab, inline or embeded window) should always be updated automatically. The "Auto Update" section in the configuration will therefore no longer be needed.
3. Activation and deactivation of the formula preview in the tooltip should be available in the configuration, but the activation and deactivation of the formula preview in the window can be triggered using the ALT+P keyboard shortcut. Such an option is therefore not needed in the configuration.
4. In the config panel, the text "Show preview as tooltip on formulas in editor" can be changed to "Show preview of formulas in tooltip". The "Display Mode:" dropdown can be changed to dropdown with the text "Display Preview In:" with items "Preview tab", "Inline", "Embeded viewer".
5. After deactivating the preview in the window (ALT+P), the contents of the window should be cleared.

The reason why it would be good to have a different preview for the tooltip and a different one for the highlighted text is that if I accidentally move the mouse cursor to a different formula when correcting the text in the formula (when the formula preview is diplayed in the tooltip too), the formula preview in the preview tab changes and I have to set the preview again.

![MathPreviewTeXStudioConfig](https://github.com/texstudio-org/texstudio/assets/79715809/3b26844f-dfd0-4471-ada4-5fe62799a22a)
![MathPreviewTeXStudio](https://github.com/texstudio-org/texstudio/assets/79715809/29038bd4-93a6-4b68-b536-25631451081b)

**Comment by octaeder** [comment]
Current state is as follows:

- checkbox text _Show preview as tooltip on formulas in editor_ is misleading. When this option is set, then a preview will appear when the mouse hovers over a formula (whether it is inline or an environment). But how this preview is displayed depends totally on the setting of the _Display Mode_ option. Thus a better text could be _Show preview when mouse pointer hovers over formulas_. Previews of colors like in `\textcolor{red}{text}` do only show when display mode is tooltip, or preview panel.
- Preview Selection/Parentheses as well as Preview by hovering do not recompile when the previewed part didn't change.
- Option _Preview in embedded viewer_ is also misleading. What is meant is the internal pdf viewer (embedded or windowed).

It seems to me that you want that previews on hovering over formulas should always appear as tooltip. But then we shouldn't change the list of Display Modes. And again I would not use "Show preview of formulas in tooltip" because it is not clear what triggers the preview, and what happens when the option is not checked: Does the formula will never show a preview or does it show a preview, but not as tooltip? Still I suggest _Show preview when mouse pointer hovers over formulas_. We could add a tooltip to the option that clarifies that it's always a tooltip in this case (hovering).

I agree that the label and the texts of the combobox for the display modes could be improved. These are:

|old|new|
|---|---|
| Display Mode: | Show Preview: |
| Show preview as tooltip if panel is hidden | as tooltip when preview panel is hidden |
| Always show preview in preview panel | in preview panel |
| Always show preview as tool tip | as tooltip |
| Always show both | as tooltip and in preview panel |
| Inline | inline |
| Show in embedded viewer | in integrated pdf viewer |

Notes:
- Last option has extra comment "Only available if pdflatex is used for compilation". But lualatex works, too.
- Changing texts needs changing idefix menu and add new translations.

I would not clear the preview in preview panel or in pdf viewer. A reason why one would like to end preview selected/parentheses could be, that the background highlighting (gray) of the current row is almost invisible with the preview highlighting (green).

Since update may take a while changing text may start many recompile processes. So it may me desirable to stop auto update.

**Comment by sunderme** [comment]
I would not change texts with no further benefit (translations).

**Comment by octaeder** [comment]
@sunderme That's why I made the note. But what do you think about the wish (as I understood) that hovering over a formula should always be previewed in a tooltip? The only complaint I would expect could be the inconvenience that you need to select an inline formula to preview it other than as tooltip. On the other hand is solves a problem I already stated in the last discussion, since such a preview would not change inline or pdf viewer previews by accident when moving the mouse pointer.

**Comment by sunderme** [comment]
"Hovering over formula gives always tooltip": is that not already the case ?

**Comment by octaeder** [comment]
no, depends on display mode (except inline, then it's tooltip).

**Comment by octaeder** [comment]
another exception: \[...\] doesn't show in pdf viewer (formula is not inline and not an env.)

**Comment by helour** [comment]
I would like to explain why I like to use the preview option and how I would like to use it.

Forget for a moment how it's coded in TeXStudio, and imagine some other "text editor" and standard text editing.

You have a lot of mathematical formulas in your text, and that makes it hard to navigate. You need to find a misspelled formula. Since your editor allows you to quickly render (preview) formulas where the mouse cursor is, you activate it and go from one formula to another. When you find the formula you need, you select the text you need (it's near the text cursor), and turn on rendering (previewing) the selected part using a keyboard shortcut with automatic rendering updates whenever you change the text. When you are done editing, you turn off rendering (preview) using the same keyboard shortcut, with the feedback of removing the rendering (preview).

Separating the preview for where the mouse cursor is and where the text cursor is has two advantages. The first is that if I accidentally move the mouse, it won't overwrite the content in the preview tab when the option is set to "Always show both". The second is that I have the ability to use the render of the first formula (preview in the tooltip) to edit the second formula, which is slightly different from the first (preview in the window).

**Comment by helour** [comment]
I would like to explain why I like to use the preview option and how I would like to use it.

Forget for a moment how it's coded in TeXStudio, and imagine some other "text editor" and standard text editing.

You have a lot of mathematical formulas in the text, which makes it difficult to navigate. You have to find the misspelled formula somewhere on the actual edited page. Since your editor allows you to quickly draw (preview) formulas where the mouse cursor is, you activate it and move from one formula to another. When you find the formula you need, you select the text you need (it's near the text cursor) and turn on rendering (preview) the selected part using a keyboard shortcut with automatic rendering updates whenever you change the text. When you are done editing, you turn off rendering (preview) using the same keyboard shortcut with the feedback of removing rendering (preview).

Separating the preview for where the mouse cursor is and where the text cursor is has two advantages. The first is that if I accidentally move the mouse, it won't overwrite the content in the preview tab when the option is set to "Always show both". The second is that I have the ability to use the render of the first formula (preview in the tooltip) to edit the second formula, which is slightly different from the first (preview in the window).

If it's complicated, don't deal with it. Could you at least do the text selection and deselection for the preview with a single hotkey (Alt+P), like a toggle switch?

**Comment by octaeder** [comment]
_I hope you are aware of the possibility to set the cursor into the math. environment name and just press Alt+P to see a preview of the environment._ I use Shift+Alt+P to stop previewing the selection. You can assign the shortcut in the so called options. When your preview is inline then it is removed. You can see that preview is stopped because the green selection is removed. Display Mode option can be set in the Idefix menu.

I look closely at what you wrote to clarify things:

1. > You have a lot of mathematical formulas in the text, which makes it difficult to navigate. You have to find the misspelled formula somewhere on the actual edited page.

   So your search is in the plain text of the editor, not in the pdf viewer.
2. > Since your editor allows you to quickly draw (preview) formulas where the mouse cursor is, you activate it and move from one formula to another.

   What exactly happens here? I assume that you want to see a preview of the formula that you "hit" with the mouse cursor in the plain text. Of which kind should this preview be? I assume that the preview should always be a tooltip (new behavior). You want an activator that can turn on/off showing previews on hitting formulas. There is already a checkbox option in the config (but there is no shortcut). Do you want in addition a checkable item in the idefix menu (similar to menu View/Show/Statusbar) for quicker access (menu navigation with keys, you can then assign a shortcut to the menu item)?

3. > When you find the formula you need, you select the text you need (it's near the text cursor) and turn on rendering (preview) the selected part using a keyboard shortcut with automatic rendering updates whenever you change the text.

   I think this is what menu Idefix/Preview Selection/Parentheses (Alt+P) does (including automatic updates if option is set, this is the default, s. configmanager.cpp, l. 730). The preview appears according to the Display Mode option.

   @sunderme I don't really see why auto update option isn't implemented as a checkbox rather than a combobox (comboBoxAutoPreview).

4. > Separating the preview for where the mouse cursor is and where the text cursor is has two advantages. The first is that if I accidentally move the mouse, it won't overwrite the content in the preview tab when the option is set to "Always show both".

   I'm not sure what _separating_ means here. Would it be ok to always show the preview as a tooltip when you hit the formula with the mouse pointer, while Alt+P shows the preview in accordance with the Display Mode option (as described above)?

5. > The second is that I have the ability to use the render of the first formula (preview in the tooltip) to edit the second formula, which is slightly different from the first (preview in the window).

   "(preview in the window)" is related to the second formula. So you see the first formula as a tooltip, and the second one in the internal pdf viewer (embedded or windowed), or inline. Be aware that the tooltip is visible for some seconds only.

**Comment by helour** [comment]
> I use Shift+Alt+P to stop previewing the selection.

Ok. I find that acceptable.

> When your preview is inline then it is removed, preview is stopped because the green selection is removed.

It's ok as a feedback. However, when I see the preview, I still get the feeling that it is active.

> So your search is in the plain text of the editor, not in the pdf viewer.

That's exactly what I do, with the advantage that I use the preview in the tooltip.

> I assume that you want to see a preview of the formula that you "hit" (i.e. hover over it) with the mouse cursor in the plain text.

Exactly.

> I assume that the preview should always be a tooltip (new behavior). There is already a checkbox option in the config (but there is no shortcut).

Yes, the current checkbox can be used.

> Do you want in addition a checkable item in the idefix menu (similar to menu View/Show/Statusbar) for quicker access (menu navigation with keys, you can then assign a shortcut to the menu item)?

No, I don't need it.

> I think this is what menu Idefix/Preview Selection/Parentheses (Alt+P) does.

That's exactly what I'm doing (I was just describing the situation).

> I'm not sure what _separating_ means here. 

Please look at the second picture. There are two _different_ previews. In the current version, you can only view _one_ preview, which can be displayed in two places. One in the tooltip and the other in the internal pdf viewer (embedded or windowed).

> So you see the first formula as a tooltip, and the second one in the internal pdf viewer (embedded or windowed), or inline. Be aware that the tooltip is visible for some seconds only.

Exactly. It might be useful to set the tooltip preview time in seconds. Or remember the preview in a cache, move the mouse a little bit next to it, and when the mouse cursor returns to the previous location (hover over it), display the cached preview.

**Comment by octaeder** [comment]
results for preview are cached, so tooltip will reappear quickly. But why not use Preview Selected/Parentheses with Display Mode _Inline_ in all cases (not mouse hovering)? In the following example I did twice: set the cursor in the env name (see alignat) and press Alt+P. I also marked the inline math with the mouse and pressed Alt+P. And in this way you still get tooltips for formulas.

![image](https://github.com/texstudio-org/texstudio/assets/102688820/50a93f49-dee4-4653-bc4b-c44d9110ea8b)

Another advantage of this approach is that you can scoll if needed to compare previews. A tooltip will disappear immediately when you start scrolling.

If this ok for you, I would say the only open point is, that the preview by hovering over a formula should always appear in a tooltip.

Maybe the "issue" with \\[...\\] I mentioned above should also be fixed.

**Comment by octaeder** [comment]
that's ok, so you may close this issue.
