### ISSUE TITLE
Search in math mode checkbox

### ISSUE THREAD

**Issue by 4252359N833231W** [texstudio-org/texstudio#320]
It would be useful to add a a checkbox to the search bar (like the 'case sensitive' one) that would allow you to search only within math modes in LaTeX (or only in text).

**Comment by sunderme** [comment]
what scenario demands this ?

**Comment by 4252359N833231W** [comment]
There are various conflictive scenarios:
- You want to find a variable that coincides with a word you repeat frequently in text.
- Yo want to search for a specific command that occurs both in text and math (\dots, for instance), but only in math mode.
- You want to replace something with something else that only makes sense in math mode (otherwise it would give back an error).

**Comment by ondrejtichacek** [comment]
It would definitely be useful. For me especially to exclude math mode from search.

My use-case scenario: In my language, prepositions are often one-letter characters and you need to include non-breakable space (~) after them. When I search for missed non-breakables, I often get matches with variables in equations, which are useless.

**Comment by niohiki** [comment]
Another upvote here. 

A common case I find (a bit the reverse of @ondrejtichacek): I want to change a variable I named "a" or "c" or some other single-letter in math mode, where they are often accompanied by some combination of spaces, brackets, braces, super and subscripting, etc, and also other letter variables. If I just search and replace over the whole text, most matches are inside words and checking one by one takes forever; otherwise I have to think of some non-trivial regex that will avoid text words as much as possible while not missing the variable when next to others (as "abc"), that I will anyway have to double check.

The ability to search only in math mode would still return some matches with letters in math mode commands, but it'd be a couple of orders of magnitude less than in the plain text.

**Comment by sunderme** [comment]
implemented, can also filter for comment/command or verbatim aside from math
