### ISSUE TITLE
Unexpected behavior of the Cancel button of the Ref window.

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#3230]
### Environment
- TeXstudio: 4.6.2
- Qt: Qt 6.5.1
- OS: Windows 10
- TeX distribution: TeX Live 2023

### Actual behavior
Do the following steps:

1. `File / New`
2.  `LaTeX / Cross References / ref`
3. `Cancel`

TXS inserts the following at the cursor:
`\ref{}`

### Expected behavior
Nothing happens.

**Comment by octaeder** [comment]
so a solution could be:
* ok button inserts \ref with label
* a new button inserts emtpy \ref
* cancel button inserts nothing

**Comment by sunderme** [comment]
@octaeder yes, or an extra entry in the drop-down list which inserts empty `\ref{}`

**Comment by octaeder** [comment]
I thought that choosing an extra entry might be tricky. Obviously it should be the first entry then. And since it is a list of label names the entry should be empty. But at first it looks like you have no labels:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/925ff1ee-b47e-4a92-b0c9-3c23317bc325)

On the right dialog when no labels are present. No visual difference.

**Comment by sunderme** [comment]
probably better to have something like `<empty>` or similar

**Comment by octaeder** [comment]
PR #3240 is on the way. Same details as given in the PR:

Note: When the dialog is presented you can immediately (at least on windows)

- scroll through the list with the up/down arrow keys
- open the list with Alt+down arrow key (image to the right)
- insert `\ref{}` by pressing Enter or clicking OK button

![image](https://github.com/texstudio-org/texstudio/assets/102688820/53958e14-3b01-46e8-bb0f-ab7af556cdca)
