### ISSUE TITLE
Selecting "Search Results" tab from Messages / Log file part leads to hidden tabs

### ISSUE THREAD

**Issue by jacobitz** [texstudio-org/texstudio#3298]
When selecting the tab "Search Results"  tab from Messages / Log file part (or also when the search function is called from the Tex document), the other tabs (Messages, Log and Preview in my case) are hidden.

### Environment
- TeXstudio: 4.6.2
- Qt: 6.5.1
- OS: Windows 7
- TeX distribution: miktex

### Expected behavior
The other tabs should not disappear.

### Actual behavior
Before I select the tab, it looks like this:
![start](https://github.com/texstudio-org/texstudio/assets/33665164/2bc1c55b-8ea3-41cb-99cf-b7df5b43c12b)

After that like this:
![search_result](https://github.com/texstudio-org/texstudio/assets/33665164/c4b0f36b-3ecc-444d-94f1-810289996b00)

### How to reproduce
Selecting the "Search Results"  tab from Messages / Log file part or search for a lable reference from the text.

**Comment by sunderme** [comment]
not reproducible
Probably win7 issue, which is end-of-life.

**Comment by octaeder** [comment]
Quick alert: This is a current issue. Please reopen.
Win10
current build TeXstudio 4.7.0 (git 4.7.0alpha2-5-ga73027a66)
Using Qt Version 6.5.1, compiled with Qt 6.5.1 R

I try to figure out details. But I think a simple search over project has this effect.

**Comment by octaeder** [comment]
Select a word, press ctrl+f, press `+` button for extended search. In simple cases this doesn't produce the error. It seems that a random search result is needed where file names are missing or the results may not be sorted correctly:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/82e37637-bcca-41aa-ae3b-afb14a8126f6)

**Comment by octaeder** [comment]
@sunderme Any simple document can serve as an example. Can you reproduce with following hints?

If the tabs have disappeared use following workaround: Close message pane and reopen it. Then all tabs reappear.
After this to recreate the issue you need to activate a tab other than the search results tab, then press the extended search button again.

This issue seems not to be related to the sort problem mentioned in my previous comment. That's rather another issue.
