### ISSUE TITLE
Screen glitching in WSL2

### ISSUE THREAD

**Issue by psymbio** [texstudio-org/texstudio#3391]
Screen glitching in WSL2
### Environment
- TeXstudio: 4.6.3
- Qt: 5.12.8
- OS: WSL2
- TeX distribution: texlive

### Expected behavior
For the screen not to glitch.

### Actual behavior
![image](https://github.com/texstudio-org/texstudio/assets/46052244/af9c7672-eb21-425b-9800-8219661b5db5)

### How to reproduce
Not sure.

**Comment by Lyeebn** [comment]
I have a similar problem that the UI crush, I guess it happens when crossing resolution ratio.
It happens when I have more than one monitor, and they differ in resolution ratio.  
- Bug Env:  【1920*1080/ 15inch】 + 【2560*1440/ 27 inch】
	* The UI works fine on the Moniter where it launched, and broken on another Moniter. vice verse.
	* When TeXstuido window cross monitor, the UI  broken and be fine,  broken and be fine.
- Normal Env:   【1920*1080/ 24inch】 + 【1080*1920 (Vertical) / 22 inch】
	* It works fine anyway TeXstuido window cross monitors

It's stranges that, the bug disappear itself recently (My TeXstudio did not get updated), Maybe a resule of Windows Update.
@sunderme

**Comment by sunderme** [comment]
txs sees only the windows system which is provided by WSL2. So, graphical glitches are rather caused by wsl and are hence fixed by its updates.
