### ISSUE TITLE
The latest 4.7.3 on Windows hangs while loading a large project

### ISSUE THREAD

**Issue by andrzej-odyniec** [texstudio-org/texstudio#3556]
The latest 4.7.3 on Windows hangs while loading a large project. After the update, the main file name is in the window header, subsequent files do not open, CPU utilization is almost 3% (that is, 100% of one thread, because I have 18 cores and 36 threads). After fifteen minutes, no progress. The problem is solved only by returning to version 4.6.3.

**Comment by sunderme** [comment]
then you need to provide the documents (directly sunderme@gmx.de) or a stripped down version which shows that issue.

**Comment by andrzej-odyniec** [comment]
I don't know how I could document this more. Program hangs are always very difficult to diagnose and document. My sources are a non-profit open source project. It is published in ZIP http://spiewnik.andrzej.odyniec.info/SpiewnikNeokatechumenalnySrc.zip and the main file of the project is called SP.tex, but I did not try to open the file from scratch, because after updating TeXStudio it hangs.
I can also ignore the prompt to update to the next 4.7.x and check every few versions to see if it will work. And if not, then reinstall 4.6.3

**Comment by sunderme** [comment]
the problem is the line `\ifalpha\usepackage{embedfile}\else\ifsp\usepackage{embedfile}\fi\fi` 
txs does not understand `\if..` constructions and it sees `\usepackage{embedfile}` twice.
The current logic assumes that is a maximum of one defintion of a package per line and gets confused by the second occurence whether it already has handled it.
Short term solution, split the line so only one \usepackage appears per line.

**Comment by sunderme** [comment]
fixed in dev build

**Comment by andrzej-odyniec** [comment]
Congratulations on the quick and efficient diagnosis. True mastery.
