### ISSUE TITLE
Titles syntax is not highlighting how it is configured. Worked before, but not now.

### ISSUE THREAD

**Issue by yuliyasinke23** [texstudio-org/texstudio#3797]
### Environment
-TeXstudio 4.1.2 (git 4.1.2)
- Qt: 
- OS: Windows 10 Education, 22H2
- TeX distribution: 

### Actual behavior: All of a sudden they show as a normal text, which makes it harder to navigate. Once you press space inside the title, it turns bold - as expected. But I can not press every title to fix it like this. 
![Configure texstudio settings](https://github.com/user-attachments/assets/bab602a2-da84-48b6-8664-70e760568d95)
![Title bug fixed by space](https://github.com/user-attachments/assets/b66c8842-658b-41cf-8479-c53f68c6fc03)
![Title bug](https://github.com/user-attachments/assets/67df87da-6bf3-4354-a11a-ccb5e175e28d)

**Comment by sunderme** [comment]
my guess is that you are using a package which also defines `\paragraph` and a cwl was automatically generated which messes with the default definition. Take a look at `%APPDATA%\texstudio\completion\autogenerated`

Otherwise you are using an obsolete version of txs and no further assistance can be given.
