### ISSUE TITLE
Go to source

### ISSUE THREAD

**Issue by VKing0307** [texstudio-org/texstudio#3819]
Please, I can't use "Go to source". The "Go to source" button disappears when I right-click like before.

**Comment by sunderme** [comment]
There should have been a issue template to ask for basic information.
Please start again and fill out the required information.

**Comment by octaeder** [comment]
@VKing0307 A new bug report looks as follows. Version of texstudio (txs) and Qt can be found in the About dialog (s. help menu of txs). A screenshot showing the problem can simply be cut and pasted into an issue comment - recommended. Describe in detail what you do.



### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior


### Actual behavior


### How to reproduce
