### ISSUE TITLE
"texstudio" not opened for MAC

### ISSUE THREAD

**Issue by nyeong13** [texstudio-org/texstudio#3836]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Since I have updated to Sequoia, texstudio cannot be opened with this message:
"Apple could not verify texstudio is free of malware that may harm your Mac or compromise your privacy"

Could you please help me out how to solve this issue?

### Actual behavior

<img width="372" alt="image" src="https://github.com/user-attachments/assets/077bf2d0-5e7a-4310-904b-8ef7a6c11fbe">

**Comment by nyeong13** [comment]
Sorry, I thought I updated the information about my use of texstudio, but it's not. My tex distribution is 4.8.4 and os is Mac intel.

**Comment by sunderme** [comment]
see texstudio.org, downlowds, how to install
"Please note: Because we do not have an Apple Developer Account, OS X may complain about an [unidentified developer](http://support.apple.com/kb/PH14369) and deny opening TXS. In that case, open the context menu on the TXS icon (Ctrl + Click) and select open."

Details may vary with the actual MAC OSX version, please google when there are open questions.

**Comment by ashutoshjangle** [comment]
Go to Privacy and Security and scroll down to the security section. There you must find something like `recently tried to open texstudio' and you can choose to `run it anyway'.
