### ISSUE TITLE
add new side panel

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#473]
Dear @Timvde 
I forked the project and I added some panel to create xy diagrams.
Is it possible to merge it on the main project so the feature could be available in official release soon?

How to proceed?

**Comment by Timvde** [comment]
Hi. I'm not sure why you mentioned me, since apart from a single patch, I have nothing to do with TeXStudio :P But to help you anyway: on your version of the repo ([here](https://github.com/tmelorc/texstudio)), you can create a pull request for the maintainer of this repository to pull your changes in. I attached a screenshot.

![screenshot_20190115_184351](https://user-images.githubusercontent.com/2463710/51198789-82ade780-18f5-11e9-9775-fb4e8e339783.png)

**Comment by tmelorc** [comment]
Oh, sorry. I tried to mention another Tim. Anyway, thanks for attention.

**Comment by timhoffm** [comment]
@tmelorc The usual way is to create a pull request (PR):

1. fork the project
2. create a branch on your fork
3. add the desired changes to the branch
4. push the branch to your fork on github
5. github detects your new branch and shows a button to create the pull request.

Once this is done, we review the PR, maybe suggest some changes, and finally merge it into our master branch.
