### ISSUE TITLE
let tex compilers run in a shell with TERM settings

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#483]
I think the 
`shell-escape and “tput: No value for $TERM and no -T specified”`
report in 
https://tex.stackexchange.com/questions/466520/shell-escape-and-tput-no-value-for-term-and-no-t-specified
could be fixed, if TXS runs the compiler in a shell with TERM environment.

`shell-escape and “tput: No value for $TERM and no -T specified”` appears, if I start TeXstudio directly in X11 via menu or `application finder`. The problem does not show up, if I run `> texstudio &` in a `xterm` session in X11 with a bash environment.
I think there are two solutions. Either fix the way TeXstudio calls the tools, or try a dirty workaround in the `.desktop` files. I would prefer the first solution, because I am not sure about side effects for other users, if we change the `.desktop` files in a distribution.

**Comment by sunderme** [comment]
you could define the command like `sh latex ...`

**Comment by Dagefoerde** [comment]
nope, doesn't work. I prepended the lualatex command line with `sh`, hoping for the error to be resolved. Alternatively , tried putting `sh -c '<original lualatex command>'. Neither works; it's just different errors that come op. Please reopen this issue or point to a different issue where this is discussed.

Also, I tried changing the `texstudio.desktop` file, but putting the TERM env into `Exec=` doesn't work either.

Ubuntu 18.04.3 here...

**Comment by muzimuzhi** [comment]
Does https://github.com/texstudio-org/texstudio/issues/768#issuecomment-555606995 relate current issue?

**Comment by j-rahman** [comment]
Why is this closed? I just encountered this issue. None of the suggestions here or in the linked StackExchange answer solve it. I can replicate this with the following command saved in the GUI settings.
`sh -c "export TERM=xterm-256color & lualatex -shell-escape -synctex=1 -interaction=nonstopmode %.tex"`

**Software Version:** TeXstudio 3.1.2 (git 3.1.2) Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
**Operating System:** macOS Big Sur 11.5.2

**Comment by padames** [comment]
This issue is still happening in Ubuntu 24.04 and TexStudio 4.8.5 Using Qt Version 5.15.13, compiled with Qt 5.15.13 R
I wonder if there is a way to call lualatex or pdflatex from TXS in a shell where the TERM variable can be set to its value. In my login shell it is "xterm-256color". 

When I try to configure TeXstudio (TXS) to  do it by running `tput -T "xterm-256color"` followed by
`lualatex -synctex=1 -interaction=nonstopmode --shell-escape %.tex`, I get:

```
Process started: tput -T "xterm-256color"

Usage: tput [options] [command] Options: -S << read commands from standard input -T TERM use this instead of $TERM -V print curses-version -v verbose, show warnings -x do not try to clear scrollback Commands: clear clear the screen init initialize the terminal reset reinitialize the terminal capname unlike clear/init/reset, print value for capability "capname"
Process exited with error(s)


Process started: lualatex -synctex=1 -interaction=nonstopmode --shell-escape "Rust-log".tex

tput: No value for $TERM and no -T specified
Process exited normally
  
```

And the reason might be that the shell where TXS runs `tput` is not the same as where it runs `lualatex`. Is there a real drawback to this. How reliant is lulatex on tput? I assume not much since most of the output is captured by TXS in the Messages and Log panels. 
Any ideas where to start looking into a fix for this seemingly minor error?
