### ISSUE TITLE
Collapsing beamer frames does not end with \end{frame}

### ISSUE THREAD

**Issue by gbacco5** [texstudio-org/texstudio#546]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10)
- TeX distribution: texlive

### Expected behavior
The collapsed frame should start with environment \begin and end with the corresponding \end, like every other environment.

### Actual behavior
The collapsed frame continues until the next \begin{frame} is encountered, or some other environment. The expected behavior works only with the first frame.

**Comment by timhoffm** [comment]
IIRC this has to do with the fact that we interpret `\begin{frame}` as a section start rather than an environment c.f. `\begin{frame}{title}#L7` in `latex-beamer.cwl`. Interestingly, the title does not show up in the list of sections, so there's something broken here as well.

As a workaround, you can revert that behavior by copying `latex-beamer.cwl`. to `compeltion/user` in the settings directory and removing the `#L7` suffix.

**Comment by gbacco5** [comment]
Thank you very much for the answer.  
I could not find `latex-beamer.cwl` in my system, and I found the line you were referring to in `class-beamer.cwl` here on GitHub in `texstudio/completion`.  
Then I followed your instructions for the workaround and it worked flawlessly.
