### ISSUE TITLE
(question) can't make tooltip on text not to show 

### ISSUE THREAD

**Issue by ghost** [texstudio-org/texstudio#557]
### Environment
- TeXstudio: 2.12.14
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
I uncheck "Show help as tooltip on text in editor." and I want to hide tooltip.
![스크린샷(6)](https://user-images.githubusercontent.com/49466310/55849638-5e784480-5b8c-11e9-9ec0-5d3987cda149.png)

### Actual behavior
However tooltip works continually.
![스크린샷(7)](https://user-images.githubusercontent.com/49466310/55849647-646e2580-5b8c-11e9-977f-a91dcd5533ad.png)

**Comment by dbitouze** [comment]
Aside remark that would fix this issue: you could (and IMHO should in order to separate style and content) define a personal macro, say `\important` defined as:
```latex
\newcommand{\important}[1]{\textbf{#1}}
```
and use `\important{...}` instead of  `\textbf{...}` each time you want to highlight something important.

BTW, if you change your mind subsequently and want to highlight important concepts, not with bold face, but with, say, italic, it is just a matter of a single place change: the definition of `\important` (BTW as `\newcommand{\important}[1]{\emph{#1}}` rather than `\newcommand{\important}[1]{\textit{#1}}`).

**Comment by sunderme** [comment]
on linux, disabling "Show help as tooltip on text in editor" works as it should.

**Comment by sunderme** [comment]
probably obsolete
