### ISSUE TITLE
macOS jump to next placeholder shortcuts

### ISSUE THREAD

**Issue by RoadToDream** [texstudio-org/texstudio#564]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.11.2
- OS: macOS 10.14.4
- TeX distribution: texlive

### Expected behavior
Hit tab and jump to the next placeholder

### Actual behavior
just entered a tab

**Comment by muzimuzhi** [comment]
You can configure the "Move to the next placeholder" shortcuts yourself.

![image](https://user-images.githubusercontent.com/6376638/56588063-3e796400-6615-11e9-9cea-56326eeada8f.png)

![image](https://user-images.githubusercontent.com/6376638/56588115-581aab80-6615-11e9-9fe2-f06e2e814695.png)

**Comment by RoadToDream** [comment]
@muzimuzhi Yes I could, but tab is always the best solution. Could there be any fix on it?

**Comment by muzimuzhi** [comment]
So your requirement is, wanting texstudio to change the default shortcuts of "Next placeholder" (and its relatives) at least for macOS?

And I wonder, if tab is set to the shortcut of "Next placeholder" by default, then how to type in the real tab symbol (could be soft tab, i.e. spaces, by user config)?

**Comment by sunderme** [comment]
first of all, we are not changing the keyboard defaults unless there are compelling reasons (platform traditions)
So, the use can change whatever he wants to "tab", I don't understand what the problem is here ?

**Comment by RoadToDream** [comment]
@muzimuzhi 
1. No, I don't what the developer team change the default settings. 
2. If the cursor is located in placeholder, then tab is occupied by the "Next placeholder" shortcuts. Maybe I didn't express clearly, vim's ultisnips extension will reserve some placeholders and you can jump to the next placeholder once you have finished the current one.

**Comment by RoadToDream** [comment]
@sunderme TeXstudio is absolutely the best tex editor of course, and I am not asking for a change of the shortcut. It is just that "tab" cannot be recognized as any shortcuts, at least it is not responding on macOS. 
There are two ways to manually change the shortcuts:
1. typing the shortcut after the command in the preference page(pressing "tab" is only let you jump to the next command)
2. selecting the shortcut from the pre-compiled list(after setting "tab" as the shortcut of jump to the next placeholder, typing tab in a placeholder will only input a tab, but not jump to the next placeholder)
If I have set shortcut to some other like option-W, it works fine. Problem happens only on "tab".

**Comment by RoadToDream** [comment]
@muzimuzhi @sunderme I'll check if there are some conflicts of my settings, thanks for your replies and patience.

**Comment by muzimuzhi** [comment]
To set "tab" as the shortcut of "Next placeholder", you should
1. type in letters "t-a-b", instead of pressing key "tab" (see the very beginning of the picture)
1. delete other occurrences of "tab" used as shortcut, here is "Tab or Indent selection" (see the very end of the picture)

If you skip the step 2, the result of step 1 will not been saved by texstudio. Hence when you re-open the preference window, the shortcut of "Next placeholder" is still empty.

![image](https://user-images.githubusercontent.com/6376638/56902324-a07e1180-6acc-11e9-819a-63ab38f0007c.png)

@sunderme It would be better if texstudio will raise "shortcut conflict" (or more detailed) prompt when user changes shortcuts.
