### ISSUE TITLE
update poppler-data-0.4.9

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#573]
TeXstudio ships old poppler-data sources in the tree.

**Comment by manudroid19** [comment]
This is interesting. I suppose the poppler-data shipped is the one indicated in the travis conf file, not in the git utilites/poppler-data folder. 

Does newer poppler-data provide any advantage? If I get it, poppler itself is updated in every release since it is compiled in the travis build process.
[https://github.com/texstudio-org/texstudio/blob/master/travis-ci/package.sh](https://github.com/texstudio-org/texstudio/blob/master/travis-ci/package.sh)

**Comment by sunderme** [comment]
the data is basically unused. One may think about removing it.

**Comment by timhoffm** [comment]
I think the only use is that sombody who wants to compile on windows on their local machine does not need to get that data separately.

**Comment by OgreTransporter** [comment]
I always compile the current poppler version under Windows myself. poppler uses CMake, which is very fast.
