### ISSUE TITLE
Labels of listing environment

### ISSUE THREAD

**Issue by bykhov** [texstudio-org/texstudio#592]
Listing environment supports labeling in the form below:

    \begin{lstlisting}[label={lst:a}]
    Some code
    \end{lstlisting}

Currently, it cannot be auto-completed while referencing it by

    \ref{lst:a} 

and it is marked by "label missing!".

**Comment by muzimuzhi** [comment]
Q: Can texstudio recognize the `<new label>` of key-value pair `label=<new label>` appeared in the kv-list of verbatim-like environment `\begin{lstlisting}[kv-list] ... \end{lstlisting}`?

### Short version:

A: I'm afraid not.

### Long version:

There are, as far as I know now, at least 2 gaps between your requirement and the current completion file [`listings.cwl`](https://github.com/texstudio-org/texstudio/blob/master/completion/listings.cwl): (related [sections of user manual](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#CWLDESCRIPTION))

1. How to provide a specified kv-pairs for verbatim-like environment
1. How to apply the appropriate classification format to a kv-pair

Since the current code only implements `#L` classification format of a kv-pair, the gap 2 remains a gap. 
https://github.com/texstudio-org/texstudio/blob/fea0e4cf377c175206d49ae6d29fe95b3ec393a1/src/latexpackage.cpp#L773-L786

Providing a kv-pairs for non-verbatim-like environment is supported, but I am not clear if verbatim-like ones are supported or not. From another side (trying the gui, rather than reading the codes), I have not succeed in changing `.cwl` file and eliminate gap 1 yet.

**Comment by timhoffm** [comment]
Values of kw-pairs cannot be defined as labels within the current cwl format.

**Comment by sunderme** [comment]
implemented, though listings.cwl keyvalues are incomplete
