### ISSUE TITLE
Option to disable automatically jumping to the text when using find?

### ISSUE THREAD

**Issue by kendonB** [texstudio-org/texstudio#598]
I'm trying to implement a section finding feature using the voice command toolbox Caster: https://github.com/dictation-toolbox/Caster/

I'm having trouble because TexStudio automatically jumps to matching occurences before I've finished typing. It would be great if there was an option to disable that and I haven't been able to find one.

I presume OS and version info 

### Environment
- TeXstudio: 2.12.6
- OS:  Windows(10) 
- TeX distribution:  texlive

**Comment by kendonB** [comment]
It also can introduce funny behavior if you mistype what you're trying to find and end up in a different region of the doc.

**Comment by sunderme** [comment]
why is it problematic. The first match should lie before the refined match ?

**Comment by kendonB** [comment]
Say the word "bare" is right down the bottom of the document, and I'm trying to find the next occurrence of the word "barf" from the current cursor. If I type "bare" -> "backspace" -> "f", it will search for "barf" from the "bare" at the bottom of the document. I won't necessarily end up at the next occurrence of "barf".

**Comment by timhoffm** [comment]
Maybe the start position could be memorized and unless the user explicitly moves the cursor the search would always start from there? Not sure if this will have some other side effect.

The problem with not moving the cursor is that cursor and first match can be far apart so that they don't fit on the screen together. Moving to the match and having the cursor off screen is not good, you cannot start typing then and would have to place the cursor with the mouse. OTOH it doesn't make sense to stay at the cursor and not show the search match.

**Comment by sunderme** [comment]
txs jumps back to older positions if part of the search word are removed...

**Comment by kendonB** [comment]
> txs jumps back to older positions if part of the search word are removed...

I'm (now) seeing this behavior too. There was a problem but it is likely narrower than this issue claims. Closing
