### ISSUE TITLE
快捷键：ctrl+shift+u 不能使用

### ISSUE THREAD

**Issue by YLXDXX** [texstudio-org/texstudio#602]
环境：Manjaro-Deepin
描述：不能使用 ^{ } 的快捷键ctrl+shift+u，试过多种版本，AppImage也试过，软件里面均不可使用ctrl+shift+u。
其它快捷键没有问题。

不知是系统的问题还是什么冲突了，望指点一下

**Comment by sunderme** [comment]
Google translate:

Environment: Manjaro-Deepin
Description: You can't use the shortcut key ctrl+shift+u of ^{ }, tried a variety of versions, AppImage also tried, ctrl+shift+u can not be used in the software.
There are no problems with other shortcuts.

I don't know if it is a system problem or a conflict, I hope to give pointers.

**Comment by sunderme** [comment]
I would assume that it is a system problem.
You could change all short-cuts to something that works on your system.

**Comment by YLXDXX** [comment]
感谢回复，不好意思，不会英文。应该不是系统的问题，因为我在其它软件中设置相同的快捷键都可以使用，另外，按下这个快捷键后会出现一个黄色的“u”字，此时所有的快捷键都不可使用，必须删除这个黄色的“u”字才可以。


再提一个问题，texstudio 的自动补全功能和宏功能都只能在纯英文的状态下才能出发。例如：\section，若我先输入“\”，再在中文状态下输入sec，则没有自动补全的提示。使用宏的时候正则表达式的匹配也有这个问题，希望能够改进。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: sunderme <notifications@github.com>
发送时间: 2019年5月14日 00:41
收件人: texstudio-org/texstudio <texstudio@noreply.github.com>
抄送: YLXDXX <1062130072@qq.com>, Author <author@noreply.github.com>
主题: 回复：[texstudio-org/texstudio] 快捷键：ctrl+shift+u 不能使用 (#602)




I would assume that it is a system problem.
 You could change all short-cuts to something that works on your system.

**Comment by sunderme** [comment]
I would guess that the language entry method (chinese) inteferes. No way for us to debug that, though...

**Comment by muzimuzhi** [comment]
@YLXDXX 

> 描述：不能使用 ^{ } 的快捷键ctrl+shift+u，试过多种版本，AppImage也试过，软件里面均不可使用ctrl+shift+u。

通过菜单 `Math - Superscript` 可以输入 `^{}` 吗？
Can you typein `^{}` by selecting the menu item `Math - Superscript`?

![image](https://user-images.githubusercontent.com/6376638/57736057-3e7ef800-76d9-11e9-80fb-d1e2cd13ec12.png)

配置窗口里显示的 `Math - Superscript` 的快捷键是什么？如果把它修改为其他组合键（尽量选生僻的以防止快捷键冲突），新设的快捷键能否生效？（因为默认的快捷键可能和操作系统或其他已打开软件的快捷键冲突）
In the configuration window, what is the current shortcut of `Math - Superscript`? If you change the current shortcut to a new and rarely used key-combination, would the new shortcut take effect? (Since the current shortcut may be conflict with the shortcut used by OS or other opened softwares)
![image](https://user-images.githubusercontent.com/6376638/57736127-77b76800-76d9-11e9-9583-61c8160768fa.png)

最后，这个项目的主要维护人员，都不是中文使用者，英语是更为接受的交流方式。如果不能使用英语，更推荐的做法是，在发帖和回帖时主动贴上机翻的英文。
BTW, none of the core maintainers of this project speaks Chinese, hence English is the more accepted language. if you cannot use English directly, pasting the machine-translated English along with your original Chinese text when opening or commenting issues would be a better manner.

**Comment by muzimuzhi** [comment]
@YLXDXX 
> 再提一个问题，texstudio 的自动补全功能和宏功能都只能在纯英文的状态下才能出发（应为触发）。例如：\section，若我先输入“\”，再在中文状态下输入sec，则没有自动补全的提示。使用宏的时候正则表达式的匹配也有这个问题，希望能够改进。

与原始问题无关的新问题，最好在新 issue 里提问，而非在评论里追问。
To ask a new question, and a question hardly related to the original one, it is recommended to open a new issue, rather than commenting below the old issue.

你预期的行为，LeTeX 的其他编辑器，或一般编程语言的编辑器或 IDE 里，是支持的吗？
Do other editors of LaTeX, and editors and IDEs of general programming languages ever support the requirement you mentioned?

**Comment by YLXDXX** [comment]
好的，谢谢，以后问问题会注意相关形式。


快捷键那个通过菜单是可以输入的，设置成其它的快捷键也可以输入，关于快捷键的冲突问题，我特意在系统里面设置了相同的快捷键“Cr+Sh+u”测试，是可以正常使用，就是不知道为啥在这个软件里面就没法使用了。
另外关于命令自动补全的问题，在使用vim或者sublime时候都可以在中英混输的情况下实现。

------------------ 原始邮件 ------------------
发件人: muzimuzhi <notifications@github.com>
发送时间: 2019年5月15日 07:03
收件人: texstudio-org/texstudio <texstudio@noreply.github.com>
抄送: YLXDXX <1062130072@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[texstudio-org/texstudio] 快捷键：ctrl+shift+u 不能使用 (#602)




@YLXDXX
  
再提一个问题，texstudio 的自动补全功能和宏功能都只能在纯英文的状态下才能出发（应为触发）。例如：\section，若我先输入“\”，再在中文状态下输入sec，则没有自动补全的提示。使用宏的时候正则表达式的匹配也有这个问题，希望能够改进。
  
与原始问题无关的新问题，最好在新 issue 里提问，而非在评论里追问。
 To ask a new question, and a question hardly related to the original one, it is recommended to open a new issue, rather than commenting below the old issue.
 
你预期的行为，LeTeX 的其他编辑器，或一般编程语言的编辑器或 IDE 里，是支持的吗？
 Do other editors of LaTeX, and editors and IDEs of general programming languages ever support the requirement you mentioned?

**Comment by muzimuzhi** [comment]
> 我特意在系统里面设置了相同的快捷键“Cr+Sh+u”测试，是可以正常使用
I set the shortcut `Control + Shift + u` in OS on purpose, it works all right.

这里的「正常使用」，具体指的是什么？
Here, what does the "works all right" mean? Please give more detailed descriptions.

另外，在 texstudio 的设置菜单里，你看到的对应 `Math - Superscript` 的快捷键是什么？
And, in the configuration window, what is the current shortcut of `Math - Superscript` on your computer?

**Comment by YLXDXX** [comment]
“正常使用”指的是：作为测试，我在系统的快捷键中设置了”Control + Shift + u“执行某个shell脚本，我可以正常调用相应的快捷键。Math - Superscript的快捷键原先是”Control + Shift + u“，我更换了快捷键后可以正常使用。

"Normal use" means: As a test, I set "Control + Shift + u" in the shortcut key of the system to execute a shell script, I can call the corresponding shortcut key normally. Math - Superscript's shortcut key was originally "Control + Shift + u", I can use it after changing the shortcut key.

现在确定是系统的问题或者设置的问题，具体原因未知，排查中。。。

It is now determined that the system is a problem or a problem with the setup. The specific cause is unknown and is being investigated. . .

这个issue可以关闭了

This issue can be closed

**Comment by yang-tsao** [comment]
Control + Shift + u is the shortcut for inputing unicode character in linux.
