### ISSUE TITLE
Clean up aux files misses some files

### ISSUE THREAD

**Issue by titizaki** [texstudio-org/texstudio#606]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.11.2
- OS: macOS 10.14.5
- TeX distribution: TeX Live 2019

### Expected behavior
When I clean up the aux files from the Tools menu, all files listed in the clean up dialog should be deleted.

### Actual behavior
Some files, even though they were listed in the dialog, remain after the operation.

### How to reproduce
Based on various tries:
- It never happens if the document is made of a single file.
- If it's made of several files, it never happens with the master document, only with the other files.
- It never happens with files whose names are simple ASCII (no accented letters or regional characters).

So it seems to be triggered by UTF-8 characters in file names except in the master document's name.

Thanks for your attention.

**Comment by sunderme** [comment]
please provide a concrete test case (zip of files) which demonstrates the behaviour.

**Comment by titizaki** [comment]
Thanks for your answer. Here is a very small example.

[test_cleanup.zip](https://github.com/texstudio-org/texstudio/files/3188478/test_cleanup.zip)

The behavior is slightly different from what I told you above: the .aux file for the last chapter is, in fact, not detected (it's absent from the list given in the clean up) dialog.

Even if I actively open this file in TeXstudio and relaunches the cleanup operation, the .aux file is never detected and never deleted.

Depending on the set of files I use, there can be one .aux file missed or several, but the missed files always have accented letters in their names.

**Comment by sunderme** [comment]
works fine on linux.
Can somebody test on osx ?

**Comment by muzimuzhi** [comment]
> the .aux file for the last chapter is, in fact, not detected

Yes, I can reproduce the problem @titizaki stated, under osx. My environment is the same as titizaki, excerpt for my macOS is 10.14.4.

With the example in zip file, aux file `OO4_réseaux.aux` is never detected.

![image](https://user-images.githubusercontent.com/6376638/57938773-6fd70e00-78fb-11e9-9035-a4c12c4ded4a.png)

**Comment by timhoffm** [comment]
Does `OO4_réseaux.aux` show up in "Files to delete"?

Or asked more generally: Where does it go wrong? Is the list "Files to Delete" incomplete, but all listed files are actually deleted? Or is the list correct, but not all files shown are deleted?

**Comment by muzimuzhi** [comment]
@timhoffm 
With texstudio 2.12.16 on macOS 10.14.5, the list "Files to Delete" is incomplete (`OO4_réseaux.aux` is missing from the list), and all listed files are actually deleted. 

I have tested again, this problem remains (with latest version of texstudio)

**Comment by timhoffm** [comment]
Interesting `003_interféromètre_michelson` also has non-ASCII chars, but is found.

Needs a deeper investigation.

**Comment by muzimuzhi** [comment]
Some new info:

1. The `é` in filename `003_interféromètre_michelson` is composed by normal `e` and `U+0301` ([Combining acute accent](http://www.fileformat.info/info/unicode/char/0301/index.htm)), hence the related `.aux` file can be found by texstudio.
2. The `é` in filename `OO4_réseaux` is the single character `U+00E9` ([Latin small letter e with acute](http://www.fileformat.info/info/unicode/char/e9/index.htm)).

Current propositions:
1. It seems that a `.aux` with some specific characters (e.g., some characters in Unicode block [Latin-1 Supplement](http://www.fileformat.info/info/unicode/block/latin_supplement/utf8test.htm)) in its filename could not been found by texstudio's "Clean Aux Files" function.
1. More interesting, `.aux` file with Chinese characters (obvious non-ASCII chars) in its filename could been found by texstudio.

**Comment by muzimuzhi** [comment]
@titizaki 
A quick fix: 
 - substitue the `é` character (`U+00E9`) in your `master_optique.tex` file (root file), line 18, to two characters `é` (`U+0065` and `U+0301`).

You can copy and paste that pair of characters from line 17 of your root file, or from the above line. The composed or decomposed forms look the same, but in computer they are different.

Currently, the known information is insufficiency to provide a detailed and fully demonstrated explanation. I will provide one if it is ready.

**Comment by muzimuzhi** [comment]
Here I will use terms
 - "1-char form" to represent "expressing e in acute with single char `U+00E9`", and
 - "2-char form" to represent "expressing e in acute with two chars `U+0065` and `U+0301`".

Technically, these two forms are two of four Unicode normalization forms (see [here](https://unicode.org/reports/tr15/#Norm_Forms)).

A longer explanation (compared to the quick fix):
1. Filenames shown by file system (e.g., Finder.app or just terminal; call `fsys-name`), of both `003_interféromètre_michelson.tex` and `OO4_réseaux.tex` are in 2-char form.
1. Filename provided as argument of `\include` (call `arg-name`) in `master_optique.tex` is, in 2-char form for `003*.tex`, but in 1-char form for `OO4*.tex`.
1. When compiling, LaTeX engine reads included files by the `arg-name`, and creates corresponding `<arg-name>.aux` files for each of them. 
  1. As expected, LaTeX engine uses the 2-char form `arg-name` to read `OO3*.tex` and write `OO3*.aux`.
  1. Quite surprisingly, LaTeX engine can use the 1-char form `arg-name` to read `OO4*.tex`, which has a 2-char form `fsys-name`, and write `OO4*.aux` in 1-char form.
1. In the dialog window of "Clean Aux Files", texstudio executes Qt function `QDir::entryInfoList()` to list aux files ready to be deleted. This Qt function, on macOS, returns only the 2-char-form `fsys-name`s (see this minimal example [char-in-filename.cpp.zip](https://github.com/texstudio-org/texstudio/files/3239100/char-in-filename.cpp.zip)). Hence, in our example, file `OO4*.aux` is missing from the clean-aux list.

This is not a problem caused by texstudio itself, therefore the issue can close. The problem may be traced back to either Qt or file system in macOS (called APFS), or both. (Or even LaTeX engines?) I have no idea about which level should this problem been reported to. Also, I am not sure if using 2-char form in both `fsys-name` and `arg-name` would be a practical suggestion to ordinary users of texstudio.

**Comment by titizaki** [comment]
This is extremely interesting, thank you!

I re-typed the name of the OO4*.tex file in the Finder and copy-pasted it into the include command in the master file, which effectively is your quick fix. Indeed TeXstudio was able to see the .aux file and clean it up, and it is stable after a couple of recompilations.

At they very least, this provides a simple workaround.
