### ISSUE TITLE
"Open Terminal" does not open dir of the current file on osx

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#616]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3, compiled with Qt 5.12.3 R
- OS: macOS 10.14.4
- TeX distribution: TeX Live 2019

### Expected behavior
Terminal.app is opened in directory of current opened file.

### Actual behavior
Terminal.app is opened in `$HOME` dir.

### How to reproduce
Open a tex file in texstudio, then click menu `Tools -> Open Terminal`. 

### Other info
The default behavior is not stated in [user manual](https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/usermanual_en.html), but the closed [feature-request#1215](https://sourceforge.net/p/texstudio/feature-requests/1215/) shows opening terminal in dir of current file is the expected behavior on Windows and some Linux Distribution (at least at Feb 2017).

From the source code, it seems on macOS, `Tools -> Open Terminal` only executes `open /Applications/Utilities/Terminal.app/`. (I know little about cpp nor Qt.)
https://github.com/texstudio-org/texstudio/blob/4c5f931edbb0e89c9f2556bf4d835eb348fb7682/src/utilssystem_unix.cpp#L5-L10

**Comment by timhoffm** [comment]
I cannot test the patch because I don't have access to OSX. But from what I've read [here](https://apple.stackexchange.com/questions/48855/open-terminal-app-with-directory-from-a-given-url) this should do. Can somebody with OSX please verify?

**Comment by KarlMagnusLarsson** [comment]
I have built commit ac7700defc52a9c2c68d7604118d8c0d4f114f03 
fix opening terminal in directory of file on OSX, fixes #616

I have OSX High Sierra 10.13.6.

If I start texstudio ac7700defc with an open tex source file then
tools->Open Terminal:

1) If a terminal is not already open then "tools->Open Terminal" opens a terminal in my user home directory: $HOME. If a terminal is already open, nothing new happens. The open terminal remains.
2) opens a finder file browser which points to the directory of the tex source file.

Magnus Larsson

**Comment by timhoffm** [comment]
@KarlMagnusLarsson Thanks for checking.

So, do I understand correctly, that the commit does not fix #616?

Could you please try out which command one would have to issue to Terminal to open it in a specific place (and always a new instance)? You can probably also check this by adding a user command (and for testing purposes just hard-code some path).

**Comment by KarlMagnusLarsson** [comment]
Hello Tim Hoffmann,

I do not think that issue #616 is fixed.

I added "-a" as per below and get the desired behavior, i.e. tools->Open Terminal opens an osx terminal application at the directory of the currently active Texstudio source file. If you issue multiple tools->Open Terminal, you get a new window each time. If you switch to another source file in texstudio then tools->Open will open new a terminal file for that directory. If there is an existing terminal app, already open, tools->Open Terminal still produce yet another terminal.

$ git diff
diff --git a/src/utilssystem_unix.cpp b/src/utilssystem_unix.cpp
index 940b4c4b..ff8a7cd3 100644
--- a/src/utilssystem_unix.cpp
+++ b/src/utilssystem_unix.cpp
@@ -5,7 +5,8 @@
 QString getTerminalCommand()
 {
 #ifdef Q_OS_MAC
-       QString command = "open /Applications/Utilities/Terminal.app/";
+       //      QString command = "open /Applications/Utilities/Terminal.app/";^M
+       QString command = "open -a /Applications/Utilities/Terminal.app/";^M
        return command;
 #else // Linux
        // Linux does not have a uniform way to determine the default terminal application

If I check the "open" command, I get this. I just added -a, since that seemed to be the wanted action. Fyi, "-n" did not work for me. The "-a" option does give the disireg behaviour with a new terminal, combined with the rest of the code in texstudio source, at least for me.

$ open
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-s <partial SDK name>][-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.
      -s                For -h, the SDK to use; if supplied, only SDKs whose names contain the argument value are searched.
                        Otherwise the highest versioned SDK in each platform is used.

**Comment by timhoffm** [comment]
@KarlMagnusLarsson Thanks! I've added the `-a`. Hopefully this is really fixed now.

**Comment by KarlMagnusLarsson** [comment]
Works for me.
