### ISSUE TITLE
Changing \bibliographystyle does not trigger BibTeX to run

### ISSUE THREAD

**Issue by zuphilip** [texstudio-org/texstudio#625]
I use the default values (pdflatex, bibtex) for the build process and see that BibTeX will be triggered, if I enter a new citation. So far so good. However, when I just change the `\bibliographystyle`, e.g. from `plain` to `apalike` then BibTeX will not be triggered in the build and thus I still see the citations and bibliography in the old style. Is it possible to trigger in such cases also BibTeX to run in the build process?

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Win8
- TeX distribution: miktex

**Comment by timhoffm** [comment]
We only check whether the bibtex-generated bbl file is older than the input bib files.

There is no persistent information on the configuration bibtex was run with. All we could do is track whether `\bibliographystyle` was modified in the current editor session. However, that's also not a complete solution. There may be other options that influence the bibliography. Also, that information is not available if TXS was just started. In that case, should we force a rerun of the bibliography just to be sure (which may be annoying)? Or should we leave it (risking that the bibliography is not up to date)?

There's no really safe solution to having an up-to-date bibliography other than always running bibtex.

The auto-rerun in TXS is just covering the most common case in which you need to rerun the bibliography because you edited the bib file. Trying anything more is not worth the effort.

**Comment by zuphilip** [comment]
Hm... I don't yet understand the condition when BibTeX is called. For example, it is called when the BibTeX file stays the same, but I add a new source with `\cite` (good!). However, it is not called when I delete some citations. This can lead to items in the list of references which are not anymore cited, which usually is a bad practice. @timhoffm Could this been fixed? This seems more severe for me.

> However, that's also not a complete solution. There may be other options that influence the bibliography.

Yeah, but _if_ we can trigger BibTeX to run, when bibliographystlye is changed, then we can also extend to the other similar options that influence the bibliography.

> Also, that information is not available if TXS was just started. In that case, should we force a rerun of the bibliography just to be sure (which may be annoying)? Or should we leave it (risking that the bibliography is not up to date)?

But is there a use case behind this? If I just start TXS to *continue* my previous work, then it is only important that I previously build the bibliography correctly. Thus, IMO it would be enough to just react on changes.

Technically, I could envision that besides tracking changes on the BibTeX file you may also want to track some changes to the `.aux` file, e.g. `\citation`, `\bibcite`, `\bibstyle`.

**Comment by timhoffm** [comment]
> For example, it is called when the BibTeX file stays the same, but I add a new source with \cite (good!). However, it is not called when I delete some citations.

This is the second mechanism we use to detect a need for a bibtex run. When you cite a new reference, LaTeX warns at the end of the log file:

> LaTeX Warning: There were undefined references.
> LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

That's what we do. There is no such warning when you delete a citation, so we he have no trigger for citation removal.

> Yeah, but if we can trigger BibTeX to run, when bibliographystlye is changed, then we can also extend to the other similar options that influence the bibliography.

That would have to be implemented and maintained; and to be honest, it's a lot of work for little gain. After all, how often do you change the bibliography style?

**Comment by zuphilip** [comment]
> That would have to be implemented and maintained; and to be honest, it's a lot of work for little gain. After all, how often do you change the bibliography style?

Okay, fair point. But I often also delete references and the list of references will then still falsely (and unnoticed) contain those not anymore cited references. Maybe one should work further there?

**Comment by timhoffm** [comment]
Before you finally release a document, you should anyway cleanup and do a full rebuild. That will take care of excess references. Until then, they should be too distracting. If you really want an always up-to-date document, you can disable the conditional bibtex checking and always run latex, biotechs, latex, latex.

The conditional checking is a trade off between always and never running. Due to the complexity of TeX and the multi-pass compile process it can unfortunately not be perfect. In my opinion, we‘re at the right spot here, between benefit (detecting common cases such as additions or changes to references) and effort to do so. All other cases are less frequent and would require significant additional work because we would need to track these changes ourselves and cannot simply query them from existing data.

You are welcome to dig into this and provide a pull request if you are interested. But I would warn that this will take some effort to get right.

**Comment by sunderme** [comment]
Have you tried latexmk for building ?

**Comment by zuphilip** [comment]
Thank you for the comments. Yeah, clean and build fresh looks like a command which I might use quite often then. I try to create a button for that... A PR here is above my skills:-) `latexmk` sounds interesting but then I will need to install Perl for that...
