### ISSUE TITLE
Not using system icons theme

### ISSUE THREAD

**Issue by joaopauloalbq** [texstudio-org/texstudio#654]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: Linux (Manjaro)
- TeX distribution: texlive
- My icon theme: [Breeze](https://github.com/KDE/breeze-icons)

### Expected behavior
Use system theme icons

### Actual behavior
Shows some system icons and some not (see figure below)

![Screenshot_20190705_215404](https://user-images.githubusercontent.com/9905202/60749457-c1516000-9f70-11e9-87fa-c847171ebcf8.png)

### How to reproduce
Options > Configure Texstudio > General > Use System Theme Icons

**Comment by sunderme** [comment]
well, not all symbols which are used by txs are defined by the system ...

**Comment by joaopauloalbq** [comment]
I found some icons that match on Breeze icons, could you use them?

![Screenshot_20190706_155830](https://user-images.githubusercontent.com/9905202/60760143-ef817f00-a006-11e9-8695-c8779d58eb4b.png)

Anyway thanks for the great work with Texstudio :)

**Comment by sunderme** [comment]
instead of go-next/previous forward and back is used which is defined on Humanity/Lubunut/gnome
run-build, document-preview,tab-close don't exist in these themes.
system-run looks totally different from our icon
we have more icons for text style apart from bold,italic..., see Latex/fontsstyle , so I am not keen to replace a few of them for system theme while others stay the same.

The only one I might change is "close" but I have not yet decied upon that.

**Comment by joaopauloalbq** [comment]
The "tab-close" is a symlink to "window-close"

I think they (Breeze team) used the icon names in line with the FreeDesktop.Org [Icon Naming Specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)
