### ISSUE TITLE
FR: The warning about external file change should be shorter and more intuitive

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#659]
### Environment
- TeXstudio 2.12.16 (git n/a)
Using Qt Version 5.12.3, compiled with Qt 5.12.3 R

### Expected behavior
The warning should be shorter and more intuitive.
I had to read the message several times, until I could decide between Yes and No.

Suggestion:
"The file %s was changed outside of TeXstudio.\n Reload file from harddisk?" Yes/No

### Actual behavior
![image](https://user-images.githubusercontent.com/298682/60774304-c64e1500-a112-11e9-84ae-1a0bc6b2c45f.png)

### How to reproduce
create file /tmp/test.tex
edit the file with vim, while open in TXS

**Comment by timhoffm** [comment]
I've rephrased partially. The message is indeed a bit cryptic, in particular the Undo/Redo part.

Reload discards the Undo/Redo stack, which is a little bit dangerous because the file on the disk will overwrite your current editor and you cannot go back afterwards. As of now I'd be reluctant to leave that information out.

OTOH with a bit of refactoring of the (re)load functions, it should be possible to keep the undo stack and reload on top of that. Then, reloading is safe and we don't need the additional note.

**Comment by jonasstein** [comment]
What do you think about something like 'File changed - Reload from disk?' or simply 'Reload from disk?'
in the title?
I think 'Reload from disk?' could be fine, because it the file would be the same it would not matter.

**Comment by sunderme** [comment]
Reload from disk is to little information.
I assume that the current solution is easy/informative enough
