### ISSUE TITLE
\newcommand command not recognized if defined immediately after certain \let statements

### ISSUE THREAD

**Issue by alray2569** [texstudio-org/texstudio#680]
### Environment
- TeXstudio: 2.12.14 
- Qt: 5.8.0 R
- OS: Windows 10
- TeX distribution: MikTeX

### Expected behavior
Commands defined using `\newcommand` should always be recognized thereafter.

### Actual behavior
Commands are highlighted in red if defined using `\newcommand` when immediately after a `\let` statement whose second argument is itself a command that normally takes arguments, e.g. `\textit`. Since this is used 

![image](https://user-images.githubusercontent.com/9136266/62332033-ebbd0d00-b48b-11e9-8cbf-031bd1afaed4.png)

### How to reproduce
Enter the following code into a [*]LaTeX file.
```
\makeatother
\let\example\textit
\newcommand{\demo}{Here's a demo}
\demo
```

**Comment by muzimuzhi** [comment]
From my personal trial and guess, I think the wrong highlight in your example is caused by `\let\xxx\textit`.

My personal guessing:
 - Since texstudio does not handle the syntax of `\let`, and
 - texstudio considers `\textit` should always accept an argument,
 - it seems that the `\newcommand` is eaten by `\textit`, then texstudio does not parse the `\newcommand` and add `\demo` to the list of "recognized command".
 - The above steps make texstudio highlighting the second `\demo` as "unrecognized command".

Some more examples for highlight testing:
```latex
% ok
\let\example\textit{}
\newcommand{\demo}{Here's a demo}
\demo

% ok
\let\example\itshape % or other zero-argument command
\newcommand{\demo}{Here's a demo}
\demo

% wrong
\textit % or other one-argument command that texstudio can recognize
\newcommand{\demo}{Here's a demo}
\demo

% ok
\itshape % or some other commands
\newcommand{\demo}{Here's a demo}
\demo
```

Fully highlight TeX, a Turing-complete (macro) programming language, is a non-trivial task, and is (as I think) not the main objective of texstudio. I think, maybe you have to endure some highlight mistakes that texstudio will make.

**Comment by alray2569** [comment]
That was what I figured was happening, though I'm surprised the parser cares at all about the number of arguments a command takes (except for specially treated commands like `\section` that gets colored blue, `\label` that has to get handled, and of course `\newcommand`), since `{\textit{sample}}` and `{\itshape{sample}}` seem to get treated the same by everything except autocomplete. While I'm not familiar with the code base for TS, I wouldn't expect the syntax of a `\let` statement to be too hard to parse.
