### ISSUE TITLE
The browing panel doesn't manage import

### ISSUE THREAD

**Issue by mohmss** [texstudio-org/texstudio#703]
Hi,
In older versions of txs, i used to use import and subimport command and i was able to navigate in my multiple files. But in the latest, it only manage input commands.

Am i wrong? is there a way to tell it to show in the panel the "imported" files?

Thanks

**Comment by sunderme** [comment]
import is not supported as it would require to handle filepath and filename separately

**Comment by mohmss** [comment]
Thanks for the answer.
In my 2.9.4 version, it works as seen in the screen capture : 
![Untitled](https://user-images.githubusercontent.com/54602076/63887754-c31e2980-c9dd-11e9-8462-3d1fa8233922.png)

I can't use the latest versions because of this feature disappeared. 

Actually, i have one master file with multiple sub directory for course, practice,etc

I have not found a better way to manage all the files except with the import and subimport package.

**Comment by sunderme** [comment]
no quite sure why `\include{03-Tp/CI-Tp}` is unusable ?

**Comment by mohmss** [comment]
Hi,
Actually, it works at the first level but it can't be nested. I have almost 3 levels of subdirectories.
I tried with input also but thus the compiler does'nt find the files.

**Comment by sunderme** [comment]
Should work. Import.doc explains how tex searches for the files ... Fri Aug 30 11:35:28 GMT+02:00 2019 texstudio-org/texstudio <reply@reply.github.com>: Hi, Actually, it works at the first level but it can't be nested. I have almost 3 levels of subdirectories. I tried with input also but thus the compiler does'nt find the files. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
