### ISSUE TITLE
How do I prohibit biber runs when storing the bbl file in a subdirectory?

### ISSUE THREAD

**Issue by bushfeuer** [texstudio-org/texstudio#728]
To keep my working folder clean, I configured pdflatex to store the aux files in a subdirectory with `pdflatex.exe -aux-directory=aux`.
I also configured biber to store its output to the same folder:
`biber.exe --output_directory aux`
I then added this folder to the additional search path in the "build" menu of Texstudio by adding `.\aux`.

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10 Pro x64
- TeX distribution: MikTeX

### Expected behavior
Texstudio doesn't run pdflatex and biber multiple times every time I use the "Build&View" or "Compile" commands.

### Actual behavior

Once the bbl file is not stored in the same directory as the tex files, Texstudio uses biber every time I use the "Build&View" or "Compile" commands. This is not the case when the bbl file is in the directory of the tex files. 

Is there any way to prevent the automatic execution of biber when the bbl file is in a different directory? The procedure takes quite some time compared to a single run of pdflatex...

**Comment by MeanSquaredError** [comment]
I have never used biber but looking at the source code at
https://github.com/plk/biber/blob/dev/bin/biber
more specifically line 25, GetOptions(...)
it looks like the output-directory should be specified with an extra equal sign after the option name, i.e.
`--output-directory=path\to\your\directory`
Not sure if the Perl parser really needs the equal sign or it can use space instead of it.
Also you may try specifying the absolute pathname of your output directory, so the full command line could look like this:
`biber.exe --output_directory "C:\Users\MyUser\MyDir\aux\\"`
(note the double backslash ( \\ ) at the end of the path in order to prevent the backslash from escaping the double quote ".

Overall, you can try running biber from Windows command prompt and once you are sure that it works correctly and outputs the file in the correct directory, specify it as a command in TexStudio.

**Comment by MeanSquaredError** [comment]
Sorry, ignore my previous message, it seems that the actual problem is with TexStudio and not with Biber

**Comment by MeanSquaredError** [comment]
I will try preparing a patch for that, but I have a few other patches in the queue, so it may be a week or so before it is ready.

**Comment by sunderme** [comment]
How does pdflatex find the bbl/blg files ?

**Comment by MeanSquaredError** [comment]
From the --aux-directory option it seems that the tex distribution is MikTex. I am not a MikTex user, but from the MikTex documentation it seems that --aux-directory also adds the corresponding directory to the search path, so MikTex/pdflatex should be able to find the bbl file  in the output directory.

Now, looking at the information provided it seems that the user uses -aux-directory for pdflatex instead of "--aux-directory". I am not sure if miktex/pdflatex recognizes the option with just one hyphen, but probably it recognizes both syntaxes.

**Comment by sunderme** [comment]
-aux-directory does not exist on texlive, so I can't test & develop.

**Comment by bushfeuer** [comment]
I am indeed using MikTeX.
-aux-directory seems to work, since the aux files are saved to the specified folder.

> 
> 
> Sorry, ignore my previous message, it seems that the actual problem is with TexStudio and not with Biber. It looks like the problem is in
> Texstudio::runBibliographyIfNecessary
> because it does not check for the .bbl file in the additional search path.

I suspected something like that, since the pdflatex/biber routine seems to be working, creates a .bbl file in the specified aux directory, which is also found by biber. It's just that Texstudio behaves as if there is no .bbl file present. Thank you very much for preparing a patch!

**Comment by MeanSquaredError** [comment]
I think this issue should be fixed in the latest dev snapshot available at
https://bintray.com/sunderme/texstudio/texstudio-win#files
With the new version if the biber output directory is listed in the additional search paths for logfiles, then TexStdudio will find the compiled .bbl file and will not try to compile it again.
