### ISSUE TITLE
glossaries in custom.sty

### ISSUE THREAD

**Issue by judober** [texstudio-org/texstudio#732]
I try to generate a glossary (with glossaries-extra) that I can use in different documents. Therefore, I defined a custom.sty file in user/texmf/tex/latex/custom (I also tried it without /custom) that is recognized by tex and can be used during compilation. E.g. it contains `\newglossaryentry{aLetter}{name = {a}, description = {First letter in alphabet}}`

However, texlife does not offer the autocompletion (e.g. `\gls{a`) of defined labes when custom.sty is loaded with \usepackage{custom} in the preamble. Contrary, when in define some \newglossaryentry in the preamble, they are included in the autocompletion.

I also added a custom.cwl file in AppData/Roaming/texstudio/completion/user that is a one-liner:
`#include:glossaries-extra`
This does only propagate \gls to texstudio but not the labels of the entries that are defined in custom.sty.

Is there a better way to build a glossary that is accessible from everywhere in the system? Or do I have to change the cwl-file?

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
Enter 

> \gls{

and autocompletion shows defined glossary entries.
### Actual behavior
Texstudio tells me

> Labels missing

### How to reproduce
Define glossary entries in .sty as described above. Load .sty with usepackacke{}. Use \gls in document.

**Comment by sunderme** [comment]
labels can't be stored in cwl.
You should put the definition in a tex file and load it per include into your document, so that txs can scan its content.

**Comment by ju-Julia** [comment]
Ok, this hepled my partially. But I still like to include the glossaries from a path which is relative to my home directory. E.g. by: `\loadglsentries{\string~/GLS/GLS.tex}`
However, Texstuio seems unable to follow this path in order to find the labels. Is there a work arround for this?

**Comment by dryo** [comment]
@sunderme You're right and I don't know why the OP tried it that way (and why he wrote something about texlive where it should be TeXstudio). It might be that he was desperate because the "regular" way of doing it did not work for him, and that is what @ju-Julia also notices:

If we have a file ``GLS.tex`` with lots of ``\newacronym`` or ``newglossaryentry`` inside and include it in the preamble via **``\loadglsentries{GLS.tex}``** then TeXstudio does not offer auto-completion for anything defined in ``GLS.tex`` when typing ``\gls{``.

When the file ``GLS.tex`` is included via **``\include{GLS.tex}``** or ``\input{GLS.tex}`` it works.

Is this somehow fixable as ``\loadglsentries`` seems to be the right way for glossaries according to its documentation: 

> If you like, you can put all your deﬁnitions in another ﬁle (for example, defns.tex) and load that ﬁle in the preamble using \loadglsentries with the ﬁlename as the argument.

**Comment by sunderme** [comment]
does `\loadglsentries` effectively work like `\include` or does it something different ?

**Comment by dryo** [comment]
It does a little more, but not much. It also tells glossaries to put the definitions in the optionally given glossary (there can be many). The documentation explicitly says that it's okay to put whatever you want in that file as long as it's valid in the preamble section of the document.

Here's the snippet from documentation:
![image](https://user-images.githubusercontent.com/2649898/69457169-c28ef800-0d6c-11ea-8c20-d5e34b5a8e96.png)

And here's the foot note:
![image](https://user-images.githubusercontent.com/2649898/69457204-d63a5e80-0d6c-11ea-908b-229a84bed05b.png)

So I guess it's safe to handle ``\loadglsentries[]{}`` the same way as included or input files are treated.

If this functionality was added my struggle that I have since 2015 would be over -- I never cared to write a feature request for it.

**Comment by sunderme** [comment]
txs already handles loadgslentries as input (at least with the current version)
'\string~' however is not interpreted, just use normal paths...

**Comment by dryo** [comment]
Alright, this is strange as it definitely does not work for me on the current document I'm working on.

Works:
```
%\loadglsentries{definitionen.tex}
\input{definitionen.tex}
```

Does not work:
```
\loadglsentries{definitionen.tex}
%\input{definitionen.tex}
```

I just tried making a minimal example but to my surprise it just works. If I have time I will try to find out why it works with the minimal example but not with my big document (380 kB of text).

Thanks @sunderme for your time and patience. I guess we can rest the discussion.

**Comment by ju-Julia** [comment]
> 
> 
> txs already handles loadgslentries as input (at least with the current version)
> '\string~' however is not interpreted, just use normal paths...

So, if I get you right, I cannot "teach" texstudio to use a relative path, e.g. in this case to my home directory.

This would be quite usefull when using the same files on different systems (with different usernames) though...

**Comment by sunderme** [comment]
handling of \string~ implemented for include
