### ISSUE TITLE
Need some boundaries between engine and format related cwl files

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#751]
Currently, we have had several cwl files recording engine primitives and format macros. For engine primitives,
 - original tex primitives are in `tex.cwl`
 - etex [1] add-ons are missing (Adding them is an easy task when boundaries are drawn.)
 - pdftex add-ons are in `latex-dev.cwl`
 - xetex and luatex add-ons are in corresponding `xetex.cwl` and `luatex.cwl`

For format macros,
 - plain tex macros are mainly in `tex.cwl`, and the rest are in `latex-dev.cwl`
 - latex2e macros are in `latex-dev.cwl`, `latex-mathsymbols.cwl` and `latex-document.cwl`
 - ConTeXt macros are missing (As I guess the number of ConTeXt users is rather small.)

And the cwl files loaded by default are (as far as I understood)
https://github.com/texstudio-org/texstudio/blob/3e9181d8421bbdf5daf023c79161e2af9d95025e/src/configmanager.cpp#L905-L906

My suggestion:
 - Primitives
   - Add etex add-ons as `etex.cwl`.
   - Move pdftex add-ons from `latex-dev.cwl` to new file `pdftex.cwl`.
   - If texstudio can be enhanced to load different engine cwl, for example, according to the current default compiler (`txs:///compiler`), load the corresponding cwl file. If not (yet), load `pdftex.cwl` by default.
   - Each of `pdftex.cwl`, `xetex.cwl` and `luatex.cwl` depends on `etex.cwl`. (see the note [1])
 - Format macros
   - latex2e supports most of the plain tex macros. Move these macros to `latex-dev.cwl`; for those familiar to normal latex users (rather than package authors), move them to `latex-document.cwl` or `latex-mathsymbols.cwl`.
   - If we do need a plain tex cwl file, or in the future texstudio can auto-detect the format, add full plain tex macros as `plaintex.cwl`. PS: some (less than ten) of the plain tex macros are not supported by latex2e, see [`texdoc source2e`](http://mirrors.ctan.org/macros/latex/base/source2e.pdf), sec. 9.
    - For ConTeXt, add `context.cwl` if the similar need or auto-detection function is ready.

This issue is mainly for discussion. Once the boundaries are drawn and decisions are made, my contributions are ready to go :).
------
[1] Intro to etex engine
etex is a tex engine that brings new primitives. Popular engines like pdftex, luatex and xetex provides all the etex primitves. On the other hand, LaTeX2e format has used etex primitives since 2003 and has required etex since 2017. Also see [this blog article](https://www.texdev.net/2016/10/31/latex2e-and-e-tex/) written by one of the maintainers of latex2e.

**Comment by MeanSquaredError** [comment]
It is a good idea to have separate .cwl files for the different backends. Right now some of the pdftex primitives are missing even from latex-dev.cwl (e.g. \pdfsuppresswarningpagegroup ). So the full list of the primitives should be extracted from the source code of the corresponding backends of TexLive. I wrote a simple bash script that extracts the primitives but never got around to actually create the .cwl files mostly because as you said the .cwl files for the different backends need to be reorganized first.

**Comment by sunderme** [comment]
I would not put too much effort into this.
primitive commands are rarely used and even rarer people jump between different engines.
So, if some commands are really missed, they can be added in latex-dev or tex, but I would not go for a feature complete solution (or automatic switching) which nobody will ever make use of ... (and the ones who might want to use it, are able to use options/completion/...)

**Comment by timhoffm** [comment]
The problem with backend-specific files is primarily that you generally don't know which backend is targeted by a file. You might have some indication via magic comments, but in the extreme, a user can write a plain .tex file and either call `Tools -> Commands -> LaTeX` or `Tools -> Commands -> PdfLaTeX`.

Since the solution cannot be complete, I don't think it's worth trying to add complexity for a partial solution.

The practical way out might be to activate all the engine-specific cwls by default. Almost none of these commands are used for completion. And it's not too bad if we don't make a command as unknown but the compiler still complains.

**Comment by MeanSquaredError** [comment]
It would be nice to have all the engine-specific primitives listed, though. Right now the support for pdftex/pdflatex primitives is (sort of) patchy. I am not sure that it is worth putting them all into latex-dev.cwl, but maybe a good compromise would be to:

1. Reorganize the .cwl files based on the suggestion of @muzimuzhi 
2. Include pdftex.cwl from latex-dev.cwl. Include latex-document.cwl and/or latex-mathsymbols.cwl from the old .cwl files that contained originally the moved cwl definitions.
3. Do not make any changes to the user interface of TexStudio.

Step 1 will simplify a lot the maintenance of the .cwl files.
Step 2 will ensure backwards compatibility for the users.
Step 3 will save the developers a lot of unnecessary work.

**Comment by muzimuzhi** [comment]
> Since the solution cannot be complete, I don't think it's worth trying to add complexity for a partial solution.

> Just to clarify, at this point I don't think that we need to load dynamically engine-specific .cwl files.

I agree with you. You remind me of something that I was not considered before.

This issue begins when I found some etex primitives and latex2e commands are missing from cwl files. And when I prepared to add these missing lines to cwl file, I find myself confused at which file(s) should I put them in. The suggestion posted in the first comment is a (somewhat ideal) solution to the situation I met.

So the base questions are:
 - Where to add missing etex primitives?
 - Where to add missing latex2e commands (case 1: if they are inherited from plain tex, case 2: if not)?

It seems the partial consensus of first question is "create new `etex.cwl` and make it included by some default loaded cwl file".

**Comment by MeanSquaredError** [comment]
As long as the changes are invisible to the end user it is easy to make the changes and it doesn't make a big difference even if the definitions initially go to the wrong file since you can always move them somewhere else. So in that case the decision should be based on the ease of maintenance.

That being said I would say the missing tex primitives/commands should probably go to tex.cwl and missing latex2e commands that are not part of the original tex should go to latex2e-specific file.

**Comment by timhoffm** [comment]
Overall, the proposal by @MeanSquaredError  https://github.com/texstudio-org/texstudio/issues/751#issuecomment-545391133 sounds reasonable. :+1:

I don't think it's necessary to distinguish between tex and etex. They could all go in `tex.cwl`. But if you want to create a separate `etex.cwl` that's ok as well.

**Comment by lvjr** [comment]
>pdftex add-ons are in latex-dev.cwl

It looks strange to me. Why not move pdftex primitives to `pdftex.cwl` or `tex.cwl`? It seems several primitives starting with `\pdf` are provided by both pdftex and xetex (see [here](https://www.overleaf.com/learn/latex/TeX_primitives_listed_by_TeX_engine)).

**Comment by mbertucci47** [comment]
@lvjr I think the idea is that since most users use pdftex, completion for its primitives should be active by default. Putting them in `latex-dev.cwl` makes this the case since it is active by default, but I agree that it would be better if they were in their own `pdftex.cwl`. That way users who exclusively use xetex or luatex could uncheck `pdftex.cwl` in the settings and check `xetex.cwl` or `luatex.cwl`. As you mention, this would mean adding the shared primitives from pdftex to `xetex.cwl` and `luatex.cwl` since in the past they've simply been omitted as they're already in the default `latex-dev.cwl`.

**Comment by sunderme** [comment]
I would prefer not discuss potential changes on 4 year old, closed issues.
That is why there is a discussion category on github.
Furthermore the practical approach is that txs should recognize used commands, there is no bonus when sorting them correctly in some arbitrary category. When it can be demonstrated that the current approach leads to problems for normal users, we can discuss. Until then this is moot.
