### ISSUE TITLE
关于macOS Catalina下内嵌PDF阅读器无法显示中文

### ISSUE THREAD

**Issue by Tree12323** [texstudio-org/texstudio#760]
### 环境
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: macOS Catalina
- TeX distribution:  MacTeX

### 问题

更新完macOS Catalina，发现中文无法显示，使用控制变量法排除编译器和TeXstudio的问题，最后排查出是TeXstudio在编译器XeLatex下的内嵌pdf阅读器无法显示中文。追根究底是内嵌pdf阅读器的问题。

### 解决方案
在ctex包中加入fontset=mac，使用mac中文字库。具体详情查看ctex文档，在中文字库一节中有详细解释。
```
\documentclass{article}
\usepackage[fontset=mac]{ctex}
\begin{document}
	Goodbye, Solar system.
	再见，太阳系。
\end{document}
```

**Comment by muzimuzhi** [comment]
0. It is express your question in English.
1. Your question has nothing to do with texstudio, since it is just an editor. Hence this is not the most appropriate place for your question.
2. For problems relating pacakge `ctex`, you can open issues in https://github.com/CTeX-org/ctex-kit. For general latex questions, you can go to this Chinese forum https://github.com/CTeX-org/forum.
3. Your question may related to https://github.com/CTeX-org/ctex-kit/issues/455.

------
Chinese version
0. 最好用中文表述
1. 你的问题和 texstudio 无关，它只是个编辑器。所以你的问题不适合发在这里。
2. 与 `ctex` 宏包集有关的问题，可以发到 https://github.com/CTeX-org/ctex-kit。latex 使用中的一般性问题，可以发到 github 上的中文论坛 https://github.com/CTeX-org/forum。
3. 你的问题可能和 https://github.com/CTeX-org/ctex-kit/issues/455 有关。

**Comment by muzimuzhi** [comment]
This comment is for collecting more data to help locate the source of your problem. Since I still runs a macOS 10.14.x, I cannot test directly on my mac. (sorry)

1. Compile your example. Which fonts are embedded in the output pdf?
1. Compile the following example. Does your problem reproduce?

```latex
\documentclass{article}
\usepackage[fontset=none]{ctex}
\input{ctex-fontset-macnew.def}
\begin{document}
	Goodbye, Solar system.
	再见，太阳系。
\end{document}
```

**Comment by muzimuzhi** [comment]
@Tree12323 
Is there any further information that you can provide? (e.g. why you closed this issue, does your problem solved, what results can you get if you take the experiments I suggested in the last comment)

**Comment by Tree12323** [comment]
My problem is solved, Thanks.

2019年10月25日 上午11:48，muzimuzhi <notifications@github.com<mailto:notifications@github.com>> 写道：


@Tree12323<https://github.com/Tree12323>
Is there any further information that you can provide? (e.g. why you closed this issue, does your problem solved, what results can you get if you take the experiments I suggested in the last comment)

**Comment by zhangyuxuan321** [comment]
Sorry to bother u, I still meet a problem. There is an error below after I put in your codes(\usepackage[fontset=mac]{ctex}).

Font "FandolSong-Regular" does not contain requested(fontspec) Script "CJK".

**Comment by muzimuzhi** [comment]
@zhangyuxuan321 
1. This is a "safe" warning, see https://github.com/CTeX-org/forum/issues/34 (in Chinese).
2. TeXstudio is an editor, and your problem is something about the latex usage. Hence the bug tracker of [ctex-kit](https://github.com/CTeX-org/ctex-kit/issues) project and/or the (Chinese) community [forum](https://github.com/CTeX-org/forum/issues) is the right place to post and discuss problems like this one.
