### ISSUE TITLE
When does the cwl-auto-generating function run?

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#768]
### Environment
- TeXstudio: 2.12.16
- Qt: Using Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS: macOS 10.14.6
- TeX distribution: macTeX 2019

### Description

Under what condition does the cwl-auto-generating function run? Here are two failing examples I encountered:
 - I have used `nicematrix` package during recent weeks for several times but there is no `nicematrix.cwl` found in directory `~/.config/texstudio/completion/autogenerated`.
 - There used to be a nearly empty `tkz-euclid.cwl` in the above directory. But if I delete it and then reopen texstudio and compile a tex file using `tkz-euclid` package (and compile that file for several times), file `tkz-euclid.cwl` is never re-generated.

The most recent auto-generated cwl files are created on Oct 13, 2019, and the second recent date is Oct 10, 2019. I have checked that neither texstudio or macOS is upgraded between that two dates.

**Comment by MeanSquaredError** [comment]
The .cwl autogeneration runs when it detects new used packages. Generally it happens in two cases:
1. When you initially open a .tex file.
2. When you edit a .tex file and TXS notices that there is a line with new "usepackage" command.

The following commands are recognized as "usepackage" commands:

1. \usepackage
2. \documentclass
3. Any command that has been classified with the "u" classifier in an existing .cwl file.
4. Additionally it treats \RequirePackage and \RequirePackageWithOptions in a similar fashion (although I think that these two commands don't start the .cwl autogeneration but they are used as source of new package names during the autogeneration).

When a new "usepackage" command is typed in the editor TXS tries to load an existing .cwl file. If the .cwl file is not found then autogeneration for that .cwl starts and runs in a separate thread for up to 30 seconds.

I don't think that compiling a .tex file would trigger the .cwl autogeneration. It should start automatically when you open .tex file or when you type \usepackage{yourpackagename}

Regarding the autogeneration not running:
1. Are you using TXS built from the latest git snapshot?
2. Did you check for .cwl files with the same name in other directories, e.g.
~/.config/texstudio/completion/user/

**Comment by muzimuzhi** [comment]
Thanks for patient response.

> * Are you using TXS built from the latest git snapshot?
> * Did you check for .cwl files with the same name in other directories, e.g.
>   ~/.config/texstudio/completion/user/
Yes and yes (there is no same named cwl files).

I tried to restore the default setting of txs, and then open txs from command line (by executing `/Applications/texstudio.app/Contents/MacOS/texstudio`). After these steps the two mentioned failing examples both works (cwl files auto-generated). I am not sure if the second step is necessary, and I will try to find more related info.

**Comment by muzimuzhi** [comment]
Thanks for patient response.

> * Are you using TXS built from the latest git snapshot?
> * Did you check for .cwl files with the same name in other directories, e.g.
>   ~/.config/texstudio/completion/user/
Yes and yes (there is no same named cwl files).

I tried to restore the default setting of txs, and then open txs from command line (by executing `/Applications/texstudio.app/Contents/MacOS/texstudio`). After these steps the two mentioned failing examples both works (cwl files auto-generated). I am not sure if the second step is necessary, and I will try to find more related info.

**Comment by muzimuzhi** [comment]
After
 - uninstalling and then reinstalling txs through homebrew-cask,
 - remove directory `~/.config/texstudio`, and
 - restart my computer

It turns out opening txs through Launchpad or Spotlight both can not auto-generate cwl files, and opening txs through direct command `/Applications/texstudio.app/Contents/MacOS/texstudio` can turn the auto generation on.

**Comment by MeanSquaredError** [comment]
I don't have OSX (only Windows and Linux) but looking at the code in Texstudio::importPackage it seems that it tries to work with absolute/relative pathnames and also relies on finding kpsewhich (which later is changed to findtexmf ). So my guess is that there is something different in the environment in each case, maybe 
1. The search path is different
2. Or some other environment variable is different.
3. Or the current directory from which TXS is run is different.
So I suspect that it is actually unable to find findtexmf or tries to use some relative pathname and ends being unable to properly access some pathname.

You can try running it from command line and from command line and from Launchpad/Spotlight and in each case use the menu item "Help/Check LaTeX Installation" and then write down the contents of the debug editor window. I am sure that there will be something different between the debug text in both cases. Most likely some pathname or other variable value will be different.

**Comment by muzimuzhi** [comment]
<details>
    <summary>Diff result</summary>

```diff
diff --git a/open-from-command-line.txt b/open-from-spotlight.txt
index 7450891..1f2579d 100644
--- a/open-from-command-line.txt
+++ b/open-from-spotlight.txt
@@ -15,34 +15,18 @@ Compiled with zlib 1.2.11; using zlib 1.2.11
 Compiled with xpdf version 4.01
 
 Environment variables:
-AUTOJUMP_ERROR_PATH=/Users/xxxxxx/Library/autojump/errors.log
-AUTOJUMP_SOURCED=1
 Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.uiMBkcEUxx/Render
+COMMAND_MODE=unix2003
 DISPLAY=/private/tmp/com.apple.launchd.HjOB0RmEI2/org.macosforge.xquartz:0
 HOME=/Users/xxxxxx
-JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-13.jdk/Contents/Home
-LC_CTYPE=UTF-8
-LESS=-R
 LOGNAME=xxxxxx
-LSCOLORS=Gxfxcxdxbxegedabagacad
-OLDPWD=/Users/xxxxxx/Documents
-PAGER=less
 PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
-PWD=/Users/xxxxxx/Desktop/latex-mini-test
 SHELL=/bin/zsh
-SHLVL=1
 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.S62TigJtkL/Listeners
-TERM=xterm-256color
-TERM_PROGRAM=Apple_Terminal
-TERM_PROGRAM_VERSION=421.2
-TERM_SESSION_ID=902DE209-CC97-462D-9D40-8E9E57EA3927
 TMPDIR=/var/folders/kf/5dt5jfqd0mndm0zws6g61t8w0000gn/T/
 USER=xxxxxx
-XML_CATALOG_FILES=/usr/local/etc/xml/catalog
 XPC_FLAGS=0x0
-XPC_SERVICE_NAME=0
-ZSH=/Users/xxxxxx/.oh-my-zsh
-_=/Applications/texstudio.app/Contents/MacOS/texstudio
+XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000003.texstudio
 __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
 
 TeXstudio:
@@ -51,47 +35,47 @@ Program call: /Applications/texstudio.app/Contents/MacOS/texstudio
 Setting file: /Users/xxxxxx/.config/texstudio/texstudio.ini
 
 Command configuration in TeXstudio:
-    DviPng (dvipng): dvipng -T tight -D 120 %.dvi
-    SVN (svn): svn 
+    Default Viewer (view): txs:///view-pdf
     DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi
-    BibTeX 8-Bit (bibtex8): bibtex8 %.aux
-    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
-    LaTeX (latex) (r): latex -src -interaction=nonstopmode %.tex
-    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf
+    Makeindex (makeindex): makeindex %.idx
+    Latexmk (latexmk): latexmk -pdf -silent -synctex=1 %
     Default Glossary Tool (glossary): txs:///makeglossaries
-    External PDF Viewer (view-pdf-external): open %.pdf > /dev/null
-    DviPdf (dvipdf): dvipdf %.dvi
-    DviPs (dvips): dvips -o %.ps %.dvi
-    Metapost (metapost): mpost -interaction=nonstopmode ?me)
-    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
-    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
-    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
+    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded
     xelatex-escaped (user0): xelatex -synctex=1 -interaction=nonstopmode -8bit -shell-escape %.tex | txs:///view-pdf
+    Precompile (pre-compile): 
+    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
+    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
     Biber (biber): biber %
+    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
+    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf
     Default Compiler (compile) (r): txs:///xelatex
-    SVNADMIN (svnadmin): svnadmin 
-    Build & View (quick): txs:///compile | txs:///view
-    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
-    LuaLaTeX (lualatex) (r): lualatex -synctex=1 -interaction=nonstopmode %.tex
-    Ps2Pdf (ps2pdf): ps2pdf %.ps
     PS Viewer (view-ps): open %.ps > /dev/null
+    Build & View (quick): txs:///compile | txs:///view
     Makeglossaries (makeglossaries): makeglossaries %
-    Default Index Tool (index): txs:///makeindex
+    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
+    SVN (svn): svn 
+    Default Bibliography Tool (bibliography): txs:///bibtex
+    DviPs (dvips): dvips -o %.ps %.dvi
+    LaTeX (latex) (r): latex -src -interaction=nonstopmode %.tex
+    BibTeX 8-Bit (bibtex8): bibtex8 %.aux
+    Ps2Pdf (ps2pdf): ps2pdf %.ps
+    DviPdf (dvipdf): dvipdf %.dvi
+    LuaLaTeX (lualatex) (r): lualatex -synctex=1 -interaction=nonstopmode %.tex
+    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
     Asymptote (asy): asy ?m*.asy
-    Precompile (pre-compile): 
-    BibTeX (bibtex): bibtex %.aux
+    Metapost (metapost): mpost -interaction=nonstopmode ?me)
+    SVNADMIN (svnadmin): svnadmin 
+    Default Index Tool (index): txs:///makeindex
     XeLaTeX (xelatex) (r): xelatex -synctex=1 -interaction=nonstopmode %.tex
-    Ghostscript (gs): gs "?am.ps"
-    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
-    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode %.tex
     Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography
-    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded
+    BibTeX (bibtex): bibtex %.aux
     Texindy (texindy): texindy %.idx
+    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
     DVI Viewer (view-dvi): open %.dvi > /dev/null
-    Default Viewer (view): txs:///view-pdf
-    Default Bibliography Tool (bibliography): txs:///bibtex
-    Makeindex (makeindex): makeindex %.idx
-    Latexmk (latexmk): latexmk -pdf -silent -synctex=1 %
+    DviPng (dvipng): dvipng -T tight -D 120 %.dvi
+    Ghostscript (gs): gs "?am.ps"
+    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode %.tex
+    External PDF Viewer (view-pdf-external): open %.pdf > /dev/null
 
 Additional Search Paths:
     Command: 
```
</details>

Original output
 - [open-from-spotlight.txt](https://github.com/texstudio-org/texstudio/files/3788365/open-from-spotlight.txt)
 - [open-from-command-line.txt](https://github.com/texstudio-org/texstudio/files/3788366/open-from-command-line.txt)

**Comment by MeanSquaredError** [comment]
I don't see anything too different between the two outputs but it is not logging all the information that I would like to see. I suspect the 

Are you able to build from source custom versions of TXS for your platform? I can prepare a modified version of TXS that would log much more information through qDebug that would allow us to catch the exact culprit.

**Comment by muzimuzhi** [comment]
> Are you able to build from source custom versions of TXS for your platform?

I can (with help from friends). Much thanks.

**Comment by MeanSquaredError** [comment]
When you start TXS through Launchpad/Spotlight is it possible to set a command line option for TXS?

I want to add an extra option, e.g.
--qt-debug-file /path/to/logfile.txt
that will log all the qDebug, qWarning, etc. messages to a logfile. In order for that to work it should be possible to set a command-line option to TXS even if it is not run from the command-line.

**Comment by muzimuzhi** [comment]
> When you start TXS through Launchpad/Spotlight is it possible to set a command line option for TXS?

I am afraid not.

Q&As like
 - https://superuser.com/questions/271678/how-do-i-pass-command-line-arguments-to-dock-items and
 - https://apple.stackexchange.com/questions/8107/how-can-i-add-command-line-parameters-to-an-application-shortcut

need either opening from bash script (which contains an execution of `/Application/.../texstudio` or opening with shell command `open -a "texstudio.app" [--arg <args>]`. 

I tested opening using `open -a "texstudio.app"`, the auto-generation runs ok.

**Comment by MeanSquaredError** [comment]
Too bad I already implemented it as a command-line option :-)
Anyway, I will rework it so that it does not use the command-line and then will post the download URL here. It will take me another 3-4 days until I find the time (I also want to sort out #761 first).

**Comment by muzimuzhi** [comment]
This issue is not in a hurry, since it relates unimportant problems and there are already multiple workarounds. Thanks for your help again.

**Comment by MeanSquaredError** [comment]
OK, I created a debug version of TXS with extra logging which should help to pinpoint the issue. The source code is available in my repository, the extra-logging branch:
https://github.com/MeanSquaredError/texstudio/tree/extra-logging

When run this version automatically creates a logfile in the home directory. The logfile is called ~/texstudio_debug.log

Please build the debug version of the source and try running it first from the command line and then from Launchpad/Spotlight and then attach here the two generated files (texstudio_debug.log).

When running the debug version please follow these steps:

1. Make sure that this is not the first run because we don't want the automatic tests to interfere with the debug output. If necessary run TXS the first time so that the automatic tests would execute, then exit TXS and delete the resulting texstudio_debug.log

2. Delete any existing texstudio_debug.log which may be remaining from a previous run of TXS.

3. Delete all the automatically generated .cwl files. On Fedora Linux they are located in
~HOME/.config/texstudio/completion/autogenerated/*
In your case the exact location may vary.

4. Start TXS either from command line or from Launchpad/Spotlight.

5. Open a .tex file for which you want to test the .cwl autogeneration.

5. Wait for about 1 minute

6. Exit TXS.

6. Save the resulting $HOME/texstudio_debug.log, then remove delete it from the home directory.

Do steps 1-6 twice, once from the command-line and a second time from Launchpad/Spotlight, then please provide the resulting texstudio_debug.log files.

**Comment by dbitouze** [comment]
Context
---
- Linux Mageia 7
- Plasma 5.15.4

```bash
git clone git@github.com:MeanSquaredError/texstudio.git
cd texstudio
su
sh BUILD.sh # Default choices except /usr/lib64/qt5/ for the path to QT4/5 base directory
```

This results in TeXstudio 2.12.16 (git 2.12.16beta1-171-gb22e73f0) but:

```bash
exit
texstudio &
su
updatedb
locate texstudio_debug.log
```
returns nothing.

**Comment by MeanSquaredError** [comment]
@dbitouze Thank you for the additional testing.

Once you clone the git repository you need to switch to the extra-logging branch. So it would be something like this:

git clone https://github.com/MeanSquaredError/texstudio.git
cd texstudio
git checkout extra-logging
./BUILD.sh
...

By the way the modified version supports one extra option
`--qt-debug-file /path/to/your/logfile.log`
You should be able to see the extra option if you you run 
`texstudio --help`
If you don't see the extra option, then it is not the extra-logging branch.

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
I think the build is successful and results
```
TeXstudio 2.12.16 (git 2.12.16beta1-178-g6171abab)
```
(here `6171abab` is the id of the latest commit of your `extra-logging` branch)

But neither any log file (`~/*.log`) nor extra option (by executing `/Applications/texstudio.app/Contents/MacOS/texstudio --help`) is found. This is strangle.

Maybe use travis-ci to build and package is a solution to eliminate the differences among building.

**Comment by MeanSquaredError** [comment]
@muzimuzhi Thank you for the testing.

It seems that there is some kind of unrelated TXS issue which boils down to the fact that debug builds are broken on (some?) MacOS machines.

The first method for building that you used creates a "Release" (non-debug) build, so that is why it builds successfully. One of the main things that BUILD.sh does when building in debug mode is to run
qmake CONFIG+=debug
which effectively breaks the build because it cannot find libQt5UiTools_debug.a

It seems that in some cases virtual machine installs of macOS have similar issues with Qt. So

1. Is it a physical computer with macOS or is it a virtual machine with macOS?
2. Can you please search your filesystem for libQt5UiTools_debug.a and see if it is anywhere in your filesystem?

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
1. It is a physical computer with macOS.
2. The problem may be caused by the missing debug version of qt (from [this](https://qcad.org/rsforum/viewtopic.php?f=33&t=6061)).
I am trying to solve this, maybe with the help of my friend.

**Comment by MeanSquaredError** [comment]
OK, don't worry about it. I will modify the extra-logging version so that it will work without the Qt debug libraries. It will try to do it in the next 2-3 days.

**Comment by MeanSquaredError** [comment]
@muzimuzhi 
OK, I implemented the debugging code which can run without the Qt debug libraries. To build the debugging version please follow these steps:

`git clone https://github.com/MeanSquaredError/texstudio.git`
`cd texstudio`
`git checkout extra-logging`
`./BUILD.sh`
When BUILD.sh asks you "Do you want to build a debug or release version?" select the release version.
After that BUILD.sh will ask you "Do you want to enable the debug logger? (yes/no)". Answer "yes" to that question (the default is "no", so you will have to enter "yes" explicitly).
After building and running TXS it will create a file debug file in the home directory called ~/texstudio_debug.log

Run TXS twice, once from the command line and once from Launchpad/Spotlight. Before each run delete ~/texstudio_debug.log and also delete the auto-generated .cwl files (on Linux these are located in `~/.config/texstudio/completion/autogenerated/*` )

After the two runs of TXS please post the generated ~/texstudio_debug.log files so that I can take a look at them.

**Comment by muzimuzhi** [comment]
@MeanSquaredError 

 - [open-from-spotlight.log](https://github.com/texstudio-org/texstudio/files/3854095/open-from-spotlight.log)
 - [open-from-command-line.log](https://github.com/texstudio-org/texstudio/files/3854096/open-from-command-line.log)

It seems the difference begins at
```
open-from-spotlight
 - LatexStyleParser: texdefMode: 0
 - LatexStyleParser: full dequeued pathname: ""
open-from-command-line
 - LatexStyleParser: texdefMode: 1
 - LatexStyleParser: dequeued file: "#tkz-base.sty//Users/xxxxx/path/to/dir"
```
I spot another difference:
 - When texstudio is opened from spotlight and is kept open, the file `~/texstudio_debug.log` is created but empty. File contents are written when texstudio is closing.
 - When texstudio is opened from command line and is kept open, the extra log file is created, non-empty, and non-complete. File contents are completed after texstudio is closed.

**Comment by MeanSquaredError** [comment]
OK, I think we have it figured out. Basically it is unable to find pdflatex and kpsewhich commands because these commands are run without any path prefix (just the command basename) and their successful execution depends on the system path that the TXS executable sees. This is the relevant code:
`	texdefDir = kpsecmd.left(kpsecmd.length() - 9);`
`	QProcess myProc(nullptr);`
`	//myProc.start(texdefDir+"texdef");`
`	myProc.start(texdefDir + "pdflatex --version");`
`	myProc.waitForFinished();`
`	texdefMode = (myProc.exitCode() == 0);`
`	LOG_DEBUG(QString("LatexStyleParser: texdefMode: %1").arg(texdefMode));`

I will try to prepare a proper fix in the next couple of days.

**Comment by muzimuzhi** [comment]
To my curiosity, does the problem (both from outer user experience and from inner source code reader) reported in this issue only reproducible under macOS?

**Comment by MeanSquaredError** [comment]
After looking at the code I would say that this issue can happen on any platform/OS where pdflatex is not in the system search path of the texstudio binary. That is when the texstudio binary is run the calling process (shell or desktop manager) passes some kind of search path environment variable to texstudio. If pdflatex and kpsewhich are not in that search path, then cwl autogeneration will fail.

So on any OS if you pass a severely limited search path to texstudio its cwl autogeneration will not work properly.

**Comment by MeanSquaredError** [comment]
@muzimuzhi 
I started looking for a way to fix the issue with cwl autogeneration and I have a couple of questions:

1. Does the TXS Build&View command run correctly when TXS is run from Spotlight ?

2. If Build&View runs correctly are you using some kind of custom commands for Build&View?
Can you please post the following settings:

Options / Configure TeXstudio / Commands / PdfLaTeX
Options / Configure TeXstudio / Build / Build & View
Options / Configure TeXstudio / Build / Default Compiler
The settings for any custom commands used by Build & View
The settings for any custom commands used by Default Compiler
Options / Configure TeXstudio / Build / Additional Search Paths / Commands ($PATH)

**Comment by muzimuzhi** [comment]
@MeanSquaredError 

> 1. Does the TXS Build&View command run correctly when TXS is run from Spotlight ?

Yes.

> 2. If Build&View runs correctly are you using some kind of custom commands for Build&View?

Probably No.

> 3. Can you please post the following settings:

```
>    Options / Configure TeXstudio / Commands / PdfLaTeX
pdflatex -synctex=1 -interaction=nonstopmode %.tex

>    Options / Configure TeXstudio / Build / Build & View
txs:///compile | txs:///view

>    Options / Configure TeXstudio / Build / Default Compiler
txs:///xelatex
Also, Options / Configure TeXstudio / Commands / XeLaTeX
xelatex -synctex=1 -interaction=nonstopmode %.tex

>    The settings for any custom commands used by Build & View
>    The settings for any custom commands used by Default Compiler
>    Options / Configure TeXstudio / Build / Additional Search Paths / Commands ($PATH)
EMPTY
```

------

For more complete settings, here is my current txs profile, with some sensitive entries substituted by `MANUALLY DELETED`: [muzimuzhi-macos.txt](https://github.com/texstudio-org/texstudio/files/3855690/muzimuzhi-macos.txt)

PS: Github supports a limited list of file extension, hence I use `.txt` insteaded of `.texprofile`.

**Comment by MeanSquaredError** [comment]
@muzimuzhi 

Thank you for providing the settings. The lack of "Additional search paths" is a bit surprising to me because I was expecting that you have some paths there and that these extra paths allowed TXS to run the external compile program even when TXS is run from Spotlight (I thought that in that case it does not have the proper system path and relied on Additional search paths).

So I have added a bit of extra logging information to the extra-logging branch in my repository. Please build it and run TXS from the command line and Spotlight again. After opening a sample .tex file please give some time for the .cwl autogeneration to run and then run a build&view command too, because I want to see why TXS is able to find xelatex even when it runs from Spotlight without proper system path.

So to build TXS please do
`git clone https://github.com/MeanSquaredError/texstudio.git`
`cd texstudio`
`git checkout extra-logging`
`./BUILD.sh`
(choose "yes" when it asks "Do you want to enable the debug logger? (yes/no)")
After building TXS run it once to let the automatic tests to run, then close TXS and delete the resulting ~/texstudio_debug.log and the autogenerated .cwl files. We don't need the debug output from the automatic tests.

Run TXS twice, once from the command line and once from Launchpad/Spotlight. When running TXS do the following:

1. Delete ~/texstudio_debug.log
2. Delete the auto-generated .cwl files (on Linux these are located in ~/.config/texstudio/completion/autogenerated/* )
3. Start TXS from the command line or from Launchpad/Spotlight.
4. Open your test file.
5. Wait for about 30 seconds to give time to the latexstyleparser to auto-generate the .cwl files.
6. Run the build&view command.
7. Exit TXS.
6. Save the resulting texstudio_debug.log

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
 - [open_from_spotlight.log](https://github.com/texstudio-org/texstudio/files/3864442/open_from_spotlight.log)
 - [open_from_teminal.log](https://github.com/texstudio-org/texstudio/files/3864445/open_from_teminal.log)

**Comment by MeanSquaredError** [comment]
@muzimuzhi 

Thank you for the additional debug logs. Now we have the full picture.

For the txs:/// commands TXS uses all of the following to build the search path:
- The system path ($PATH variable that TXS inherited from the program that started it, can be shell, Spotlight, etc.).
- The "Additional search path" from TXS configuration.
- On macOS it also uses the path as seen by bash (effectively it starts bash and does "echo -n $PATH" to get that path). Most likely there are some startup scripts that are run by bash on its startup and that add additional directories to the search path. In this case they add /usr/local/bin, etc.

For .cwl autogeneration it starts pdflatex but it only uses the first two (system $PATH and "Additional search path"). 

So if TXS is started with severely limited system path (like it is when it is started by Spotlight) the txs:/// commands may still work because they will use the extra search paths added by bash startup scripts while .cwl autogeneration will not use these extra search paths and will fail.

In your case the system path when started from Spotlight is 
`/usr/bin:/bin:/usr/sbin:/sbin`
while the bash system path is
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`
So txs:/// commands are able to find xelatex while the .cwl autogenerating code cannot find pdflatex and fails to work.

I will prepare a patch tomorrow that will fix the .cwl autogenerating code.

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
Follow your full picture, I found that mactex (the latex distribution I installed) adds extra path `/Library/TeX/texbin` to `$PATH` by a rather special way: a file `TeX` located in directory `/etc/paths.d` and containing one extra entry.
```bash
$ cat /etc/paths.d/TeX
/Library/TeX/texbin
```
ref: this [reply to post on latex.org](https://latex.org/forum/viewtopic.php?t=26726), made by joseph wright.

**Comment by MeanSquaredError** [comment]
@muzimuzhi 
Hi,
I updated the extra-logging branch in my repo by adding the code which should fix .cwl autogeneration on macOS when run from Launchpad/Spotlight.

Please download and build the extra-logging branch of TXS and let me know if it fixes the .cwl autogeneration issue.
`git clone https://github.com/MeanSquaredError/texstudio.git`
`cd texstudio`
`git checkout extra-logging`
`./BUILD.sh`

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
The extra-logging branch at commit https://github.com/MeanSquaredError/texstudio/commit/53c5f424d6d78f92200ef93398fb5b60ae745151 does not fix the problem. 

 - If opened from spotlight, apart from not auto-generating cwl files, texstudio cannot even compile tex files and returns
    ```
    Error: Could not start the command: xelatex -synctex=1 -interaction=nonstopmode "tkz-test".tex
    ```
    in (lower-left) Messages panel
    ![image](https://user-images.githubusercontent.com/6376638/69374110-55ce1c00-0ce0-11ea-9b19-1f5ed45312a7.png)

 - If opened from terminal, texstudio works alright.

logs
 - [open_from_spotlight.log](https://github.com/texstudio-org/texstudio/files/3876637/open_from_spotlight.log)
 - [open_from_terminal.log](https://github.com/texstudio-org/texstudio/files/3876639/open_from_terminal.log)

**Comment by MeanSquaredError** [comment]
@muzimuzhi 
I am sorry there was a bug and the PATH environment was not actually updated. I fixed the bug so please try downloading the `extra-logging` branch again, build it and let me know if the cwl autogeneration bug is fixed and if compiling works correctly now.

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
Build from commit https://github.com/MeanSquaredError/texstudio/commit/be3f74135d0ca00197447b72895f0fa1703a5d29, the cwl auto-generation bug is fixed. And compiling is alright.
