### ISSUE TITLE
Redirect .PDF output

### ISSUE THREAD

**Issue by Srebby** [texstudio-org/texstudio#795]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: Mac
- TeX distribution: texlive
### Expected behavior
This is an enhancement request.  I would like to have a way to create PDF files with different names than the default.  I create tests with answers that display optionally.  I would like to be able to create one .PDF for the test with no answers, and another (from the same .tex file with just one command change) that has the answers.

Thank you for your consideration.

**Comment by MeanSquaredError** [comment]
It depends on how you differentiate between the two builds. If you differentiate them via the pdflatex command-line then I can think of one solution.

Enable "Show advanced options" for the TeXstudio configuration, then add two user commands  in
Options / Configure TeXstudio / Build / User commands
Let's say the user commands are my_build_1 and my_build_2
Each of the two build commands would invoke pdflatex with different options e.g.

pdflatex -synctex=1 -interaction=nonstopmode --jobname=%-first %.tex
pdflatex -synctex=1 -interaction=nonstopmode --jobname=%-second %.tex

If your tex file is myfile.tex, then it would create myfile-first.pdf and myfile-second.pdf

Then your Build&view command will be something like:
txs:///my_build_1 | txs:///my_build_1 | txs:///view
Of course you would have to adjust the view command too so that it would find the differently named .pdf files.

**Comment by timhoffm** [comment]
As described by @MeanSquaredError, this is reasonably supported by the build system. Additional dedicated special-casing is not needed.
