### ISSUE TITLE
Consistent and annoying crashes of texstudio

### ISSUE THREAD

**Issue by kirk86** [texstudio-org/texstudio#801]
It crashes consistently and frequently especially during pressing F5 (compile and view)

Logs:
[logs.txt](https://github.com/texstudio-org/texstudio/files/3864819/logs.txt)

### Environment
- TeXstudio: 2.12.16 ()

- Qt: 5

- OS: Linux (Manjaro)

- TeX distribution: texlive

### Expected behavior
Work reliably

### Actual behavior
Crashes alot after F5

### How to reproduce
I guess use it alot by pressing F5 :thinking:

**Comment by MeanSquaredError** [comment]
From the stack trace it seems to be crashing in libpoppler in FoFiType1::parse() 
That function seems to be trying to load some file from the disk. It seems to try to pass incorrect data to a libc function which fails on some assertion.

So my guess is that TeXstudio crashes after it has compiled the PDF and when it tries to display it in the internal viewer window.

I am not familiar with that specific part of TeXstudio that communicates with libpoppler, but I would speculate that libpoppler crashes when it tries to load one of the fonts used by your documents.

If your distribution has libpoppler version below 0.82.0 you may consider upgrading libpopper to 0.82.0 and see if that makes a difference. They say that one of the improvements in 0.82.0 is 
`Fix crashes in malformed files`

Alternatively you can try changing the fonts that you use and see if that will make a difference. Sorry if the above advice is not helpful enough.

**Comment by kirk86** [comment]
No, that was helpful. Thanks, the current version of poppler from my distro is 0.80.0-2, so I reported this on distro managers in hope of updating their pkg repos with the latest stable version.

**Comment by MeanSquaredError** [comment]
By the way are you able to get and upload somewhere a core dump (a.k.a. crash dump) of TeXstudio when it crashes. A crash dump would make debugging it much easier.

**Comment by kirk86** [comment]
Does texstudio save crash dumps in a specific location? Couldn't find anything in logs or config/texstudio?

**Comment by MeanSquaredError** [comment]
I think that TeXstudio itself does not change the OS coredump settings so whether it will dump core depends mostly on the OS (in your case Manjaro distro) settings. In most cases it means that it will dump core if:
1. ulimit settings allow core to be dumped. You can try running `ulimit -c` from the shell prompt and see if core dumps are allowed.
2. The kernel is configured to save the core dumps to a file or to pass it to a program that will save the core dump. You can try `cat /proc/sys/kernel/core_pattern` to see what it will do with the core dumps.

I am not familiar with the Manjaro distribution so I don't know how exactly it handles core dumps. You can see
https://wiki.archlinux.org/index.php/Core_dump
(for ArchLinux which seems to be similar to Manjaro)
https://radek.io/2012/02/11/core-dumps-in-fedora/
(this is for Fedora but may be useful since it gives a simple explanation)
http://man7.org/linux/man-pages/man5/core.5.html
(the generic manual page)

**Comment by sunderme** [comment]
crash in poppler from the distro
