### ISSUE TITLE
Make .cwl files be able to be updated online 

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#806]
It could be nice to make `.cwl` files be able to be updated online, independently of releases cycle. The same feature could be useful for templates.

**Comment by sunderme** [comment]
not a fan. the cwl need a certain texstudio version to understand the syntax.
e.g. old version of txs would not make use of many of the features.
And why not update txs ?

**Comment by timhoffm** [comment]
Basically a good idea. It could motivate people to contribute cwls if they can immediately re-use them from an upstream channel. If I have to wait half a year before my contribution gets back to me in a new release, I will more likely just keep a local version and not contribute at all.

The cwl format would need versioning to make sure TXS can understand a given file.

On the practical side, it would be a larger effort, and I don't see capacity for that. You would need an upstream infrastructure that can be queried efficiently by TXS, and that users can publish their changes on. On the client side, you need synchronization mechanisms. Of course, if somebody is interested to contribute here, we could talk about that.

**Comment by sunderme** [comment]
there is already a repository for macros with zero user participation. I really don‘t think that much is gained by splitting the cwl location.

**Comment by dbitouze** [comment]
> there is already a repository for macros with zero user participation.

Probably because macros require programming skills and missing them doesn't directly bother users. By contrast, missing completion and having highlighted (as faulty) commands of a daily used package is much more sensible.

**Comment by MeanSquaredError** [comment]
Maybe nice to have but getting it implemented properly is a fair amount of work.

A variation of the idea would be to have the TXS on startup automatically detect if there are any user-defined .cwl files and macros and offer the user to create automatically a github pull request or just post them automatically as an issue on github. That might require less work to implement because there would be no need to implement server-side code and code to download updates. But it would be still require time to design, implement and test properly. And then again I am not sure how easy would be to implement an automatic creation of a github pull request.

So everything boils down to whether there is someone who likes the idea a lot and has the time to implement it :-)

**Comment by dbitouze** [comment]
> A variation of the idea would be to have the TXS on startup automatically detect if there are any user-defined .cwl files and macros and offer the user to create automatically a github pull request or just post them automatically as an issue on github.

Good idea!

>Maybe nice to have but getting it implemented properly is a fair amount of work. [...]
>So everything boils down to whether there is someone who likes the idea a lot and has the time to implement it :-)

I admit you're right :)

**Comment by muzimuzhi** [comment]
Some thinking from a latex user's point of view, rather than from software developers': 
 - cwl files record mainly the user interfaces of latex packages (and engines). 
 - There are thousands of packages, of which about 100 to 200 (or, less than 500) are frequently used.
 - The whole latex ecology is relatively stable. Say, for existing frequently used packages, their interfaces are basically stable. And, new packages with good quality and helpful utilities (which are candidates of frequently used ones) appear at a rather slow speed.
 - Therefore, I think the main gap is that texstudio does not contain enough manually revised cwl files for frequently used packages. If this gap is made up (this may do some effort), to follow up their updates (in the long term) is simpler.
 - I think of this issue as "a solution to help texstudio provide more helpful and reliable cwl files", so I give the above thinking. I am slowly doing the made-up work for past months, maybe too slow.

**Comment by sunderme** [comment]
First of all, the cwl file delivered plus autogeneration does work well. We have >600k installations and very few complaints about missing packages.  

Second, there will be no autosubmit of autogenerated cwl files. I don't want to be bombarded with low quality cwls which in turn a few people correct and nobody will even notice it.

Correcting cwl files is some work,especially if you want to make use of txs syntax features. It demands some commitment but then we will help and usually add the filw to the repository.I don't see a point why this proven methodology should be changed...

**Comment by MeanSquaredError** [comment]
I was explicitly referencing the user-defined .cwl files and not the autogenerated ones (there is little benefit from autosubmitting the autogenerated ones, anyway).

Other than that I agree that any automatic submission would require a manual review which takes valuable time, so unless there is a volunteer to do that long-term there is no point in implementing any feature like that.

**Comment by dbitouze** [comment]
> Other than that I agree that any automatic submission would require a manual review which takes valuable time, so unless there is a volunteer to do that long-term there is no point in implementing any feature like that.

GitHub pull requests would not be automatic: it would require for users to have a GitHub account and to figure out how to submit pull requests. Hence I guess it would mostly filter users who would provide low quality `.cwl` files.

But, okay, let's close this issue.
