### ISSUE TITLE
Isolate LaTeX (DVI mode of pdfLaTeX) from the other LaTeX derivatives

### ISSUE THREAD

**Issue by tats-u** [texstudio-org/texstudio#81]
Blocks #69 

There are some LaTeX derivatives that can make DVI other than pdfLaTeX (so-called `latex`), so it must be contained in another command other than `compile`, for example, `compile-to-dvi`.

**Comment by sunderme** [comment]
i don't want to generate more commands, since everything is already working as it is.
the distinction between dvi/pdf is only relevant for the viewer and you can choose what viewer to use, so what benefit would extra commands have ?
The general approach right now is, anyway, to go for pdf.

**Comment by tats-u** [comment]
1. You can ban invalid chains like `txs:///latex | txs:///view-pdf` (choosing `txs:///latex` as `txs:///compile`).
2. "Compile & View" is duplicated.  Why there are PDF, DVI, and PS chains?  What's worse is that `txs:///pdflatex` is hard-coded to them and some other chains.  You can't use LuaLaTeX and XeLaTeX insted of pdfLaTeX.
3. `txs:///latex` is also frequently hard-coded in many other commands.  It must be isolated from `txs:///compile`.

There are something irrational.  There is some benefit to remove hard-code of specific tools.

P.S.
DVI is treated as an intermediate even for almost all Japanese using pLaTeX and isn't open directory by viewer because they make PDF by dvipdfmx.

P.P.S.
I wish LuaLaTeX got 10x faster and we could migrate legacy class files for (u)pLaTeX to LuaLaTeX easily.

**Comment by tats-u** [comment]
Todo to solve 2.:
- [ ] Delete "Compile & View"
- [ ] Rewite `txs:///pdflatex` in many commands to `txs:///compile`
- [ ] Set "PDF chains" as the default
- (Optionally) remove `txs:///latex` from "The default compiler" and rename it as "The default PDF compiler"

**Comment by sunderme** [comment]
the approach seems a little too dogmatic.
What you want to achieve is a chain platex/japanese bibtex&makeindex/dvipdfmx/view pdf
This can already be set using user commands. So there is no need to break everything.
To make things a little simpler, default commands/chain for platex may be defined, but there is really no need to redefine anything. Especially default settings which work fine nearly everywhere will not be touched since it probably would existing set-ups.

**Comment by tats-u** [comment]
> Especially default settings which work fine nearly everywhere

It it for almost all non-Japanese users, which don't need to use other than pdfLaTeX

> will not be touched since it probably would existing set-ups.

I think this may be because there are no means to reset specific user settings in update.  I wish it will be fixed in future.

OK, I'll remove commands for (u)pLaTeX from #69.  It might as well be the official hack to rewrite LaTeX command to what for pLaTeX if you want to it for the time being.

**Comment by sunderme** [comment]
I don't see the point. Your pull-request was fine in the way, that there more commands available and the chains could be set accordingly. What I object to is to restructure basic,established processes.

**Comment by timhoffm** [comment]
I agree, that the pre-configured build options are already too complex and we shouldn't add more.

**Comment by tats-u** [comment]
Hmm, I wonder if the build options mustn't be touched though they have some problems like hard-code of the names of compilers.
I don't think they are as complex as they supports other than PDF.

**Comment by sunderme** [comment]
what exactly would need to be changed ?

**Comment by timhoffm** [comment]
Overall, the build system is structured similar to a grammar: One command calls one or more others. Additionally, some have some implicit logic attached. This is difficult to overlook.

The pre-configured chains are meant as preconfigured standard use-cases so that the user doesn't have to configure all details of the calls himself. On the other hand. A number of chains mixed in between the other build commands adds clutter as well.

Alternative and IMO better approaches would be:
- some flowchart-like command layout
- or maybe a short javascript defining the calls
- or very maybe relying on one of the already available LaTeX build systems (basically a good interface for configuring them).

But I don't see the time for working in any of these directions.
