### ISSUE TITLE
Support docker image as LaTeX source

### ISSUE THREAD

**Issue by theexiile1305** [texstudio-org/texstudio#819]
All current installations require a locally installed LaTeX distribution.
The LaTeX distribution could be deployed inside a docker image so that it only needs to be pulled onto a computer. Texstudio only needs to support execution within the Docker Container. 

### Environment
- OS: any (Windows(7,8,10), Mac and Linux)
- TeX distribution: actual tex distribution --> like version in docker image

### Advantages:
- Installing LaTeX on a local machine is faster.
- Universally applicable, because of no dependency on a specific LaTeX distribution.
- small installation size of LaTeX.

**Comment by MeanSquaredError** [comment]
The dependency on the Latex version will remain, even though Latex will be wrapped in a docker image. Also I am not sure if the size of the docker image will be smaller than the size of the Latex distribution.

So IMHO the only real advantage is faster (and maybe simpler) installation of Latex . In that case it is probably easier to bundle Texstudio with Latex in the docker image.

**Comment by theexiile1305** [comment]
I currently writing some stuff in LaTeX in Visual Studio Code or Texstudio. My current installation size of TexLive on my Mac is about 1.3 GB. The complete docker image with the same stuff is only about 1.0 GB big.  

> So IMHO the only real advantage is faster (and maybe simpler) installation of Latex . In that case it is probably easier to bundle Texstudio with Latex in the docker image.
This sounds very interesting. Would this be a possible feature?

**Comment by MeanSquaredError** [comment]
My guess is that the docker image with TexLive lacks some of the packages that the native installation has, but it also could be that the docker image is somehow compressed.

It is possible to build a Linux docker image with TeXstudio and TexLive , but I am not sure if there would be any volunteer to maintain such a docker image with a recent version of TeXstudio and TexLive in it.

The other option is to use a native installation of TeXstudio with TexLive from a docker file. I think this should be possible just by configuring the TeXstudio commands and will not require any changes to TeXstudio. You can do that by configuring the TeXstudio external commands ( enable advanced options and then go to Options / Configure TeXstudio / Commands ) to run from the docker image. Some of the features like autogeneration of .cwl files will not work because TeXstudio relies on running pdflatex/kpsewhich directly by name but these feature should not affect the main workflow of the user.

**Comment by sunderme** [comment]
I don't think that docker provides any meaningful help.
Configuring docker to handle local data is probably not trivial and it is not really the intended use case.
In any case, if someone wants to set up a system like this, okay, but it is not the task of the tex editor.
