### ISSUE TITLE
Would TeXstudio be able to put itself at front when it receives a citation push?

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#857]
### Environment
- TeXstudio: 2.12.18
- Qt:  Using Qt Version 5.12.6, compiled with Qt 5.12.6 D

JabRef and Zotero (with BetterBibTeX extension) allow the user to select one or several references and to push them to TeXstudio. 

JabRef has this extra feature that, when the references are pushed, TeXstudio has the focus and, more importantly, is put in front.

Though this is probably a Java feature, it would be nice if it would be available with Zotero/BetterBibTeX as well. I asked for this in [this issue](https://github.com/retorquere/zotero-better-bibtex/issues/1371) and the BetterBibTeX developer answered:

>WRT putting texstudio back up after push, it'd be more logical to have texstudio put itself at front (configurably maybe) when it receives a citation push. That would solve it for all programs that do such pushes rather than having each have to reimplement it. Are you OK with giving that a try first?

Do you think this is feasible from the TeXstudio side?

**Comment by sunderme** [comment]
a quick glance into documentation tells that it may be possible on linux (depending on the window manager) but not on windows ...
Not sure if it is worth the effort ...

**Comment by MeanSquaredError** [comment]
I just looked at their code at
https://github.com/retorquere/zotero-better-bibtex/blob/master/content/tex-studio.ts
and it seems that by "pushing" a citation they mean running TXS with the `--insert-cite` command-line option. Acting on their "push" is the easy part.

The hard part is actually making the TXS window a foreground one while it is in the background. There is no non-hacky way to do that in Windows. MS has documented when a process can make a window a foreground one (see the Remarks section):
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow

In our case it means that the process that owns the current foreground window (and this is Zotero) has to call AllowSetForegroundWindow to allow TXS to set the foreground window. However if they go through the process of calling AllowSetForegroundWindow for TXS then they can just bring TXS to the foreground instead of calling AllowSetForegroundWindow for TXS.

So there is a good reason why JabRef takes care of bringing the TXS window to the front. Basically there is no other sane way to do that.

**Comment by sunderme** [comment]
so, in consequence, no.

**Comment by dbitouze** [comment]
@MeanSquaredError 

>So there is a good reason why JabRef takes care of bringing the TXS window to the front.

And do you think this is only feasible with Java (upon which JabRef is built). Would Zotero be able to do that as well?

**Comment by MeanSquaredError** [comment]
I am not familiar with the technology behind Zotero. 

After a quick glance at their source code it seems that Zotero is a javascript/ecmascript desktop application that uses nodejs. If that's the case indeed then they should be able to call winapi functions through some package like node-ffi ( https://github.com/node-ffi/node-ffi ),  therefore invoking the relevant winapi functions to move the TXS window to the foreground.

**Comment by dbitouze** [comment]
>After a quick glance at their source code it seems that Zotero is a javascript/ecmascript desktop application that uses nodejs.

[Seems to not be the case](https://github.com/retorquere/zotero-better-bibtex/issues/1371#issuecomment-570934806). Sigh...
