### ISSUE TITLE
Embedded terminal in TexStudio window

### ISSUE THREAD

**Issue by Andersmb** [texstudio-org/texstudio#864]
### Environment
- TeXstudio: 2.12.16 (git 2.12.16)
- Qt: 5.12.3
- OS: MacOS Mojave 10.14.6
- TeX distribution: TeXLive 2018

### Expected behavior
Show a terminal embedded in the TXS window. Could be an additional tab in the Messages/Log/Preview/Results pane. See for example the layout of the PyCharm IDE.

I use the terminal a lot when editing latex, and I find it a bit annoying having to open a separate terminal window, trying to fit it on the same Desktop view as TXS. When TXS is in fullscreen, I need to keep the terminal window in a different Desktop, which inhibits seamless productivity.

**Comment by timhoffm** [comment]
Last time I thought about this, there hasn't been any suitable terminal widget. And writing that ourselves would be a significant effort. Does anybody know if the situation got better and there is some terminal widget out there, we could reuse?

**Comment by MeanSquaredError** [comment]
No stable and supported terminal widgets that I know of.

Qt has the Qt serial port example
https://doc.qt.io/qt-5/qtserialport-terminal-example.html 
that comes with the Qt examples. Of course it is not really a widget but a standalone application, so I think it is not well suited for running in a tab. But I guess it could be used as a starting point if nothing better is found.  Also it connects to a real terminal device (in the case of the example a serial port), which is OK with Linux because it has /dev/ttyX, but I am not sure how that would be made general enough to support Windows.

The most straighforward approach for TXS would be to start the corresponding shell (bash or cmd.exe) then connect the corresponding terminal widget to the shell process through three pipes/sockets (stdin, stdout and stderr) and then work as a middleman piping the data through these pipes/sockets. Would be nice to have a widget that can take care of that, so that TXS would not have to implement all of that.

**Comment by OgreTransporter** [comment]
Example, working on Windows 10 and Ubuntu 19.04+: https://github.com/OgreTransporter/MinQtShellWidget

Wouldn't it be easier to install a Python console instead of various system dependent terminals?

**Comment by axkibe** [comment]
QSerialPort is way to basic, just imagine all the terminal emulation ESC-codes one would have to implement!

I just looked around
https://github.com/lxqt/qtermwidget
looks promising. Based on konsole, but stripped of all KDE-dependencies.

**Comment by benibela** [comment]
Closing, since #993 added qtermwidget for Linux
