### ISSUE TITLE
Texstudio failed to find pdf

### ISSUE THREAD

**Issue by JJ543** [texstudio-org/texstudio#905]
Hi, 

I'm very new to tex and I'm using Texstudio for OSX to type my work.
I just update program version to 2.12.22-osx, and have already installed Miktex.
The configuration of texstudio is as the default.

![Screen Shot 2020-01-26 at 17 57 03](https://user-images.githubusercontent.com/60312241/73132946-59c24580-4065-11ea-8157-5bc1d02ceb97.png)

![Screen Shot 2020-01-26 at 17 57 15](https://user-images.githubusercontent.com/60312241/73132952-6181ea00-4065-11ea-8c1c-7363c1764e70.png)

But when I try to show the pdf, there was a message said that the program could not find the file.

It shows error message
**failed to find file ".......pdf" perhaps it has been deleted.**

Just yesterday when I tried to run, it did not show this error. 
The pdf can be viewed normally.
But today, it cannot show the pdf and my pdf file was gone from the directory.

I have tried to change the file's directory and update my miktex, but still does not work.

Any suggest for me? 
Thank you in advanced

JJ

### Environment
- TeXstudio:  2.12.22 OsX
- Qt:  
- OS:  Mac
- TeX distribution:  miktex

**Comment by MeanSquaredError** [comment]
Maybe the pdf file has been deleted indeed? Have you checked whether the pdf file exists in the directory where TeXstudio is looking for it (most likely the same directory where your .tex file is located).

**Comment by billtubbs** [comment]
I have the same problem.  The pdf has indeed disappeared.  But why is the pdf needed to compile a Tex document?  Can't I reproduce it?

**Comment by octaeder** [comment]
you should have a tex document open in txs. if it has been compiled then the pdf viewer should find the target pdf.
Without the tex file there can be problems. Target pdf file may also disappear when the compile isn't successfull.

**Comment by MeanSquaredError** [comment]
@billtubbs The .pdf file is not needed in order to compile a .tex document, but you obviously need the .pdf in order to view it. You should be able to regenerate the .pdf by opening the corresponding .tex file and then compiling it by pressing F6 or by choosing the Tools/Compile menu item. Then you should be able to view the generated .pdf file.

**Comment by billtubbs** [comment]
Thanks @MeanSquaredError.  I resolved the problem on stackoverflow.
 - [TexStudio reports "Process exited with error(s)" but there is no error message](https://tex.stackexchange.com/questions/681096/texstudio-reports-process-exited-with-errors-but-there-is-no-error-message)

It was caused by a compile error that did not show in the 'Messages' or 'Log' pane.  I found the error by opening the .Log file.

The "failed to find pdf file" error is a bit misleading.  When the actual error is not shown on the screen, you're eye is drawn to it but this is a symptom not a cause.
