### ISSUE TITLE
Bug detecting Adobe Acrobat Reader

### ISSUE THREAD

**Issue by OgreTransporter** [texstudio-org/texstudio#914]
### Environment
- TeXstudio: git e3a4e40
- Qt: 5.14.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Detect installed Adobe Reader - whether version 9, X or DC.

### Actual behavior
Current Adobe Reader DC could not be found.

### How to reproduce
Delete configuration or reset external PDF viewer.

**Comment by MeanSquaredError** [comment]
Does it reset the external PDF viewer setting to some incorrect non-empty value or does it set it to an empty value?

**Comment by sunderme** [comment]
works fine on a quick test.
txs looks for programs associated to the "pdf" extension which are called "AcroRd32.exe".

**Comment by MeanSquaredError** [comment]
It works fine on my Windows machine too. However looking at the code it seems that TXS fetches the PDF viewer on Windows using:
```
QString getCommandLineViewPdfExternal()
{
	QString def = W32_FileAssociation(".pdf");
	if (!def.isEmpty())
		return def;

	foreach (const QString &p, getProgramFilesPaths())
		if (QDir(p + "Adobe").exists())
			foreach (const QString &rv, QDir(p + "Adobe").entryList(QStringList() << "Reader*", QDir::Dirs, QDir::Time)) {
				QString x = p + "Adobe/" + rv + "/Reader/AcroRd32.exe";
				if (QFile::exists(x)) return "\"" + x + "\" \"?am.pdf\"";
			}
	return "";
}
```

So if `W32_FileAssociation` returns successfully, we just pass it back without changes and without trying to look of AcroRd32.exe. Windows is notorious for having over-complex rules for the resolution of file associations. So it is quite possible that the registry on the user's computer is slightly damaged, so that resolution of file associations works from the command line and/or desktop but fails from TXS. I have seen way too many such cases in the past. Actually my Windows machine has similar problems with incorrectly setup file associations that I am too lazy to investigate. They somehow work magically, but a call to `AssocQueryStringA` (like TXS does in `W32_FileAssociation`) would probably return an incorrect value.

That is why I asked if TXS studio resets the value of the external PDF viewer to an empty string of to an incorrect non-empty string. The incorrect non-empty string is a sign that there is some slight problem with the registry.

**Comment by OgreTransporter** [comment]
W32_FileAssociation does not work for me. This is due to Windows 10, which sometimes has Edge set as the PDF viewer. I have solved this as follows:

```
QString getCommandLineViewPdfExternal()
{
	QString def = W32_FileAssociation(".pdf");
	if (!def.isEmpty())
		return def;

	foreach (const QString &p, getProgramFilesPaths())
		if (QDir(p + "Adobe").exists() {
			QDirIterator it(p + "Adobe", QStringList() << "AcroRd32.exe", QDir::Files, QDirIterator::Subdirectories);
			while (it.hasNext()) return "\" + QDir::toNativeSeparators(it.next()) + "\" \"?am.pdf\""
		}
	return "";
}
```

The file search works better this way. I can't create a commit right now, I can deliver it later.

**Comment by MeanSquaredError** [comment]
The proposed fix will fail if QDirIterator finds only one matching file. Also that will fail for most users because you are returning the second match and even if it works fine for you there is absolutely no guarantee that for everyone the second match is the correct one.

**Comment by OgreTransporter** [comment]
I aggree, ``If`` is better.

**Comment by OgreTransporter** [comment]
Fixed
