### ISSUE TITLE
Adding QtPdf support

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#940]
Starting from qt 5.15, qt will offer a qtpdf module. In order to,avoid external dependencies, support for that module would be useful. Anyone interested in implementing this ?
### Environment
- TeXstudio: 3.x
- Qt: 5.15
- OS: all
- TeX distribution: n/a

**Comment by MeanSquaredError** [comment]
Fedora 30 (the distribution that I use) still uses with Qt5.12
Fedora 31 (the latest stable distribution)  uses Qt5.13
Fedora Rawhide (the latest dev. distribution) uses Qt5.13

So I guess Fedora lags a bit with regard to the latest Qt5 releases. I wonder what would be the correct approach:

1. Keep the current PDF code, add QtPdf as a second option and use QtPdf if Qt version is >= 5.15. Better compatibility but more complex code to maintain.
2. Switch to QtPdf, anyway and remove the old code. In this case testing TXS on these distributions would require linking to Qt statically. Worse compatibility but simpler code.

Setting the project requirements to Qt5.15+ would probably help with a slightly cleaner code in a couple of places (e.g. `QAtomicInteger<bool>` instead of `QAtomicInt`, etc.).

**Comment by sunderme** [comment]
Qt 5.15 is out as *alpha* now and it can be installed with the qt installer. (Switching between different qt version is simple)

Poppler needs to stay for now. But all our feature transitions have been done with selective configurations to simplify it, so that is not really an issue.

**Comment by a-reisberg** [comment]
This is something I would love to do and in fact looked a bit into a year back while I was working on the flicker-free pdf update.  It would be great since pdfium is so much faster than poppler.  Unfortunately, I haven't been able to find the bandwidth for this yet.

**Comment by sunderme** [comment]
apparently qtpdf has not materialized ...
