### ISSUE TITLE
Enhancement: option to auto-hide auxiliary build files

### ISSUE THREAD

**Issue by thomas-daniels** [texstudio-org/texstudio#964]
Several auxiliary files are generated while building LaTeX documents, cluttering the directory with the source files. It would be nice if TeXstudio offered an option to hide these files. The editor TexitEasy offers this for example. This can be achieved by creating a `.hidden` file (Linux), `chflags +h` (Mac) or `attrib +h` (Windows). [Although this might not be the best approach for Windows, because [hidden auxiliary files cause some issues.](https://tex.stackexchange.com/questions/184925/tex-engine-cant-write-on-hidden-aux-files-in-windows)]

**Comment by MeanSquaredError** [comment]
You can set an output directory which is different from the directory holding your source files. This pretty much takes care of the clutter.

**Comment by sunderme** [comment]
And there is the clean command to get rid of all the files easily

**Comment by MikeGitb** [comment]
> You can set an output directory which is different from the directory holding your source files. This pretty much takes care of the clutter.

Could you point me to where this is done? I was looking for such an option an couldn't find it.

**Comment by MeanSquaredError** [comment]
It is not a single option, but rather a combination of options. Assuming that you use texlive and you want to set `/home/john/texout` as your output directory you can do the following:

1. Open `Options / Configure TeXstudio...` and then enable `Show Advanced Options` (lower left corner of the configuration popup window).

2. Go to `Build` settings and then set default compiler as 
`pdflatex -synctex=1 -interaction=nonstopmode -output-directory=/home/john/texout %.tex`
(here the important part is `-output-directory`

3. On the same `Build` screen add `/home/john/texout` to the directory lists in 
`Additional Search Paths / Log File`
`Additional Search Paths / PDF File`

4. If you are using the external PDF viewer, go to the `Commands` settings screen and set `External PDF viewer`, so that it can find the PDF file, e.g.
`xdg-open ?p{pdf}:ame > /dev/null`
(this can vary depending on your PDF viewer)

5. If you have a build script that generates any article images into your output directory you probably want a recent version of texlive (after 2019-05-07) because it has a bug which prevents it from searching for graphics in the output directory:
https://tug.org/pipermail/tex-k/2019-May/003014.html
Alternatively if you have an older version of texlive you can use the following workaround that I use myself:
```
% Workaround a bug in the \includegraphics macro which fails to include images from the output directory
% For more details see
% docs/graphics_bug.txt
% https://github.com/latex3/latex2e/issues/145
\def\Gin@getbase#1{%
  \edef\Gin@tempa{%
    \def\noexpand\@tempa####1#1\space{%
      \def\noexpand\Gin@base{####1}}}%
  \@iffileonpath{\filename@area\filename@base#1}%
    {\Gin@tempa
     \expandafter\@tempa\@filef@und
     \edef\Gin@ext{#1}}{}}%
```
(you can place it either in the preamble or in a custom .cls file
only needed if you use old texlive and include graphics from the output directory)

**Comment by sunderme** [comment]
maybe a good overview to put in the wiki for future reference ?

**Comment by MeanSquaredError** [comment]
Yes, it is probably a good idea to add it to the Wiki, since the question of using a separate output directory seems to reappear now and then.

Maybe you can just copy the above description (with small changes) to the Wiki and then if users still have questions we can adjust it accordingly ?

**Comment by MikeGitb** [comment]
> It is not a single option, but rather a combination of options. Assuming that you use texlive and you want to set /home/john/texout as your output directory you can do the following:

Ah ok. I also helped me out by modifying the individual commands in the past (albeit on windows and I remember it wasn't trivial for a latex noop like me).  However, I forgot to save them when I reset my computer and was wondering if there was a integrated version by now.

> maybe a good overview to put in the wiki for future reference ?

Would appreciate that

**Comment by sunderme** [comment]
You should be able to put it into the wiki as well , I think.

**Comment by MeanSquaredError** [comment]
OK, let me try to add it to the wiki...

**Comment by MeanSquaredError** [comment]
OK, I added it to the "Tips And Tricks" page as a last item called "Using a separate output directory"
https://github.com/texstudio-org/texstudio/wiki/Tips-And-Tricks

**Comment by sunderme** [comment]
looks good, thanks
