### ISSUE TITLE
On win10 the save and cancel buttons are not visible.

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#995]
### Environment
TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Win10,
texlive
### Expected behavior
When Opening the Option->Configure Texstudio, the screen should make the "ok" or "save" and "cancel" visible at the bottom of the screen. 
### Actual behavior
As of now, Options -> configure the screen immediately changes to 100+ % of fullscreen, 
in the bottom of the screen some button seem to exist, but they cannot be clicked even if you know which button to expect.  

### How to reproduce
Should work

**Comment by gaplin** [comment]
Same behaviour on newer versions:

### Environment
- TeXstudio: 4.4.1
- Qt: 6.4.1
- OS: Windows 11
- TeX distribution: miktex

**Comment by octaeder** [comment]
My txs build of current master with Qt 6.4.2, Win10 opens a config dialog of size 1378x864 (same as with 4.4.1). I think this should be small enough for current displays (but not for HD ready). Screenshot scaled to 50%:

![grafik](https://user-images.githubusercontent.com/102688820/213323729-26c73e5e-e12a-42ce-9273-e7758c4ad1b3.png)

**Comment by gaplin** [comment]
On my laptop there is a 125% display scaling enabled in windows settings by default. If I disable it, the dialog is fully visible.
I think that 125% scaling on laptops is quite common so making this window a little smaller might be a good idea.

**Comment by octaeder** [comment]
When I scale the given size of the dialog by 125% the result is 1733x1080. So it should still fit on a FullHD screen. Can you explain why the ok and cancel buttons are not visible on your screen?

Maybe it could be useful to know following about your display: Number of pixels in horizontal and vertical direction, the screen format and the length of the diagonal.

**Comment by gaplin** [comment]
It's typical 1920x1080(16:9) 15,6 inch screen.
I'll attach screenshot how it looks. Buttons are hidden behind windows task bar.

![image](https://user-images.githubusercontent.com/50521366/213588591-9a3db41c-a5d8-4baa-8b87-1c0e725f1204.png)

**Comment by octaeder** [comment]
I can't figure out how the size is set. There seems to be code in configdialog.cpp (l. 600ff) which tries to reduce the window size. But program control returns before any change is done. Reason is that the size used for comparison is less than the screen size. But even forcing the code to set the dialog size to a smaller value doesn't work.
It seems normal that dialog windows do not cover the taskbar, so the taskbar is always on top. Workaround for your issue: Make the taskbar disappear automatically or move the dialog window upwards with cursor keys (s. window menu you can open at the upper left).

**Comment by sunderme** [comment]
the best solution is to maximize the config window in those cases.

**Comment by gaplin** [comment]
Ye, maximizing is actually good workaround, because this window will be opened maximized next time.

Also I've played a bit with the configDialog code. It seems like the //limit dialog size section (l. 603) doesn't change anything.
Actually the resize method doesn't work at all. 

Setting fixed size for dialog using its own size actually resizes it.
After doing: (btw. in given ss in 613l. there is screen.left when comparing to y axis, but that's not related to this issue.)
![image](https://user-images.githubusercontent.com/50521366/213816600-84e4baab-ae80-41a5-a998-0df00123c770.png)

the dialog looks like this:
![image](https://user-images.githubusercontent.com/50521366/213814158-9e8d0828-10f3-4bdb-bfe6-150cc887382f.png)

Other thing is that screen.width and height returns size of whole screen not of main window. 
So even if hypothetically the dialog exceeded for some reason my screen height and resizing would work then buttons would still appear below taskbar.

**Comment by octaeder** [comment]
To avoid the problem with the taskbar one should use availableGeometry(). Maybe there have to be solved some OS specific problems (s. [Qt doc](https://doc.qt.io/qt-6/qscreen.html#availableGeometry-prop)).

The real size of the final config dialog is (1378, 864). When I debugged the code I was surprised that width() and height() delivered the smaller size (1116, 300). In fact this is the size given in the geometry property of the QDialog widged named ConfigDialog (s. configdialog.ui).

When I set windows scaling to 200% then screen size decreases to (960, 600) -- format is 16:10. Now the delivered size (1378, 864) is larger. So final size is (960, 600). But the ok/cancel buttons are (almost) not visible (taskbar with two lines).

Is the window resizable when you use setFixedSize?

**Comment by gaplin** [comment]
No, it's not resizable and the maximize button is disabled.
I've tried also setting maximumSize to parent->size(). Buttons are now visible but the maximize button is disabled.
Ss with maximized parent window.

![image](https://user-images.githubusercontent.com/50521366/213866472-752d3e1f-5d9e-4255-865d-74adbd60036e.png)

Ss with parent window resized to minimum values:
![image](https://user-images.githubusercontent.com/50521366/213866551-a0f974fd-3004-43d1-b8e5-8f864585b5ae.png)

**Comment by gaplin** [comment]
Ok, so after further investigation this piece of code in cofigDialog doesn't matter at all and imo should be removed for now because it is actually misleading.
![image](https://user-images.githubusercontent.com/50521366/213867808-61d70c12-b077-40ba-a686-fe69df582c8e.png)

The reason is that in configManager after configDialog creation there is another resizing called:
![image](https://user-images.githubusercontent.com/50521366/213867824-880e1889-0b38-494d-91f8-121f5264c0b6.png)

And this resizing is using min value of availableGeometry.height() and some h * height values for vertical part.
In my case h * height is 832 and height from geometry is 816. Both are too big, because maximized parent window has height of 793.
![image](https://user-images.githubusercontent.com/50521366/213868045-455d8372-1693-4163-902d-b68083b47540.png)

So the solution would be to put a lower number in resizeInFontHeight call(49 works for me with 125% scaling, but it breaks for bigger scaling) or stop calling it at all and handle resizing actually in configDialog.

**Comment by octaeder** [comment]
It seems that Qt can't figure out the size of the dialog including decoration from the window manager (frameGeometry). I sum up the changes I would suggest:

```
configdialog.cpp:
-	QRect screen = QGuiApplication::primaryScreen()->geometry();
+	QRect screen = QGuiApplication::primaryScreen()->availableGeometry();

-		resize(nwidth, nheight);
+		resize(nwidth, nheight-31);

-			frameGeometry().bottom() > screen.bottom() ? screen.left() : y());
+			frameGeometry().bottom() > screen.bottom() ? screen.top() : y());
```
The  integer 31 is a rough approximation of the pixels needed for the decoration.

```
configdialog.ui;
-    <width>1116</width>
-    <height>300</height>
+    <width>1378</width>
+    <height>864</height>
```

```
configmanager.cpp:
-	UtilsUi::resizeInFontHeight(confDlg, 86, 52);
```

@gaplin Can you retest this? Do you make a pull request?

**Comment by gaplin** [comment]
I've retested this and new problem came up. Buttons are now fully visible but after the resizing is done the move() call is moving dialog always to top left corner.

I've figured out that position of dialog in constructor is always (0, 0) so moving should be done after window is visible on a screen. So I created new method moveIfExceedsScreen() and I'm calling it after exec() is called in configManager.
After all that it seems to work.

I would like to make a pull request. I'm getting 403 when I try to push new branch so I guess I need to get permission to do that.

**Comment by sunderme** [comment]
fixed constant probably don't do the trick on all systems (different scaling)

**Comment by gaplin** [comment]
That's probably true. 
But in my opinion it fixes most popular cases(full hd with 125% scaling which is enabled by default on many laptops).

**Comment by octaeder** [comment]
after new hints given [here](https://github.com/texstudio-org/texstudio/pull/2863#discussion_r1083457660) (in PR #2863) new PR #2868 should resolve the problem of calculating config window size (including window decorations).
